libopenstorage/openstorage

- config.yaml
- drivers.go
- drivers/vfs/vfs.go
Sample code for review and understanding driver code.
Few things is not clear to me.
1. Create()- In create function, the folder structure that is created, doesnt make any sense while mounting.
2. I have not implement, Mount function, since it is not required.
3. After mounting the volume in docker container, the data changes in that mounted folder is reflected in ``/var/lib/docker/volume/<volume-name>``
4. I want to understand, how the create/mount  folder/file is reflected to actual IO Path. It is not clear to me.
NOTE: This converted to local from nfs-driver.
Signed-off-by: Kunal Kushwaha <kunal.kushwaha@gmail.com>
> localfs, a zero-configuration driver 

- Makefile
We can deal with the errors from it later :)
> Fix make lint

- Makefile
fixed compiler to only compile btrfs if headers are installed
> fixed issue with fuse error messages during package list

- README.md
Fix a typo commincate --> communicate in Readme.md
Signed-off-by: Suhas Anand <suhas.04@gmail.com>
> Fix a typo to readme

- cmd/osd/main.go
@jvinod @adityadani putting this in a PR so you can see it, merging so i can do other work quickly, apologies
> clean up cmd/osd/main.go

- etc/bin/release.bash
Signed-off-by: Peter Edge <peter.edge@gmail.com>
> Start of release script

- api/server/server.go
- api/testing/testing_test.go
- cmd/osd/main.go
- config/config.go
- etc/config/config.yaml
- Enable volume api REST service on a port. (mgmtPort)
- Enable volume plugin api REST service on a port. (pluginPort)
> Running OSD REST service on ports along with sockets

- volume/drivers/aws/aws.go
AWS Create Volume was allocating device names, but it was never releasing them.
As a result, no more than 11 AWS volumes could be created.
> 167: Fixing AWS Create volume

- api/server/cluster.go
- cluster/manager.go
Old REST "GET Inspect Cluster Node" call was not implemented.
This fix implements the call, and is loosely based on REST "GET
Enumerate" call.
> PWX-2772: Implemented REST cluster/inspect/node

- pkg/mount/mount.go
PWX-3974: Revert immutable flag, only it was not set to begin with on mount failure.
> Pre mount state

- Dockerfile.osd
- Dockerfile.osd-dev
> Update golang version to 1.9.2

- csi/csi.go
- csi/csi_test.go
- csi/server.go
> csi: Create an interface for the gRPC server

- csi/controller.go
- csi/controller_test.go
> csi: ListVolumes Support

- api/client/client.go
- api/client/volume/client_volume_test.go
Hey we need this functionality so we can support https and certificates in our client.
> Add SetTLS function to client so we can support https

- csi/node.go
- csi/node_test.go
Support for NodePublishVolume
Closes #234
> csi: Mount Support

- pkg/storageops/storageops.go
This is basically a generic version of storage ops interface in the aws driver: https://github.com/libopenstorage/openstorage/blob/master/volume/drivers/aws/aws_storage.go#L44
> Add storage operations interface which will be implemented by providers like AWS and GCE

- api/api.go
- api/client/volume/client.go
- api/client/volume/client_volume_test.go
- api/server/creds.go
- api/server/volume.go
- volume/drivers/aws/aws.go
- volume/drivers/buse/buse.go
- volume/drivers/coprhd/coprhd.go
- volume/drivers/fuse/volume_driver.go
- volume/drivers/mock/driver.mock.go
- volume/drivers/nfs/nfs.go
- volume/drivers/vfs/vfs.go
- volume/volume.go
- volume/volume_not_supported.go
These APIs allow clients to configure and manage credentials for
different cloud providers.
> Adding credential APIs.

- csi/csi_test.go
- csi/identity.go
- csi/identity_test.go
> csi: Update identity name

- vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
- vendor/vendor.json
> csi: Update to CSI Spec v0.1.0

- csi/csi.go
- csi/csi_test.go
> csi: Do not register driver when starting the csi server.

- csi/controller.go
- csi/controller_test.go
- csi/csi_test.go
- csi/identity.go
- csi/identity_test.go
> csi: Update gRPC errors

- api/client/volume/client.go
- api/client/volume/client_volume_test.go
- api/client/volume/volume.go
- api/server/creds.go
- api/server/creds_test.go
Also remove unit test for credentials that does work.
> Pass credential UIUD in url rather than as paramter.

- pkg/mount/mount.go
- pkg/mount/nfs.go
- volume/drivers/nfs/nfs.go
Signed-off-by: bouviti <timothy.bouvier@verizon.com>
**What this PR does / why we need it**:  Support for multiple NFS servers to allocate docker volumes from
Closes # NA
**Special notes for your reviewer**: Not backwards compatible with existing NFS volume driver. Is that worth adding support for?
> support for multiple NFS servers

- api/server/cluster_test.go
Tests Failing because of issue #279 , #280 , #281 , #282 , #283
> Adding test cases for Cluster REST endpoints.

- api/server/volume_test.go
This PR is to remove the style of unit tests for the Volume API in api/testing/restapi_test.go
and implement all of those tests in this file.
This tries to build a base for #299 , once all unit tests for volume are written in one place.
Closes #
> New volume unit tests

- api/server/volume_test.go
Signed-off-by: Ram Suradkar <ram@infracloud.io>
This PR is to add of more unit tests to cover all volume unit test scenarios
This tries to build a base for #299 , once all unit tests for volume are written in one place.
Closes #
> Adding Volume API Unit test case.

- api/api.pb.go
- api/api.proto
- api/server/cluster.go
- api/server/volume.go
- api/swagger/swagger.json
Fix for our documentation, it was complaining about alot of api's not having certain fields or having no type.
> fix documentation so we can go live with the new API

- cmd/osd-sanity/sanity_test.go
- pkg/sanity/osd_test_util.go
- pkg/sanity/sanity.go
- pkg/sanity/volume.go
This PR works on the osd-sanity tests for Volume API's
Closes #
> Volume create,enumerate API osd-sanity

- Makefile
- api/server/cluster.go
- api/server/volume.go
- api/swagger/swagger.json
- cmd/osd/main.go
- config/config.go
Signed-off-by: Paul Theunis <paul@portworx.com>
Remove 2nd tags caused confusion in the documentation.
> Remove 2nd tags from all api's and update contact information to github

- api/swagger/swagger.json
- cmd/osd/main.go
Signed-off-by: Paul Theunis <paul@portworx.com
Requested to remove contact info and update the api Summary
> change description of the api, remove contact info

- pkg/sanity/osd_test_util.go
- pkg/sanity/snapshot.go
- pkg/sanity/volume.go
This PR adds snapshot tests, volume ha-update and resize tests to osd-sanity and fixes the size issue in previous tests.
Closes #
> osd sanity haupdate,snapshot,resize fix.

- pkg/sanity/cluster.go
osd-sanity cluster endpoints
Closes #
> osd-sanity cluster endpoints.

- api/server/cluster_test.go
- api/server/testutils_test.go
Adds more unit tests for Cluster API and cleans up some issues.
Closes #279 #280 #283 
> Fixes #279,#280,#283 and more unit tests.

- api/server/cluster.go
- api/swagger/swagger.json
- osdconfig/struct.go
Swagger comments had bug. In particular, the error was due to tab spacing. Now fixed
> swagger bug fix

- api/api.go
> Add metadata field for backup info

- pkg/storageops/gce/gce.go
- pkg/storageops/test/storageops.go
> fix label based filtering for GCE enumerate

- cmd/osd-sanity/cloud-backup.yaml
- cmd/osd-sanity/sanity_test.go
- pkg/sanity/backup_restore.go
- pkg/sanity/creds.go
- pkg/sanity/sanity.go
- pkg/sanity/volume.go
Addtion of Backup and Restore tests to osd-sanity
Closes #
> Osd sanity bkp restore

- pkg/sanity/backup_restore.go
> Fix sanity test

- api/swagger/swagger.json
- osdconfig/struct.go
More changes in osdconfig struct were required based on requirements in Portworx code. This PR fixes some struct inconsistencies and struct tags.
None
> Osdconfig struct update 2

- api/client/cluster/client.go
- api/client/cluster/cluster.go
- api/client/cluster/osdconfig.go
- cli/cluster.go
- cluster/cluster.go
- pkg/sanity/cluster.go
Reverts libopenstorage/openstorage#390
> Revert "Reorganize to create cluster.ClusterClient"

- api/api.pb.go
- api/api.proto
- api/swagger/swagger.json
Signed-off-by: Paul Theunis <paul@portworx.com>
It seems like one of my check-ins was possibly reverted somehow.
This fixes make docs.
> somehow api.pb.go / api.proto have been reverted

- .gitignore
- api/api.go
> Add typedef for OpType for Cloudbackup

- api/server/cluster.go
- api/server/server.go
- api/server/testutils_test.go
- cluster/manager.go
- secrets/secrets.go
Signed-off-by: Ram <ram.suradkar@portworx.com>
Removed unnecessary Manager object and related NewSecretManager()
> Cleanup for secrets API

- api/client/cluster/client.go
- api/server/routes.go
- api/server/schedpolicy.go
- api/server/schedpolicy_test.go
- cluster/mock/cluster.mock.go
- schedpolicy/mock/schedpolicy.mock.go
- schedpolicy/sched_policy.go
Signed-off-by: Ram <ram.suradkar@portworx.com>
This PR add schedule policy Get API into osd, which will returns requested policy detail
Closes #
> Adding Schedule policy Get API

- api/api.go
- api/api.pb.go
- api/api.pb.gw.go
- api/api.proto
- api/client/sdk/js/api_pb.js
- api/client/sdk/python/api_pb2.py
- api/client/sdk/ruby/api_pb.rb
- api/server/sdk/api/api.swagger.json
- api/server/sdk/cloud_backup_test.go
- api/server/sdk/cluster.go
- api/server/sdk/cluster_test.go
- api/server/sdk/volume_ops.go
- api/server/sdk/volume_ops_test.go
- api/server/sdk/volume_snapshot.go
- api/server/sdk/volume_snapshot_test.go
- hack/git-add-proto-generated.sh
- pkg/flexvolume/flexvolume.pb.go
- pkg/flexvolume/flexvolume.pb.gw.go
- pkg/jsonpb/testing/testing.pb.go
Allow clients to have more flexibility by only returning ids in the Enumerates.
Closes #475 
Part of #407
Do not review the generated files commit.
> Sdk enumerate

- api/client/sdk/ruby/Makefile
Signed-off-by: Ram Suradkar <ram.suradkar@portworx.com>
This PR fixes bug "make proto" broken. 
Closes #495 
> Fix for bug "make proto" is broken

- api/api.pb.go
- api/api.pb.gw.go
- api/client/sdk/js/api_pb.js
- api/client/sdk/python/api_pb2.py
- api/client/sdk/ruby/api_pb.rb
- api/server/sdk/api/api.swagger.json
> generating code from proto

- pkg/flexvolume/flexvolume.pb.go
- pkg/flexvolume/flexvolume.pb.gw.go
- pkg/jsonpb/testing/testing.pb.go
> generated code from proto

- api/api.pb.go
- api/api.pb.gw.go
- api/server/sdk/api/api.swagger.json
- pkg/flexvolume/flexvolume.pb.go
- pkg/flexvolume/flexvolume.pb.gw.go
- pkg/jsonpb/testing/testing.pb.go
Seems that the previous files generated are done by an older proto compiler. We will need a method of checking for this on Travis.
> Update Generated Files

- api/api.go
- api/api.pb.go
- api/api.pb.gw.go
- api/api.proto
- api/client/sdk/js/api_grpc_pb.js
- api/client/sdk/js/api_pb.js
- api/client/sdk/python/api_pb2.py
- api/client/sdk/python/api_pb2_grpc.py
- api/client/sdk/ruby/api_pb.rb
- api/client/sdk/ruby/api_services_pb.rb
- api/server/sdk/api/api.swagger.json
- api/server/sdk/cloud_backup.go
- api/server/sdk/cloud_backup_test.go
- api/server/sdk/cluster.go
- api/server/sdk/cluster_test.go
- api/server/sdk/credentials.go
- api/server/sdk/node.go
- api/server/sdk/node_test.go
- api/server/sdk/objectstore.go
- api/server/sdk/schedule_policy.go
- api/server/sdk/sdk_test.go
- api/server/sdk/server.go
- api/server/sdk/volume_ops.go
- api/server/sdk/volume_ops_test.go
- api/server/sdk/volume_snapshot.go
* Major updates to documentation
* Updated gRPC REST Gateway entry points
* Cleaned up Cluster APIs by creating new Node Service
* Added InspectCurrent() to both Cluster and Node services
* Changed name of OpenStorageVolume.Set() to Update() to match others
* Cleaned up errors to return NotFound when the key is not found.
* Removed VolumeSpec from Clone() since it was not needed.
Closes #527
>  sdk: Create new Node Service and Clean up docs

- pkg/storageops/gce/gce.go
- pkg/storageops/gce/gce_test.go
- pkg/storageops/test/storageops.go
Lower casing all the label values to avoid failures from GCE apis
Closes #
> Lower case label keys and value for GCE

- cluster/manager/manager.go
- cluster.Enumerate must return all nodes, even those decommissioned
- nodeCache is init when node joins cluster
- it is kept updated by the watch
Closes #
> Do not filter decommissioned nodes in cluster.Enumerate

- api/swagger/swagger.json
- osdconfig/struct.go
To add new fields in osdconfig struct for kvdb consul tls connect
Closes #557 
> Consul TLS connect update in osdconfig

- Makefile
- api/server/sdk/api/api.swagger.json
- tools/sdkver/sdkver.go
Needed a program to extract the SDK version and update certain files. For now it outputs the version to stdout and updates `api.swagger.json`
This will be very helpful to autogenerate the documents with the correct version.
> sdkver a tool to update SDK versions

- pkg/storageops/aws/aws.go
- pkg/storageops/gce/gce.go
- pkg/storageops/storageops.go
- throwing error for DeviceMappings if unable to get actual device path
- throwing new error ErrInvalidDevicePath for device path check errors
Closes #
> Putting device path check in storageops for GCE

- pkg/options/options.go
Adds more documentation to the Options used by a VolumeDriver
> Add detailed documentation to the Options specified in pkg/options

- alert/alert.go
- alert/alert_kvdb.go
- alerts/README.md
- alerts/action.go
- alerts/alerts.go
- alerts/alerts_test.go
- alerts/api.go
- alerts/filter.go
- alerts/opt.go
- alerts/rule.go
This PR is a follow up on previous pr #575 and fixes a bug and adds new filter types.
Also added deprecated tag to older alert pkg.
Closes #572 
> alerts new filter types and enum bug fix

- api/server/cluster.go
code which check for specific errors does not work because of the prefix. 
Closes #
Signed-off-by: sangleganesh <ganesh@portworx.com>
> Do not add prefix to error

- api/api.pb.go
- api/api.proto
- api/server/sdk/api/api.swagger.json
There was some confusion regarding the use of SdkCloudBackupEnumerateRequest
this documents the valid combinations and their expectations.
> Document CloudbackupEnumerateRequest better

- osdconfig/struct.go
> Adding yaml tags to osdconfig

- api/server/sdk/alerts.go
- api/server/sdk/server.go
as discussed offline, this pr allows others to leverage server side components that comply to SDK.
Closes #
> adding new method for obtaining alerts server

- .travis.yml
Trying to update the travis spec to see if it fixes the issues causing failures in the unit tests.
> Fixing travis CI

- alerts/alerts.go
> delete alert before any put

- SDK_CHANGELOG.md
> Fix SDK_CHANGELOG

- SDK_CHANGELOG.md
updated changelog to reflect new minor version
Closes #
> changelog update

- cluster/manager/manager.go
- In the updateClusterStatus loop, when a node is detected online/offline we
notify the registered listeners about the update. In the same loop we also
update the node cache.
- If a storage listener takes longer time to respond to the update, the node cache update
gets delayed. A subsequent cluster.Enumerate query hence returns stale information.
> Notify the Storage Listeners after node cache is updated.

- .travis.yml
- Makefile
- tools/sdkver/sdkver.go
Cherry-pick 70f5127 and update it for the 0.9.x release branch
> Toolcheck 0.9

- SDK_CHANGELOG.md
- api/api.go
- api/api.pb.go
- api/api.proto
- api/server/sdk/api/api.swagger.json
- api/server/sdk/cloud_backup.go
- api/server/sdk/cloud_backup_test.go
> Cherry picks and updated sdk version to 0.24.0

- Makefile
- SDK_CHANGELOG.md
- api/api.pb.go
- api/api.proto
- api/server/sdk/api/api.swagger.json
SDK version needs to be frozen since this branch is about to release.
> Freeze SDK versions at 0.22.x

- cluster/manager/pair.go
> Don't return error if re-pairing with a cluster with same token

- cluster/manager/pair.go
> Pick another cluster pair as default if the current default is deleted

- cluster/manager/pair.go
> Change cluster pair log to debug

- SDK_CHANGELOG.md
- api/api.pb.go
- api/api.proto
- api/server/sdk/alerts.go
- api/server/sdk/alerts_test.go
- api/server/sdk/api/api.swagger.json
alerts api is streaming and requires list of alerts to be split into chunks. this pr fixes a bug in chunking logic.
Closes #
> alerts chunking logic bug fix

- pkg/mount/mount.go
If the original mount path is read-only and we cannot chattr it,
then we create a bind mount in `/var/lib/osd/mounts`. We can then
chattr this bind mounted path and proceed with the mount.
Closes #
> Bind mount path so we can chattr on it.

- pkg/mount/mount.go
> Use bind mounts if chattr fails

- cluster/manager/manager.go
Follow up on the previous pr, changing osdconfig usage to a caller based api (no watches required)
Closes #
> changing osdconfig usage to caller

- cluster/manager/manager.go
> changing osdconfig usage to caller (#759)

- api/api.pb.go
- api/api.pb.gw.go
- api/api.proto
- api/client/volume/client.go
- api/server/migrate.go
- api/server/migrate_test.go
- api/server/sdk/api/api.swagger.json
- api/server/sdk/volume_migrate.go
- api/server/sdk/volume_migrate_test.go
- volume/drivers/mock/driver.mock.go
- volume/volume.go
- volume/volume_not_supported.go
> Add task id and cluster id to cloud migrate status request

- SDK_CHANGELOG.md
- api/api.pb.go
- api/api.proto
- api/server/sdk/api/api.swagger.json
> Update SDK version

- SDK_CHANGELOG.md
- api/api.pb.go
- api/api.pb.gw.go
- api/api.proto
- api/client/volume/client.go
- api/server/migrate.go
- api/server/migrate_test.go
- api/server/sdk/api/api.swagger.json
- api/server/sdk/volume_migrate.go
- api/server/sdk/volume_migrate_test.go
- volume/drivers/mock/driver.mock.go
- volume/volume.go
- volume/volume_not_supported.go
>  Add task id and cluster id to cloud migrate status request

- api/server/migrate.go
> Use empty request if nothing was sent for migrate status

- api/client/volume/client.go
- api/server/creds.go
- volume/errors.go
Sending http error code 422 when we get an error validating a credential.
Based on server error, return a fixed ErrInvalidCredential error to differentiate between invalid creds and other errors.
Closes #
> Returning 422 for invalid credentials

- api/client/cluster/client.go
- cluster/cluster.go
- cluster/cluster_not_supported.go
- cluster/manager/manager.go
- cluster/manager/manager_test.go
- cluster/mock/cluster.mock.go
This is a cherrypick from master.
Closes #
> Method to update scheduler node name

- api/server/volume.go
> Propagate correct error for rest clients

- api/server/backup_test.go
- volume/cloudbackup.go
> Update cloudbackup wait helper to use task id

- api/server/volume.go
Code had been commented out incorrectly during REST -> SDK refactoring.
Closes #814
> Re-add support for REST Set

- api/server/backup_test.go
> Fix mock tests for group cloud snapshots

- api/server/docker.go
- hack/docker-integration-test.sh
Docker calls were found that not all can be secured. The
list and unmount must be allowed to be insecure to make
docker ce work correctly.
Closes #
> Docker CE Volume API support for security

- api/api.pb.go
- api/api.proto
- api/server/sdk/api/api.swagger.json
The libopenstorage.github.io website markdown had syntax errors because of the comments in the api.proto file.
> Fix comments in proto file

- alerts/alerts_test.go
- api/client/cluster/client.go
- cluster/cluster.go
- cluster/cluster_not_supported.go
- cluster/manager/database.go
- cluster/manager/manager.go
- cluster/mock/cluster.mock.go
- cmd/osd/main.go
- vendor/github.com/portworx/kvdb/Dockerfile.kvdb
- vendor/github.com/portworx/kvdb/Makefile
- vendor/github.com/portworx/kvdb/README.md
- vendor/github.com/portworx/kvdb/common/common.go
- vendor/github.com/portworx/kvdb/consul/client.go
- vendor/github.com/portworx/kvdb/consul/kv_consul.go
- vendor/github.com/portworx/kvdb/etcd/common/common.go
- vendor/github.com/portworx/kvdb/etcd/v2/kv_etcd.go
- vendor/github.com/portworx/kvdb/etcd/v3/kv_etcd.go
- vendor/github.com/portworx/kvdb/kvdb.go
- vendor/github.com/portworx/kvdb/kvdb_controller_not_supported.go
- vendor/github.com/portworx/kvdb/mem/kv_mem.go
- vendor/github.com/portworx/kvdb/updates_collector.go
- vendor/vendor.json
Cherry-picks from master branch
- Update kvdb.Snapshot API.
Closes #
> Kvdb snapshot release 5.0

- api/api.go
- api/spec/spec_handler.go
- api/spec/spec_handler_test.go
Signed-off-by: prabir <prabir@portworx.com>
Closes #
> Spec handler fixup for queue_depth, add support for nodiscard

- api/api.go
- api/spec/spec_handler.go
- api/spec/spec_handler_test.go
Signed-off-by: prabir <prabir@portworx.com>
Closes #
> Spec handler fixup for queue_depth, add support for nodiscard (#833)

- api/client/request.go
cherry-pick from master for go-routine fix.
> Fix goroutine creation bug and add exponential back-off logic (#858)

- api/server/sdk/volume_migrate.go
We were returning the wrong error code for ownership denied.
> Change returned error to PermissionDenied

- pkg/storagepolicy/sdkstoragepolicy.go
- pkg/storagepolicy/sdkstoragepolicy_test.go
For Update Storage Policy: Instead of overwriting old volume specs with new specs. Merge old and new specs
Closes #
> Fix update policy bug

- pkg/storagepolicy/sdkstoragepolicy.go
- pkg/storagepolicy/sdkstoragepolicy_test.go
Cherry Pick for #887 
Closes #
> Cherry Pick Fix Update Storage policy bug

- pkg/storageops/aws/aws.go
- With AmazonLinux 2 OS used in EKS, the devices are exposed as nvme drives
where a normal device path /dev/xvdf points to /dev/nvme0n2
- Change the getActualDevicePath function to check if the device path returned by AWS is
a symbolic link to a an actual device.
- For certain instance types like c5 or m5, these symbolic links do not exist and hence for
them we will be still using the nvme list command. This command does not exist on AmazonLinux 2
> [AWS Storage Ops]: Always follow device symbolic links to get the parent devices.

- pkg/grpcserver/grpcutil.go
- pkg/util/wait.go
* Fixes timeout issue with `Connect` function
Closes #894
> Fix issue where Connect() would timeout intermittently

- api/server/backup_test.go
REST server unit tests were using gRPC instead of the REST server
> Update REST server unit tests

- cmd/osd/main.go
- pkg/auth/claims.go
- pkg/auth/claims_test.go
- pkg/auth/oidc.go
- pkg/auth/oidc_test.go
Some OIDCs like Auth0.com provide custom claims behind a namespace
Closes #909
> OIDC to support namespaced custom claims

- Makefile
> Freeze SDK Version 0.42.x

- api/server/sdk/volume_node_ops.go
- api/server/sdk/volume_ops.go
- csi/controller.go
- csi/controller_test.go
- csi/csi.go
- csi/csi_test.go
- csi/csisanity_test.go
- csi/node.go
- csi/node_test.go
- pkg/util/volume.go
> release-6.0: CSI Migration to SDK Server

- api/server/sdk/cloud_backup.go
- api/server/sdk/cloud_backup_test.go
If only one credential is configured for the user, it need not be passed in the input request.
Closes #
> Default credentials for cloud backup requests.

- api/server/sdk/credentials.go
- api/server/sdk/credentials_test.go
> Fix getting ownership from cred params

- api/server/migrate.go
- api/server/migrate_test.go
- volume/drivers/fake/fake.go
Cherry-pick Migration Auth from Master.
> Add authentication to REST Calls for Migration. (#936)

- api/api.go
- api/server/docker.go
- api/server/middleware_auth.go
- api/server/server.go
- api/spec/spec_handler.go
- api/spec/spec_handler_test.go
- cmd/osd/main.go
cherry pick of f3498608b2cf8936a446a0c6294383796dd4591a and 81eb976b4478463575e9ccc7f573f32f6b671188
> Rel60 dcos token secrets and k8s empty secret fix

- api/api.go
- api/server/backup.go
Also fix bug in the default creds path for enumerate.
Closes #
> CloudBackup enumerate status conversion.

- pkg/auth/oidc.go
> Fix ODIC->OIDC typo

- pkg/auth/oidc.go
cherry pick of 83a62207c8b18f5b1f61d5d8d6730a789488277b
> release-6.0: fix oidc typo

- api/server/migrate.go
- api/server/sdk/volume_migrate.go
> Fix Idempotency for migration starts (#967)

- api/server/sdk/volume_migrate.go
> Add driver check to Migration calls (#972)

- api/server/server.go
cherry pick of b3afe9f08e3469a094876d1eefb5de885880d2c8
> release-6.0: Add check for authProviderType before initializing secretsStore

- cmd/osd/main.go
- csi/csi.go
- csi/csi_test.go
cherry pick of 61b597cc37ae76fe06cdd251e4a367d085298346
> release-6.0: Add validation of SdkUds to CSI Server (#971)

- pkg/role/sdkserviceapi.go
same as #994 , against master branch
Closes #
> Add view storage policy rule for system.user (master)

- pkg/role/sdkserviceapi.go
Cherry-pick for master sp-role
Closes #
> Cherry-pick for Storage policy role system.user

- api/server/backup.go
- api/server/sdk/cloud_backup.go
- api/server/volume.go
- api/server/volume_test.go
> Fix Inspect and Cloud Backup Create

- pkg/storageops/azure/azure.go
- vendor/github.com/Azure/go-autorest/autorest/azure/auth/auth.go
- vendor/github.com/dimchansky/utfbom/LICENSE
- vendor/github.com/dimchansky/utfbom/README.md
- vendor/github.com/dimchansky/utfbom/go.mod
- vendor/github.com/dimchansky/utfbom/utfbom.go
- vendor/golang.org/x/crypto/pkcs12/bmp-string.go
- vendor/golang.org/x/crypto/pkcs12/crypto.go
- vendor/golang.org/x/crypto/pkcs12/errors.go
- vendor/golang.org/x/crypto/pkcs12/internal/rc2/rc2.go
- vendor/golang.org/x/crypto/pkcs12/mac.go
- vendor/golang.org/x/crypto/pkcs12/pbkdf.go
- vendor/golang.org/x/crypto/pkcs12/pkcs12.go
- vendor/golang.org/x/crypto/pkcs12/safebags.go
- vendor/vendor.json
> Use generic authorizer which uses different auth methods based on what is passed

- pkg/storageops/azure/azure.go
- vendor/github.com/Azure/go-autorest/autorest/azure/auth/auth.go
- vendor/github.com/Azure/go-autorest/autorest/azure/cli/profile.go
- vendor/github.com/Azure/go-autorest/autorest/azure/cli/token.go
- vendor/github.com/dimchansky/utfbom/LICENSE
- vendor/github.com/dimchansky/utfbom/README.md
- vendor/github.com/dimchansky/utfbom/go.mod
- vendor/github.com/dimchansky/utfbom/utfbom.go
- vendor/github.com/mitchellh/go-homedir/LICENSE
- vendor/github.com/mitchellh/go-homedir/README.md
- vendor/github.com/mitchellh/go-homedir/go.mod
- vendor/github.com/mitchellh/go-homedir/homedir.go
- vendor/golang.org/x/crypto/pkcs12/bmp-string.go
- vendor/golang.org/x/crypto/pkcs12/crypto.go
- vendor/golang.org/x/crypto/pkcs12/errors.go
- vendor/golang.org/x/crypto/pkcs12/internal/rc2/rc2.go
- vendor/golang.org/x/crypto/pkcs12/mac.go
- vendor/golang.org/x/crypto/pkcs12/pbkdf.go
- vendor/golang.org/x/crypto/pkcs12/pkcs12.go
- vendor/golang.org/x/crypto/pkcs12/safebags.go
- vendor/vendor.json
> Cherry pick: Generic authorizer for azure

- api/server/sdk/cloud_backup.go
- api/server/sdk/cloud_backup_test.go
> Clarify credential error message.

- api/server/sdk/cloud_backup.go
- api/server/sdk/cloud_backup_test.go
> Clarify credential error message. (#1009)

- cluster/manager/manager.go
- pkg/clusterdomain/clusterdomain.go
Add a new error type ErrNoClusterDomainProvided.
Closes #
> Add new error type ErrNoClusterDomainProvided

- api/server/sdk/cloud_backup.go
- api/server/sdk/cloud_backup_test.go
> Auth support for cloudbackup status and change-state apis.

- pkg/auth/claims.go
- pkg/auth/claims_test.go
- pkg/auth/oidc.go
- pkg/auth/selfsigned.go
- pkg/auth/token_test.go
cherrypick of 6d68649313a2d9c853d816488abda9b475cf1bd6
> Add check for empty username during authentication

- api/server/sdk/cloud_backup.go
- api/server/sdk/cloud_backup_test.go
> Auth support for cloudbackup status and change-state apis. (#1026)

- api/server/docker.go
- api/spec/spec_handler.go
- api/spec/spec_handler_test.go
cherry-pick of b8afdb653ea71245671c9fefd4d2c1920e79cf79
> Fix token secret to be more flexible for full dcos secret path

- pkg/role/sdkserviceapi.go
- pkg/role/sdkserviceapi_test.go
If a value already exists in kvdb, the library will not return
the object, instead it will return nil.
> Role creation better handle of kvdb

- api/server/docker.go
- api/server/sdk/volume_node_ops.go
- api/server/sdk/volume_node_ops_test.go
- csi/node_test.go
- pkg/role/sdkserviceapi.go
- pkg/role/sdkserviceapi_test.go
> Cherry-pick from master

- api/server/volume.go
> Snap enum 6

- api/api.go
- api/server/sdk/errors.go
- api/server/sdk/volume.go
- api/server/sdk/volume_node_ops.go
- api/server/volume.go
- api/server/volume_test.go
**What this PR does / why we need it**: This fixes an issue where unmount was not handling volumes that are deleted.
> Fixes for handling unmounts on deleted volumes

- api/api.go
- api/server/sdk/errors.go
- api/server/sdk/volume.go
- api/server/sdk/volume_node_ops.go
- api/server/volume.go
- api/server/volume_test.go
* Fixes for handling unmounts on deleted volumes
* fix detach UT
* add comment to checkAccessForVolumeId function
* fix comment
Closes #
> [cherry-pick] Fixes for handling unmounts on deleted volumes (#1050)

- api/server/sdk/errors.go
- api/server/volume.go
Cherry-pick of #1052 
Closes #
> Do not hide errors in enumerate

- api/server/sdk/volume_node_ops.go
cherry-pick of vol not found mount mask issue
> Change mount permissions check to match attach

- api/server/volume.go
- api/server/volume_test.go
Need to increase the maximum buffer size when requesting data from thousands of volumes
> Increase buffer size to allow for many volumes

- api/server/middleware_auth.go
> if volume is not found, return correct sdk error

- api/server/middleware_auth.go
cherry-pick of 8d2af6bfc2b557a8d9f67e859a0b4dbb1dcd84d4
> release-6.0: in-tree: Get k8s secret from labels if not in PVC annotations

- api/server/sdk/rest_gateway.go
- api/server/sdk/sdk_test.go
- vendor/github.com/rs/cors/LICENSE
- vendor/github.com/rs/cors/README.md
- vendor/github.com/rs/cors/cors.go
- vendor/github.com/rs/cors/go.mod
- vendor/github.com/rs/cors/utils.go
- vendor/vendor.json
* Adds support for cors
Closes #567 
> Enable cors support for sdk rest server

- api/server/sdk/volume_ops.go
cherry-pick of 44ef36a27c512a5bab92e55273120a59d4a66cdb
> Check for ownership before volume create spec

- api/server/sdk/rest_gateway.go
- api/server/sdk/server.go
cherry-picks of 71b7f37f99c70e697aa31ca57fa8fb1404629329
and 93e40accd16fc21e15ec9f44f21b0f05af2011ac
> Release-7.0: Add SDK Server Extensions

- api/server/sdk/volume_migrate.go
- api/server/sdk/volume_migrate_test.go
> release-7.0: cloud migration ownership

- api/server/sdk/volume_migrate.go
- api/server/sdk/volume_migrate_test.go
> Check for ownership on migrate cancel and status

- csi/csi.go
- csi/csi_test.go
- csi/identity.go
- csi/identity_test.go
- csi/v0.3/csi.go
- csi/v0.3/csi_test.go
- csi/v0.3/identity.go
- csi/v0.3/identity_test.go
Cherry-pick of #1131 and #1109
> CSI Name Conformance

- cluster/cluster.go
- cluster/manager/manager.go
Name conflicted with other libraries
> Fix conflict of API name

- cluster/cluster.go
- cluster/manager/manager.go
> Support Pool and Node information

- cluster/cluster.go
- cluster/manager/manager.go
> Pool and disk information 

- api/server/sdk/cloud_backup.go
> Fix error interpretation for cloud-backup

- api/server/sdk/cloud_backup.go
> Fix error interpretation for cloud-backup (#1155)

- api/client/client_test.go
- api/client/request.go
Cherry-pick from master.
* Fix api client request body length 0
> Fix api client request body length 0 (#1154)

- pkg/options/options.go
Allows read-only mounts
Closes #
> New options constant for mount access

- pkg/options/options.go
> New options constant for mount access (#1166)

- volume/drivers/common/default_store_enumerator.go
The OpenStorage SDK only supports unique names for volumes due
to idempotency. Since names are unique to volumes, OpenStorage
default enumerator should support using names as identifiers
to volumes.
> Support volume name in default enumerator

- api/server/sdk/rest_gateway.go
- api/server/sdk/server.go
cherry-pick of 93e40accd16fc21e15ec9f44f21b0f05af2011ac
> Add support for REST server extensions

- api/server/sdk/server.go
cherry-pick of 71b7f37f99c70e697aa31ca57fa8fb1404629329
> Add support for SDK gRPC server extensions

- api/server/sdk/cluster_test.go
- api/server/sdk/sdk_test.go
- api/server/testutils_test.go
- csi/csi_test.go
- csi/csisanity_test.go
- csi/identity_test.go
Fixes issues with tests failing due to port conflicts
> Fix test port conflicts

- api/api.go
- api/server/docker.go
- api/server/middleware_auth.go
- api/server/server.go
- api/spec/spec_handler.go
- api/spec/spec_handler_test.go
- pkg/auth/secrets/secrets.go
- pkg/auth/secrets/secrets_test.go
cherry-pick of 47fae40a8483420325079797492d4cc1da219f1b
> Add Vault, KVDB, and Docker auth token_secret support

- api/server/sdk/volume_ops.go
This patch will add more error information during timeout errors
received during the creation of a volume.
> Add more information to timeout errors

- api/server/sdk/volume_ops.go
- api/server/sdk/volume_ops_test.go
- csi/controller_test.go
- pkg/util/wait.go
Cherry-pick of #1199
Cherry-pick of #1218
> SDK will now return a volume only if it is ready

- api/api.go
- csi/node.go
- csi/node_test.go
> CSI: Make Unmount idempotent by succeeding if already unmounted (#1222)

- csi/controller.go
- csi/controller_test.go
* Default to sharedv4 for shared volume creation
> CSI: Default to Sharedv4

- csi/controller.go
- csi/controller_test.go
> CSI: Default to Sharedv4 (#1227)

- csi/controller.go
- csi/controller_test.go
- csi/csi.go
- csi/csi_test.go
- csi/node.go
cherry-pick 63ac38a0dae3c3574c8c239a7cab5c5700acda04
> CSI: Add req.Secrets to SDK calls for volume encryption (#1226)

- api/server/backup.go
> API server to Propagate restore errors.

- api/server/backup.go
> Cloudbackup err rel7

- api/server/backup.go
Closes #
cherry-pick from master
> API server to Propagate restore errors. (#1244)

- api/server/sdk/volume_migrate.go
- api/server/sdk/volume_migrate_test.go
> Change volume migration to use Enumerate instead of Inspect (#1245)

- api/server/sdk/cloud_backup.go
Updates the error message for cloud backup group create when a user does not have access to a volume in a group.
Closes #1257
> Update cloud migrate group backup access denied message

- api/server/sdk/cloud_backup.go
Cherry pick of #1258 on release-7.0.
#1258: Update cloud migrate group backup access denied message
> Automated cherry pick of #1258: Update cloud migrate group backup access denied message

- hack/cherry_pick_pull.sh
* Automated cherry-picking to release branches!!
Source: https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh
> Add automated cherry-picking script from kubernetes/kubernetes

- Makefile
- SDK_CHANGELOG.md
- api/api.pb.go
- api/api.proto
- api/server/sdk/api/api.swagger.json
SDK Version needs to stay at 0.42.x
> Set SDK version to 0.42.18

- api/api.pb.go
- api/api.proto
- api/server/sdk/api/api.swagger.json
- api/server/sdk/volume_migrate.go
Make sure `CloudMigrateStatus` does not get nil `CloudMigrateStatusRequest`
Closes #
> Handle nil migratestatus request

- api/server/backup.go
Do not check for sdk errors for cloudBackup restores as they are not routed
through sdk.
Closes #
Incorrect error being returned for cloud back restores, preventing it from being idempotent for requests with same task id.
> Fix cloudback returning incorrect error

- SDK_CHANGELOG.md
- api/api.go
- api/api.pb.go
- api/api.proto
- api/server/sdk/api/api.swagger.json
> Fix Storage Pools and deprecate id

- api/server/backup.go
Do not check for sdk errors for cloudBackup restores as they are not routed
through sdk.
Closes #
> Fix cloudback returning incorrect error (#1269)

- api/server/sdk/volume_migrate.go
* driver.Enumerate, when given a list of volume Ids, will return
NotFound and an empty list if any volumes does exist. This was problematic, 
because we were building a list of which volumes the user has access to based on this response.
* If a volume ID did not exist during a cloud migration status call, this would cause all volume IDs to be perceived as access denied, resulting in an empty cloud migration status response.
Now, we just enumerate each volume and only include volumes which the user has access to.
> Fix cloud migration status auth filtering

- api/server/sdk/volume_migrate.go
Cherry pick of #1273 on release-6.1.
#1273: Fix cloud migration status auth filtering
> Automated cherry pick of #1273: Fix cloud migration status auth filtering

- csi/controller.go
Need CSI to create shared/sharedv4 volumes when using ReadOnlyMany access type
> Add support for ReadOnlyMany volume creation

- alert/alert_kvdb_test.go
- api/server/sdk/sdk_test.go
- api/server/sdk/volume_ops_test.go
- api/server/testutils_test.go
- cluster/manager/manager_test.go
- cmd/osd/main.go
- csi/csi_test.go
- csi/csisanity_test.go
- csi/v0.3/csi_test.go
- objectstore/fake.go
- pkg/dbg/log.go
- pkg/role/sdkserviceapi_test.go
- pkg/storagepolicy/sdkstorage_policy_ownership_test.go
- pkg/storagepolicy/sdkstoragepolicy_test.go
- schedpolicy/fake.go
- vendor/github.com/portworx/kvdb/Dockerfile.kvdb
- vendor/github.com/portworx/kvdb/common/common.go
- vendor/github.com/portworx/kvdb/consul/client.go
- vendor/github.com/portworx/kvdb/consul/kv_consul.go
- vendor/github.com/portworx/kvdb/etcd/common/common.go
- vendor/github.com/portworx/kvdb/etcd/v2/kv_etcd.go
- vendor/github.com/portworx/kvdb/etcd/v3/kv_etcd.go
- vendor/github.com/portworx/kvdb/kvdb.go
- vendor/vendor.json
- volume/drivers/common/default_store_enumerator_test.go
- volume/drivers/fake/fake.go
- volume/drivers/fake/fake_test.go
- volume/drivers/test/driver.go
* update kvdb package.
- use the default handler to error out.
* Add new function for panic
- LogErrorAndPanicf will log error and panic
Closes #
> update kvdb package. (#1305)

- api/api.go
> All check pool uuids in the volume Contains method

- api/server/creds.go
- api/util.go
- api/util_test.go
> Convert cred handlers to use SDK calls

- api/errors/errors.go
> Pretty print the error ErrStoragePoolResizeInProgress.

- cluster/manager/pair.go
> set pair token

- cluster/manager/pair.go
> set the pair token by default (#1345)

- cluster/manager/manager.go
watch errors:
1. if this node is in decommissioned state, do nothing
2. on error, try getting data directly from kvdb.
- if error, give up and try restarting the watch.
- if no error, continue.
Closes #
> handle watch errors.

- cluster/manager/manager.go
handle watch errors. (#1347)
1. if this node is in decommissioned state, do nothing
2. on error, try getting data directly from kvdb.
- if error, give up and try restarting the watch.
- if no error, continue.
Closes #
> Automated cherry pick of #1347 upstream release 7.0

- api/api.pb.go
- api/api.proto
- api/server/sdk/api/api.swagger.json
Bump version in api.proto as it was missed in a few commits
> Bump patch version 0.42.24

- api/api.pb.go
- api/api.proto
- api/server/sdk/api/api.swagger.json
Bump version in api.proto as it was missed in a few commits
> Bump patch version 0.42.24 

- Makefile
> Freeze 0.69.0 of the SDK

- api/server/sdk/server.go
- api/server/sdk/server_interceptors.go
- api/server/sdk/server_interceptors_test.go
- api/server/testutils_test.go
- cmd/osd/main.go
- pkg/role/sdkserviceapi.go
- pkg/role/sdkserviceapi_test.go
- vendor/github.com/hashicorp/go-multierror/go.mod
> Update public user to use RBAC negation for volume creation

- csi/node.go
- csi/node_test.go
Cherry pick of #1379 on release-6.3.
#1379: Remove CSI NodeUnpublish lstat
> Automated cherry pick of #1379: Remove CSI NodeUnpublish lstat

- api/server/sdk/server.go
- api/server/sdk/server_interceptors.go
- api/server/sdk/server_interceptors_test.go
- api/server/testutils_test.go
- cmd/osd/main.go
- pkg/role/sdkserviceapi.go
- pkg/role/sdkserviceapi_test.go
- vendor/github.com/hashicorp/go-multierror/go.mod
> Update public user to use RBAC negation for volume creation (#1382)

- cmd/osd/main.go
- hack/kind.yaml
- hack/osd-csi.yaml
- hack/setup-kind-csi-cluster.sh
> Add script to start OSD CSI Driver in kind

- cmd/osd/main.go
- hack/osd-csi.yaml
- hack/setup-kind-csi-cluster.sh
> Change setup CSI OSD cluster to use DaemonSet instead of binary

- hack/osd-csi.yaml
> Revert removal of csi-driver-path volume mount

- api/client/request.go
* Fix the retry logic of our api client.
Currently it's possible for the Do() call to receive a 503 status
without a retry-after header.
This results in calls looping every second for 5 minutes.
Fixed this with a check for the header and a boolean check.
> Fix the retry logic of our api client. (#1424)

- api/api.go
> Restore labels rel8

- api/api.go
Closes #
cherry-pick from master
> New label to support source volume based provision (#1423)

- .travis.yml
Signed-off-by: stgleb <glebstepanov1992@gmail.com>
> Run gofmt against latest version of go

- api/api.go
> Cloudbackup label option for ignoring credentials (#1454)

- vendor/gopkg.in/freddierice/go-losetup.v1/LICENSE
- vendor/gopkg.in/freddierice/go-losetup.v1/README.md
- vendor/gopkg.in/freddierice/go-losetup.v1/constants.go
- vendor/gopkg.in/freddierice/go-losetup.v1/device.go
- vendor/gopkg.in/freddierice/go-losetup.v1/format.go
- vendor/gopkg.in/freddierice/go-losetup.v1/info.go
- vendor/gopkg.in/freddierice/go-losetup.v1/losetup.go
- vendor/vendor.json
- volume/drivers/nfs/nfs.go
- volume/drivers/nfs/nfs_test.go
- volume/drivers/test/driver.go
For CSI Raw block testing
Volume Creation:
Will attach to the NFS host, then create a file of the requested
size on the NFS share. It will then use losetup to mount the file
and format it according to the format in the request. If not format
was requested, then it will be left as RAW.
Snapshots are done by copying the file.
> NFS Raw block support

- csi/controller.go
> Add support for VolumeSnapshot beta restore 

- api/server/cluster.go
Signed-off-by: stgleb <glebstepanov1992@gmail.com>
> unsecure nodehealth endpoint

- api/server/sdk/server_interceptors.go
- api/server/sdk/server_interceptors_test.go
> Remove confusing error message for unauthenticated API calls

- alert/alert_kvdb.go
when kvdb becomes unavailable, a new wrapper is added to it.
query kvdb instance instead of saving it.
Closes #
> do not store kvdb instance (#1482)

- api/api.go
- api/spec/spec_handler.go
- api/spec/spec_handler_test.go
Signed-off-by: prabir <prabir@portworx.com>
Need for supporting cow_ondemand xattr in volume spec
Closes #
> Spec handler changes for supporting new cow_ondemand xattr

- api/api.go
- api/spec/spec_handler.go
- api/spec/spec_handler_test.go
Signed-off-by: prabir <prabir@portworx.com>
Closes #
> Spec handler changes for supporting new cow_ondemand xattr (#1501)

- api/server/docker.go
- hack/docker-integration-test.sh
> [docker] Add support for mount via volume ID

- csi/controller.go
- csi/controller_test.go
> Revert "Automated cherry pick of #1513: Fix FsType resolution to use PX FsType by default"

- pkg/grpcserver/grpcutil.go
- volume/drivers/pwx/connection.go
- volume/drivers/pwx/connection_test.go
To have functions which can produce dial options and endpoints.
Closes #
> TLS configuration for Px REST MGMT and SDK/iSDK endpoints

- pkg/grpcserver/grpcutil.go
- volume/drivers/pwx/connection.go
- volume/drivers/pwx/connection_test.go
> Endpoint and dial ops funcs were added.

- pkg/mount/mount.go
- pkg/mount/nfs.go
> Add trace logs to generic mounter load function

- api/server/middleware_auth.go
Signed-off-by: stgleb <glebstepanov1992@gmail.com>
Closes #
PWX-12646
> PWX-12646 Fix error message for empty token error

- api/server/middleware_auth.go
> PWX-12646 Cherry pick to 7.0

- api/server/middleware_auth.go
- api/server/middleware_auth_test.go
- pkg/auth/secrets/secrets.go
Needed to clean up the way some of the code was checking for authenticators
> Cleanup auth checks

- pkg/mount/mount.go
Signed-off-by: adikulkarni0 <adi.kulkarni@portworx.com>
Closes # PWX-11542
> PWX-11542 : Change the already mounted warning message to info (#1528)

- volume/drivers/pwx/connection.go
- volume/drivers/pwx/connection_test.go
Updates to let a user manually set Portworx endpoint, SDK and rest APIs ports
Closes #
> envs to set porx endpoint and ports with no dynamic configuration

- volume/drivers/pwx/connection.go
- volume/drivers/pwx/connection_test.go
(cherry picked from commit 7f13a33bc18735ec4f596b2957fc5d530eedb7a1)
Closes #
> Envs to overwrite dynamic tls configuration

- volume/drivers/pwx/connection.go
- volume/drivers/pwx/connection_test.go
(cherry picked from commit 7f13a33bc18735ec4f596b2957fc5d530eedb7a1)
Closes #
> PWX-11764 envs to set porx endpoint and ports with no dynamic configration

- pkg/mount/bind_mount.go
- pkg/mount/custom_mount.go
- pkg/mount/device.go
- pkg/mount/mount.go
- pkg/mount/nfs.go
> add trace cache for pkg/mount

- pkg/mount/mount.go
- pkg/mount/nfs.go
> Only log trace cache when source is not in nfs mount table

- api/server/volume.go
Signed-off-by: adikulkarni0 <adi.kulkarni@portworx.com>
Closes # PWX-10619
> PWX-10619: Fail ha-update when volume is not found (#1582)

- pkg/mount/bind_mount.go
- pkg/mount/consistent_read.go
- pkg/mount/device.go
- pkg/mount/mount.go
- pkg/mount/nfs.go
> Add fix for consistent mount table read

- pkg/mount/bind_mount.go
- pkg/mount/custom_mount.go
- pkg/mount/device.go
- pkg/mount/mount.go
- pkg/mount/nfs.go
Cherry pick of #1603 on release-7.0.
#1603: pkg/mount: Remove trace cache
> Automated cherry pick of #1603: pkg/mount: Remove trace cache

- cluster/manager/pair.go
- pkg/grpcserver/creds_injector.go
- pkg/grpcserver/creds_injector_test.go
- volume/drivers/pwx/connection.go
PWX-13521 ClusterPair should respect authorization
STOR-203, gRPC interceptor for injecting authZ token
Closes #
> gRPC interceptor for injecting authZ token and making clusterPair calls to use authorization token 

- api/api.go
- api/server/sdk/server.go
- api/server/sdk/server_interceptors.go
- api/server/sdk/volume.go
- api/server/sdk/volume_node_ops.go
- api/server/sdk/volume_ops.go
- pkg/grpcserver/grpcutil.go
- pkg/role/sdkserviceapi.go
This patch adds support for the following audits:
* log when unathenticated
* log volume id for attach, detach, mount, unmount, created,
delete, and update
> More audit log support

- cluster/manager/pair.go
- pkg/grpcserver/creds_injector.go
- pkg/grpcserver/creds_injector_test.go
- volume/drivers/pwx/connection.go
> gRPC auth token interceptor

- .travis.yml
- SDK_CHANGELOG.md
- api/api.pb.go
- api/api.proto
- api/server/sdk/api/api.swagger.json
- hack/check-api-version.sh
Add SDK Version check to travis
> Add SDK Version check to travis

- SDK_CHANGELOG.md
- api/api.pb.go
- api/api.proto
- api/server/sdk/api/api.swagger.json
Signed-off-by: Prashanth Kumar <prashanth.kumar@portworx.com>
Bumping the SDK version in changelog
Closes #
> Updated SDK version in changelog

- pkg/mount/nfs.go
> Remove LogDevices in pkg/mount

- api/ownership.go
- api/ownership_test.go
- pkg/auth/userinfo.go
> Fix system.guest user to not have access to all groups

- api/ownership.go
- api/ownership_test.go
- pkg/auth/userinfo.go
Cherry pick of #1623 on release-8.0.
#1623: Fix system.guest user to not have access to all groups
> Automated cherry pick of #1623: Fix system.guest user to not have access to all groups

- SDK_CHANGELOG.md
- api/api.pb.go
- api/api.proto
- api/server/sdk/api/api.swagger.json
Bumping the SDK version in changelog
Closes #
> Added fetching backup size of volume backup

- hack/cherry_pick_pull.sh
> update cherry-pick script to fetch all remotes

- hack/check-api-version.sh
> Fix travis for release-7.0

- hack/check-api-version.sh
> Fix misspelled word

- api/server/sdk/server_interceptors.go
> Fix error missing optional arg list

- api/server/sdk/server_interceptors.go
> Fix auth audit log syntax

- hack/cherry_pick_pull.sh
Tested PR example here:
https://github.com/libopenstorage/openstorage/pull/1675
> Cherry pick script: Change name of autogenerated branch to remove #

- pkg/auth/oidc.go
- vendor/github.com/coreos/go-oidc/oidc.go
- vendor/github.com/coreos/go-oidc/verify.go
- vendor/vendor.json
> Skip issuer check (Cherry-pick for release-8.0)

- api/server/volume.go
- api/server/volume_test.go
The Kubernetes Portworx intree driver has a bug when it tries to check if the server is up and running. It sends a request to this server to get a version, but instead of using the correct API, it sends a request to get information about a volume called "version". Since the intree driver is _not_ sending a authenticated call for this check, it will be denied as an unathorized request. We will need to return a 200 HTTP request as if the volume was not found.
> Enable K8S Porx Intree driver to work with auth

- api/server/middleware_auth.go
- pkg/auth/secrets/secrets.go
> Check for nil when accessing secret instance

- api/server/middleware_auth.go
- pkg/auth/secrets/secrets.go
> Check for nil in secrets instance

- api/spec/spec_handler.go
> Set io profile as auto in default spec.

- api/server/sdk/volume_ops.go
> Correctly set xattr value

- api/server/sdk/server.go
- api/server/sdk/server_interceptors.go
- api/server/sdk/server_interceptors_test.go
Adds stream interceptors
Closes #
> Add stream interceptors for auth, logging, and rwLock

- api/client/volume/client.go
- api/server/creds.go
> Allow credential names/uuids with '/'

- api/client/volume/client.go
- api/server/creds.go
* Allow credential names with '/'
* Fix go fmt.
Closes #
> Allow credential names/uuids with '/' (#1744)

- api/server/middleware_k8s.go
- api/server/middleware_k8s_test.go
- api/server/volume.go
> Handle Set requests from CO in auth middleware.

- api/server/middleware_auth.go
- api/server/middleware_auth_test.go
- api/server/volume.go
Reverting `Handle Set requests from CO in auth middleware. (#1742)`
> Reverting Handle Set requests from CO in auth middleware

- api/server/middleware_auth.go
- api/server/testutils_test.go
- api/server/volume_test.go
- cluster/mock/cluster.mock.go
> Need to update middleware to work with Guest Roles

- csi/node.go
> [CSI] Add path to unmount log line

- cluster/manager/manager.go
- pkg/sched/sched.go
to prevent ticker overwrite
Signed-off-by: sangleganesh <ganesh@portworx.com>
Closes #
> set start flag in Start

- docs/dev-sdk.md
Update SDK Development documentation
> Update SDK Development Doc

- .travis.yml
> Update Travis to Go 1.14 and 1.15

- api/client/client.go
Going to use the api/client package as a http client wrapper but my use case requires the PATCH method. This change adds the Patch method to the REST client.
> Add Patch method to the REST client

- cluster/manager/manager.go
- cluster/manager/manager_test.go
Signed-off-by: Serhii Aheienko <serhii.aheienko@gmail.com>
Closes #
> cluster/manager: replace logrus.Printf with dbg.LogErrorAndPanicf

- volume/drivers/pwx/connection.go
Use the same env variable already used by stork to keep it consistent.
Closes #
> change the env variable for token issuer to match the one used by stork

- api/client/client.go
- api/client/cluster/cluster.go
- cluster/manager/pair.go
> [cherry-pick] Support cluster pairing over https endpoint

- api/server/middleware_auth.go
- api/server/testutils_test.go
- api/server/volume_test.go
- cluster/manager/manager.go
> Auth-middleware delete is not idempotent

- Dockerfile.osd
- hack/docker-integration-test.sh
> Remove docker images to avoid rate limited docker pull (#1830)

- .github/labeler.yml
- .github/workflows/cron-stale.yml
- .github/workflows/on-pr.yml
- .github/workflows/on-review-requsted.yml
> Add github actions for PR metadata 

- .github/CODEOWENRS
- .github/workflows/cron-stale.yml
- .github/workflows/on-pr.yml
> Add codeowners, sync area labels on PR update, mark stale PRs

- csi/csi.go
> Remove test line and test codeowners

- csi/controller.go
- csi/node.go
> [CSI] Don't log entire request and cleanup logs

- csi/controller.go
- csi/node.go
Waiting until next release for this.
> Revert "Automated cherry pick of #1841: Don't log entire request and cleanup logs"

- .travis.yml
> Change travis email notification to control plane team

- api/spec/spec_handler.go
- api/spec/spec_handler_test.go
Signed-off-by: Harsh Desai <hadesai@purestorage.com>
Closes #
> [cherry-pick] PWX-19496 Default to cow_on_demand for new volumes (#1856)

- .gitignore
- csi/controller.go
- csi/controller_test.go
- csi/node.go
- csi/node_test.go
- hack/csi-sanity-test.sh
- pkg/mount/mount.go
- pkg/mount/mount_test.go
- pkg/mount/raw_mount.go
- volume/drivers/fake/fake.go
> [CSI] Raw Block support

- csi/controller.go
- csi/controller_test.go
Cherry pick of #1870 on release-9.1.
#1870: Round volume size up to nearest GiB
> Automated cherry pick of #1870: Round volume size up to nearest GiB

- api/errors/errors.go
- api/server/sdk/cloud_backup.go
- api/server/sdk/cloud_backup_test.go
Indicate when to retry with ResourceBusy error codes.
Closes #
> New error codes for cloudBackup APIs

- api/errors/errors.go
- api/server/sdk/cloud_backup.go
- api/server/sdk/cloud_backup_test.go
> Add cloudbackup specific busy error code

- Dockerfile.osd-dev
- Dockerfile.osd-dev-base
- Makefile
- api/client/request.go
- api/server/backup.go
- api/server/migrate.go
- api/server/sdk/sdk_test.go
- api/server/volume.go
- api/server/volume_test.go
- csi/controller.go
- csi/node.go
- pkg/auth/oidc.go
- pkg/defaultcontext/default.go
- pkg/defaultcontext/default_test.go
- pkg/grpcserver/grpcutil.go
- pkg/grpcutil/context.go
- pkg/grpcutil/context_test.go
> Add timeouts to all RPCs

- csi/controller.go
Fixes the volume snapshot restore size to be non-zero
Closes #
> [CSI] Fix Volume Snapshot restore size

- csi/controller.go
- csi/controller_test.go
Implements CSI snapshot list. Mainly for Nomad CSI, but will be called for K8s CSI as well.
Closes #
> [CSI] ListSnapshots implementation

- csi/controller.go
- csi/controller_test.go
Cherry pick of #1888 on release-9.1.
#1888: ListSnapshots implementation
> Automated cherry pick of #1888: ListSnapshots implementation

- cluster/manager/manager.go
updateClusterStatus() function had dual purpose. It would update the node cache with the new info
received from gossip and it would also notify the listeners of any changes in the node status. If
one of the listeners took long time to process the change notification, node cache updates stopped.
This patch refactors node-cache updates and listener notifications into separate goroutines
so that one does not block the other.
PWX-15391
Cherry-pick from master to 9.1 release branch.
> PWX-15391: separate out node cache update

- csi/controller.go
Useful for nomad and other CSI schedulers
Closes #
> [CSI] Skip adding empty PVC name/namespace

- api/errors/errors.go
- api/server/sdk/cloud_backup.go
- api/server/sdk/cloud_backup_test.go
> Add cloudbackup specific busy error code (#1876)

- api/server/sdk/volume_ops.go
fix volume ready status
Signed-off-by: Paul Theunis <ptheunis@purestorage.com>
Co-authored-by: Paul Theunis <ptheunis@purestorage.com>
> Cherry-pick from master 

- SDK_CHANGELOG.md
Signed-off-by: Aditya Kulkarni <akulkarni@purestorage.com>
Closes #
> Fix typos in CHANGELOG

- api/server/volume.go
> PWX-20657: Automated cherry pick of 1903 release 9.1

- csi/controller.go
- csi/node.go
> Change CSI driver logs from Debugf to Infof

- pkg/options/options.go
Add an option to indicate if a Detach was issued as a part of Delete
Closes #
> Add an option to indicate if a Detach was issued as a part of Delete

- api/spec/spec_handler.go
add extra check for external access flag 
Signed-off-by: Jim Ou <jqou@purestorage.com>
> fixup! [PWX-20437] Add a flag in Sharedv4ServiceSpec

- csi/csi_test.go
- pkg/auth/auth.go
- pkg/correlation/README.md
- pkg/correlation/context.go
- pkg/correlation/correlation_test.go
- pkg/correlation/hook.go
- pkg/correlation/interceptor.go
> Correlation context pkg feedback

- api/client/volume/client.go
- api/flexvolume/flexvolume.go
- api/server/docker.go
- api/server/middleware_auth.go
- api/server/sdk/volume_node_ops.go
- api/server/sdk/volume_node_ops_test.go
- api/server/volume_test.go
- cli/volumes.go
- csi/controller.go
- csi/csi.go
- csi/node.go
- csi/node_test.go
- csi/v0.3/node.go
- csi/v0.3/node_test.go
- graph/drivers/layer0/layer0.go
- pkg/correlation/context.go
- pkg/correlation/correlation_test.go
- pkg/correlation/hook.go
- pkg/correlation/interceptor.go
- pkg/sanity/backup_restore.go
- pkg/sanity/volume.go
- volume/drivers/buse/buse.go
- volume/drivers/fake/fake.go
- volume/drivers/fuse/volume_driver.go
- volume/drivers/mock/driver.mock.go
- volume/drivers/nfs/nfs.go
- volume/drivers/test/driver.go
- volume/drivers/vfs/vfs.go
- volume/volume.go
- volume/volume_not_supported.go
> Add correlation context to attach/detach/mountedAt

- pkg/correlation/hook.go
> Remove error when we can't get correlation context

- .travis.yml
> Update .travis.yml to go 1.16 and 1.17

- Makefile
auto generate mocks for volume/drivers
otherwise, need to manually `go generate` in `volume/drivers` folder.
Closes #
> PWX-22038 auto generate volume/drivers/mock/

- api/api.go
> Add helper function to get all proto enum info

- .travis.yml
- Makefile
- hack/csi-sanity-test.sh
- hack/docker-integration-test.sh
> Add PR makefile targets and parallelize travis

- csi/identity.go
- csi/identity_test.go
- csi/node.go
Signed-off-by: Piyush Nimbalkar <pnimbalkar@purestorage.com>
Closes #
> Add CSI capability to support topology

- Makefile
> Always pull docker-proto image before running

- Makefile
> Switch to manual pull as --pull flag requires new docker

- .travis.yml
- Dockerfile.proto
- Makefile
- hack/csi-sanity-test.sh
- hack/docker-integration-test.sh
> Fix packr failures and update makefile/travis

- api/server/sdk/server_interceptors.go
- csi/controller.go
- csi/controller_test.go
> Release 9.3 CSI & Correlation tracing fix

- api/api.go
- cluster/manager/pair.go
> [cp] pass remote cred uuid while calling refresh cluster pair

- api/server/volume.go
The OSD Client in Kubernetes Portworx in-tree driver is out of date
and uses non-pointer booleans in the VolumeSpec. This code is locked and cannot be updated.
volumeSet is only used with K8s in-tree resizing and will have a
false boolean flag for all unset spec values. As a result, real values
such as autofstrim/proxy_write are being reset during K8s resize operations.
We must only update the size in this case to preserve other spec values.
Closes #
> Only update size for k8s set requests

- csi/controller.go
- csi/controller_test.go
There appear to be some cases where resizer things a resize is needed, so a request comes into PX to resize. However, since no change is needed, we return an error in the proto driver. This fixes these cases at the CSI level.
Closes #
> [CSI] Add extra idempotency check for resizing

- .github/CODEOWNERS
> Update CODEOWNERS for ggriffiths

- Makefile
> Use quay.io/openstorage/osd-proto:pre-gomodules for docker-proto

- pkg/mount/mount.go
> Fix error mask in pkg/mount Mount call (#2017)

- api/server/sdk/server_interceptors.go
Closes #
Example test
```
@grant-k8s-1-node2 portworx[9633]: time="2022-04-07T01:05:24Z" level=info msg=Authorized correlation-id=bc086d3a-b4e7-43e3-b9fa-1884774275ce email=operator@apps.portworx.io groups="[*]" method=node.enumeratewithfilters name=operator origin=sdk-server roles="[system.admin]" subject=operator@apps.portworx.io username=operator@apps.portworx.io
@grant-k8s-1-node2 portworx[9633]: time="2022-04-07T01:05:24Z" level=info msg=Authorized correlation-id=292ef8fc-a36b-4593-ba2d-d24852628a4a email=operator@apps.portworx.io groups="[*]" method=role.inspect name=operator origin=sdk-server …
```
> [correlation] Add correlation context to audit logs

- api/server/volume.go
Fixes an issue where we parsing the correlation context http headers and directly adding to an outgoing gRPC context. This was incorrect. We should have instead adding a RequestContext object to the current context.
Test data attached below
Closes #
Note the presence of correlation id `f7e208d7-761c-4a12-9b24-f5241f5ebbee` on both nodes below:
Source node:
```
grant@ip-70-0-0-129:~$ kn logs px-cluster-72d387a1-6e69-46e8-8799-7e9b08ee8fe1-mnnk9 -c portworx | grep -v "GGCOR" |grep f7e208d7-761c-4a12-9b24-f5241f5ebbee
@grant-k8s-1-node0 portworx[25426]: time="2022-04-06T00:05:51Z" level=info msg="csi.NodeUnpublishVolume …
```
> [Correlation] Fix 9001 server parsing remote correlation context

- hack/cherry_pick_pull.sh
> Update cherry_pick_pull.sh to always use libopenstorage/openstorage

- api/server/sdk/server_interceptors.go
Cherry pick of #2025 on release-9.4.
#2025: Add correlation to audit logs
> Automated cherry pick of #2025: Add correlation to audit logs

- api/server/volume.go
Cherry pick of #2024 on release-9.4.
#2024: Fix 9001 server parsing remote correlation
> Automated cherry pick of #2024: Fix 9001 server parsing remote correlation

- api/server/sdk/server_interceptors.go
Removes invalid token from the audit logs
n/a
n/a
> [Auth] Remove failed token and role from audit logs

- csi/csi.go
> Update server name to CSI 1.6 to match vendor version

- csi/controller.go
> Add CSI standard pvc name/namespace

- Makefile
- api/mock/mock_cluster.go
- api/mock/mock_diags.go
- api/mock/mock_fscheck.go
- api/mock/mock_fstrim.go
- api/mock/mock_node.go
- api/mock/mock_storagepool.go
- api/mock/mock_volume.go
- api/server/mock/mock_schedops_k8s.go
- cluster/mock/cluster.mock.go
- volume/drivers/mock/driver.mock.go
> Fix mockgen to an older tag for release-9.4 docker-proto

- cluster/manager/database.go
Signed-off-by: Naveen Revanna <nrevanna@purestorage.com>
Closes #
> PWX-22045: Scale bringup - increasing timeout for clustermap lock

- Makefile
- api/swagger/swagger.json
> Update makefile targets to install dependencies w/ new Go versions

- api/status.go
Signed-off-by: Lakshmi Narasimhan Sundararajan <lns@portworx.com>
cherry picked changes from master
https://github.com/libopenstorage/openstorage/pull/2052
Closes #
https://portworx.atlassian.net/browse/PWX-23690
> PWX-23690: missed pool maintenance severity

- csi/controller.go
- csi/controller_test.go
- csi/csi.go
- csi/csi_test.go
Add CSI VolumeCreate round-robbin
Closes #
> Add CSI VolumeCreate node round-robin

- api/server/sdk/server.go
- cmd/osd/main.go
- csi/controller.go
- csi/csi.go
- csi/csi_test.go
Fixes a few issues in the original PR and adds a MaxConnectionAge to the SDK gRPC server
Closes #
> [CSI] Add remote conn fixes for provisioning

- cmd/osd/main.go
- csi/controller.go
- csi/controller_test.go
- csi/csi.go
- csi/csi_test.go
> [CSI] Add CSI VolumeCreate node round-robin 

- bucket/drivers/s3/s3.go
Signed-off-by: Priyanshu Pandey <ppandey@purestorage.com>
Handle user account deletion when bucket access is revoked
Closes #PWX-24287
1. Bucket Policy name has been moved inside a function.
2. getAccountAccessKey call should be independent of bucket. It is specific to a user and should be only called once irrespective of the bucket name. This call has been removed and accountName is used directly as the key in the map.
3. During GrantBucketAccess, returning cached access key for the user should happen after grantAccessToBucket to update the access policy for the new bucket.   A user might already exist and a bucket access request comes for a new bucket. Bucket policy …
> PWX-24287: Handle user account deletion when bucket access is revoked

- bucket/drivers/fake/fake.go
> Fix CreateBucket and DeleteBucket errorAlreadyExists code check

- api/server/sdk/credentials_test.go
- api/server/sdk/sdk_test.go
- api/server/sdk/server.go
- api/server/sdk/volume_ops_test.go
- bucket/drivers/fake/fake.go
- cmd/osd/main.go
> Add support for multiple bucket drivers

- bucket/drivers/purefb/purefb.go
> [BucketDriver] Add Pure FB String function

- bucket/drivers/purefb/purefb.go
> [BucketDriver] Add admin account as AccountID

- .github/workflows/on-pr-merged.yml
Add action to cherry-pick to release-9.5
Closes #
> Add action to cherry-pick to release-9.5

- api/server/sdk/bucket_ops.go
- api/server/sdk/bucket_ops_test.go
Cherry pick of #2096 on release-9.5.
#2096: PWX-26155: Setting default region for purefb in case of
> Automated cherry pick of #2096: PWX-26155: Setting default region for purefb in case of

- cluster/manager/manager.go
Cherry-pick PR for release-9.1
Original change description
```
We were deep-copying the api.Node struct for the self node but not for the
peer node. Moreover, the peer node struct is a shallow copy of the one
inside the gossip store. Any modifications to this struct can trigger "concurrent
map read and map write" panic when gossip is trying to send this struct out.
This interim fix avoids the issue by returning a deep copy of the peer
api node struct. There is still more work left to ensure that the gossip
store does not return a shallow copy of its api.Node struct.
```
Closes #
> PWX-21380: return a deep copy of the peer api.Node to the caller

- pkg/sched/sched.go
Also, don't print the histogram when there are no samples.
PWX-26709
> PWX-26709: don't print 0 valued buckets in sched stats

- api/api.go
> Adds a missing method that slipped into Porx directly

- .travis.yml
> Fix release-9.5 travis failures

- .github/dependabot.yml
Adds dependabot to Openstorage. This bot will send weekly PRs to update various dependencies. 
Closes #
> Add dependabot action to stay up to date on dependencies

- cluster/manager/manager.go
- When a node is joining a cluster check if it is decommissioned.
- There exists a race condition where a peer node could be decommissioning a node which was offline but it is now trying to come up. The peer node will update the clusterDB, but the node getting decommissioned overwrite it back as a part of the join cluster routine.
Closes #
> PWX-27408: Do not join the cluster back if the node is decommissioned.

- .github/workflows/on-pr-merged.yml
> Add new release branches to GitHub cherry-pick action

- volume/drivers/pwx/connection.go
* moved K8s CA addition into `appendK8sCaCertBytes()`
* calling it from both `BuildTlsConfig()` and `BuildDialOps()`
Signed-off-by: Zoran Rajic <zrajic@purestorage.com>
* making the addition of the Kubernetes CA more generic, so it can be called from multiple methods
* will call `appendK8sCaCertBytes()` for both -- 
- `BuildDialOps()`  (client for portworx-api:9020) as well as
- `BuildTlsConfig()` (client for portworx-api:9023) 
Closes #
- PWX-26915 (part 1 - reworked), also
- PWX-28189 (stork auto-SSL support)
> PWX-26915-pt1.r2/PWX-28189: Auto-TLS support r2 (#2159)

- pkg/mount/raw_mount.go
[CSI] Fix CSI raw block mounter RegExp to find mount root
Closes #
> [CSI] Fix CSI raw block mounter RegExp to find mount root

- csi/sched/interceptor.go
> [csi/sched] PWX-29171: Fix error formatting to use error received

- csi/controller.go
- csi/controller_test.go
Reverts libopenstorage/openstorage#2213, accidental merge
> Revert "CSI: Cleanup failed snapshot and re-create on next retry"

- api/server/sdk/volume_ops.go
- api/server/sdk/volume_ops_test.go
- api/server/sdk/volume_snapshot_test.go
- csi/controller.go
- csi/controller_test.go
- volume/drivers/fake/fake.go
cherry picked changes from master.
https://github.com/libopenstorage/openstorage/pull/2228
Closes # https://portworx.atlassian.net/browse/PWX-23290
> PWX-23290: handle spec updates with stale config

- api/server/sdk/cloud_backup.go
add near sync pause/resume for testing
Closes #
> PWX-29467 near sync pause/resume

- csi/sched/interceptor.go
Warnf on CSI sched filter fail instead of erroring out
Closes #
> PWX-29572: Warnf on CSI sched filter fail instead of erroring out

- csi/sched/interceptor.go
> PWX-29572: Skip CSI sched filter for non-k8s clients

- cluster/manager/database.go
- cluster/manager/manager.go
- go.mod
- go.sum
- vendor/github.com/portworx/kvdb/.travis.yml
- vendor/github.com/portworx/kvdb/DCO
- vendor/github.com/portworx/kvdb/LICENSE
- vendor/github.com/portworx/kvdb/README.md
- vendor/github.com/portworx/kvdb/common/common.go
- vendor/github.com/portworx/kvdb/consul/client.go
- vendor/github.com/portworx/kvdb/consul/kv_consul.go
- vendor/github.com/portworx/kvdb/etcd/common/common.go
- vendor/github.com/portworx/kvdb/etcd/v2/kv_etcd.go
- vendor/github.com/portworx/kvdb/kvdb.go
- vendor/github.com/portworx/kvdb/mem/kv_mem.go
- vendor/github.com/portworx/kvdb/updates_collector.go
- vendor/modules.txt
> PWX-28882: Vendoring and updating kvdb

- pkg/keylock/keylock.go
Implemented TryLock to acquire the per-volume keylock
Now we return error if we cannot acquire the keyLock in 30 seconds
Closes #
> Pwx 21105 implement Trylock to acquire the per-volume keylock

- pkg/keylock/keylock.go
* Implement trylock - don't keep waiting for the per-volume keyLock forever
Signed-off-by: Dolly Talreja <dtalreja@purestorage.com>
Closes #
> Cherry-pick into 9.6 : Pwx 21105 -  implement Trylock to acquire the per-volume keylock

- pkg/keylock/keylock.go
Now we return error if we cannot acquire the keyLock in 30 seconds
Closes #
PWX-21105
> Return error code if failed to acquire lock

- pkg/keylock/keylock.go
Cherrypick
Now we return error if we cannot acquire the keyLock in 30 seconds
Closes #
PWX-21105
> Return error code if failed to acquire lock (#2279)

- api/server/testutils_test.go
pkg imported more than once
Closes #
> chore: pkg imported more than once

- pkg/keylock/keylock_test.go
Added Unit test cases for PR 21105
PWX-31857
NA
> Add unit test cases for Acquire with timeout

- pkg/keylock/keylock.go
- pkg/keylock/keylock_test.go
Cherrypick
Now we return error if we cannot acquire the keyLock in 30 seconds.
Added UTs for aquireWithTimeout
Closes #
PWX-21105
> Cherrypick pwx 21105 9.7

- pkg/keylock/keylock.go
- pkg/keylock/keylock_test.go
Cherrypick to release9.8
Now we return error if we cannot acquire the keyLock in 30 seconds.
Added UTs for aquireWithTimeout
Closes #
PWX-21105
> Cherrypick TryLock feature PWX-21105 to release9.8

- api/server/sdk/sdk_test.go
> fix watcher test

- Makefile
- api/server/sdk/rest_gateway.go
- hack/check-registered-rest.sh
* Add missing REST handlers to openstorage SDK server 
* Adds a linter
Closes #
> PWX-32459: Add missing REST handlers to openstorage SDK server

- Makefile
- api/server/sdk/rest_gateway.go
- hack/check-registered-rest.sh
Cherry-pick 2753450f78d2b2357acd999261c9cf9b06c45b98
Closes #
> Add missing REST handlers to openstorage SDK server

- api/server/sdk/filesystem_trim.go
Signed-off-by: Chia-Chun Lin <chialin@purestorage.com>
(cherry picked from commit 8b9217492993887d4dcdbfb340d2ef21bbf8f8cf)
Closes #
> PWX-31645 remove required path arg for fstrim (#2274)

- csi/controller.go
Fix to block the rawblock request for FBDA.
Closes #PWX-23536
> PWX-23536: fix to block the rawblock request for FBDA.

- csi/controller.go
Fix to block the rawblock request for FBDA & enable for FADA
Closes #PWX-23536
> PWX-23536: fix to block the rawblock request for FBDA & enable for FADA

- SDK_CHANGELOG.md
- api/api.pb.go
- api/api.proto
- api/server/sdk/api/api.swagger.json
> Add auto-journal IO profile

- api/server/sdk/credentials.go
> Fix cred inspect nil on empty map

- api/server/sdk/credentials.go
> Fix cred inspect nil on empty map (#2312)

- api/client/volume/client.go
- api/server/sdk/sdk_test.go
- api/server/sdk/server.go
- api/server/sdk/watcher.go
- csi/csi_test.go
- volume/drivers/buse/buse.go
- volume/drivers/fake/fake.go
- volume/drivers/fuse/volume_driver.go
- volume/drivers/mock/driver.mock.go
- volume/drivers/nfs/nfs.go
- volume/drivers/vfs/vfs.go
- volume/volume.go
> Add start and stop volumeWatcher

- csi/csi.go
- csi/csi_test.go
- pkg/grpcserver/grpcserver.go
- vendor/github.com/davecgh/go-spew/LICENSE
- vendor/github.com/davecgh/go-spew/spew/bypass.go
- vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
- vendor/github.com/davecgh/go-spew/spew/common.go
- vendor/github.com/davecgh/go-spew/spew/config.go
- vendor/github.com/davecgh/go-spew/spew/doc.go
- vendor/github.com/davecgh/go-spew/spew/dump.go
- vendor/github.com/davecgh/go-spew/spew/format.go
- vendor/github.com/davecgh/go-spew/spew/spew.go
- vendor/github.com/stretchr/testify/LICENSE
- vendor/github.com/stretchr/testify/assert/assertion_format.go
- vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
- vendor/github.com/stretchr/testify/assert/assertion_forward.go
- vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
- vendor/github.com/stretchr/testify/assert/assertion_order.go
- vendor/github.com/stretchr/testify/assert/assertions.go
- vendor/github.com/stretchr/testify/assert/forward_assertions.go
- vendor/github.com/stretchr/testify/assert/http_assertions.go
- vendor/vendor.json
> PWX-32881: [CSI] Add CSI socket auto-recover when deleted (#2322)

- csi/csi.go
- pkg/loadbalancer/roundrobin.go
> PWX-33631: Lock fixes

- api/server/docker.go
The http volume mount request id is added to the mount path so that containers get mounted to unique paths so that operation on one container does not affect the other.
Closes #
or
PWX-33076
Tested changes by checking on Dev Machine
> Add volume id, gotten from mount request, to the mountpath (#2356)

- api/errors/errors.go
Update Error message, remove labels
PWX-34442
> [PWX-34442] cherry pick

- SDK_CHANGELOG.md
- api/api.go
- api/api.pb.go
- api/api.proto
- api/server/sdk/api/api.swagger.json
- api/spec/spec_handler.go
> Cherry-pick: Spec handler changes for fs format options

- pkg/mount/mount.go
Fixes the race between Mount/Unmount by tracking in progress mounts and the inprogressmount is protected by m.Lock().
Closes #
or
PWX-35452
> PWX-35452: Fix mount race by using Mount/Unmount (#2392)

- api/client/client.go
Reverting 1 problematic commit due to PWX-35553.
PWX-35553
> Revert "fix: rebuild connection cache on timeout"

- pkg/mount/mount.go
* PWX-36522 Add Additional logging in Mount/Unmount/Load/Reload
* Add Additional logging in Mount/Unmount/Load/Reload
---------
Closes #
or
PWX-
> Add Additional logging in Mount/Unmount/Load/Reload (#2427)

- pkg/mount/mount.go
Cherrypick [PR](https://github.com/libopenstorage/openstorage/pull/2403)
Closes #
or
PWX-33580
> PWX-33580 [Cherrypick]: Run stat command with timeout during NFS Unmount (#2403)

- pkg/mount/mount.go
This reverts commit 0ba1aa1e2a52c2c3d596cb51e404f95b4562bbf5. Needs to be merged in 9.9
Closes #
or
PWX-33580
> Revert "PWX-33580 Run stat command with timeout during NFS Unmount (#2403) (#2457)"

- pkg/mount/mount.go
Cherrypick of commit ac3b370c08ba78fcdf5e78c62ab6ce4b3e26025f for PX-3.2.0.
Closes #
or
PWX-33580
> PWX-33580: Run stat command with timeout during NFS Unmount (#2403)

- cluster/manager/manager.go
(cherry picked from commit aa42d863b87edf274a876ceb8ac689626eafcc29)
Closes #
or
PWX-38030
> PWX-38030: Don’t fail if node osdconfig doesn’t exist

- pkg/mount/mount.go
- pkg/mount/mount_test.go
- pkg/options/options.go
Added more tests.
Based on review comments fixed the variable name for options.
Closes #
or
PWX-38618
> Change ForceUnmount to UnmountOnEnoent

- pkg/mount/mount.go
- pkg/mount/mount_test.go
- pkg/options/options.go
> Rel98 38618

- pkg/sched/intervals.go
(cherry picked from commit 2478442d0147651deedf2b0f376f2e0f3fd7ec70)
Cherrypick #2484 
Closes #
or
PWX-
> Add SpeedUpForUT function to sched package (#2484)
