libopenstorage/openstorage

- Dockerfile
Currently, while building, btrfs-progs and its dependencies need to be required to install at host machine.
Dockerized  build environment helps to keep the development machine clean.
Signed-off-by: Kunal Kushwaha <kunal.kushwaha@gmail.com>
> Dockerized build enviornment

- drivers/aws/aws.go
- drivers/aws/aws_test.go
AWS tests won't work for OSS contributors, unless they want to provide their own AWS account/money for testing :) Also better to not modify environment if there is no absolute need to.
> Do not modify environment variables for AWS if AWS keys passed in params, skip AWS test if no AWS environment variable keys

- Dockerfile
https://github.com/libopenstorage/openstorage/issues/25
Have not tested but almost guarantee this fixes it.
Another alternative is https://github.com/peter-edge/go-cacerts but I actually do not use that as much anymore.
> fix ca certificates

- drivers/btrfs/btrfs.go
- drivers/btrfs/unsupported.go
There are other places we should have similar logic, but we'll get there.
> Add btrfs unsupported.go for not linux and cgo

- Makefile
- etc/btrfs/init.sh
I have a feeling that the mount in the script should not be there, when I killed osd after running make launch-local-btrfs, I have no way to unmount /var/lib/openstorage/btrfs, it is always busy.
We need to visit this and do documentation.
> add etc/btrfs/init.sh and make launch-local-btrfs

- api/server/flexvolume.go
- api/server/server.go
- cmd/osd/main.go
- config/config.go
- pkg/flexvolume/client.go
- pkg/mount/mount.go
- Implemented the attach/detach/mount/unmount functions in flexvolume server plugin.
- The flexvolume client now writes to stdout the way kubernetes flexvolume plugin expects for each command.
- Modified the mounts package to provide devicePath given a mount point.
Note: Currently we are storing a mapping of devices and their volume drivers in a in-memory map. If the osd daemon dies and upon restart it does not find a volume driver for a device then it defaults to pwx driver.
> Flexvolume for k8s integration

- .travis.yml
- README.md
This moves openstorage from jenkins to travis. The main reasoning here is:
1. Transparency - it's way easier for people to see/understand what is happening when they see a .travis.yml file, as opposed to jenkins where I couldn't actually figure out what build steps were being run until I logged in (and most people don't have openstorage jenkins credentials)
2. Consistent build environment - if we use travis, we know exactly what we are getting, with a blank virtual machine every time, no more customizations that you also have to go to jenkins to see, travis does allow both sudo and docker --privileged though, so we have plenty of ability to add what we need
3. Deployment - travis is way nicer for deployment, which we will get to next
> Move to Travis CI

- volume/drivers/aws/aws.go
- Fixes issue where scanning for free devices breaks on special device /dev/sda1. 
- AWS volumes now formatted and prepared (EXT4) on create.
- AWS volumes now mounted properly.
> fixing issue #119, fixing aws mount issue

- volume/drivers/common/default_store_enumerator.go
Signed-off-by: Terry Chen <seterrychen@gmail.com>
When using "docker volume ls", the value of locator and volumeLables of `match` method will be nil. It's the root cause of the `nil pointer dereference` problem. (issue #136)
To fix the problem, elem is just added into volumes and `match` function doesn't need to check when locator and labels are nil.
> fix: nil pointer dereference when using "docker volume ls"

- volume/drivers/aws/aws.go
Deleting a EBS volume from Openstorage properly deletes the volume from AWS but leaves a reference inside the store configured:
```
$ openstorage --file config.yaml aws create test --fs ext4 --size 5000
Waiting for state transition to "attached"...
Waiting for state transition to "detached"....
vol-xxxx
$ openstorage --file config.yaml aws enumerate
[{
"id": "vol-xxxxx",
"source": {
"parent": "",
"seed": ""
},
"readonly": false,
"locator": {
"name": "test"
},
"ctime": "2016-09-27T13:18:39Z",
"spec": {
"ephemeral": false,
"size": "5242880000",
"format": "ext4",
"block_size": "32768",
"ha_level": "1",
"cos": 1,
"dedupe": false,
"snapshot_interval": 0,
"shared": false,
"aggregation_level": 0
},
"usage": "0",
"last_scan": "2016-09-27T13:18:39Z",
"format": "ext4",
"status": "up",
"state": …
```
> aws: deleting a EBS volume also delete the reference in the volume store

- cluster/cluster.go
- cluster/database.go
- cluster/manager.go
- volume/drivers/buse/buse.go
Do not hold the lock when Listener's Init functions
are being called.
Cluster And Node Init workflow
1. Take cluster lock
2. Read cluster data from kvdb. If cluster not initialized initialize
the cluster and update cluster data in kvdb as initialized.
3. Release cluster lock
4. Call Listener's Init functions.
5. Take cluster lock
6. Update cluster data with new node info obtained from listener.
7. Release cluster lock
8 Start cluster watch based on last index obtained step 6.
> Reduce the duration for which cluster lock is held

- api/client/cluster/client.go
The client API code was not using the actual server REST-call, but was returning a dummy response.
> PWX-2772.r4: Fixing client API for REST REST cluster/inspect/node

- api/client/cluster/client.go
Removed duplicated client invocation to request.Do(), which initiates the REST call.
> Fixing duplicated REST calls (#175)

- api/api.go
- api/client/cluster/client.go
- api/server/cluster.go
- cluster/cluster.go
- cluster/database.go
- cluster/manager.go
- config/config.go
- volume/drivers/buse/buse.go
1.Added support for api server to accept a put request to update the logging url and enumerate to get the values.
curl -s  -X PUT "http://localhost:9001/v1/cluster/loggingurl?url=harbor.lighthouse.test.com"
curl -s  -X GET -H "Content-type: application/json"  "http://127.0.0.1:9001/v1/cluster/enumerate" | python -m json.tool
Changes are orchestrated via kvdb updates to all nodes. Changes are persisted in the clusterinfo of kvdb.
> PWX-2975: Augment API to set logging url

- .travis.yml
- Makefile
Change the to a tool which provides test coverage results
for all packages and outputs a single file. Now we can display
this file in the logs of Travis. In a future enhancement we will
add support for coveralls.io.
> travis: Coveralls.io support

- api/server/cluster.go
Adding new REST call /nodehealth to report node health status.  Returned status
is similar to /nodestatus, except that it returns '200 OK' only when the node
is OK and ready to serve storage externally.
Ie [HTTP code // body]:
> 503 Service Unavailable // Node status not OK (STATUS_NOT_IN_QUORUM)
> 503 Service Unavailable // Node status not OK (STATUS_INIT)
> 503 Service Unavailable // Node status not OK (STATUS_MAINTENANCE)
> 200 OK // Node status OK
> PWX-4196: Adding /nodehealth REST call

- volume/drivers/aws/aws_storage.go
- volume/drivers/aws/aws_test.go
- Previously we were able to parse devices only in "/dev/xvd[f-p]" format and unnecessarily error out for devices like /dev/xvdcg
> AWS Driver: Do not error out when the block device name is in the "/dev/xvd[b-c][a-z]" format.

- csi/node.go
- csi/node_test.go
Adresses: #236 
```
INFO[0187] Connecting to NBD...
INFO[0187] Attempting to open device /dev/nbd0
INFO[0187] Formatting /dev/nbd0 with FS_TYPE_EXT4
INFO[0187] BUSE mapped NBD device /dev/nbd0 (size=10000000) to block file /var/lib/openstorage/buse/92208801-f13c-4b5f-bca7-045be1369b0f
INFO[0303] BUSE mounted NBD device /dev/nbd0 at /mnt
INFO[0303] Voume 92208801-f13c-4b5f-bca7-045be1369b0f mounted on /mnt
INFO[0329] Volume 92208801-f13c-4b5f-bca7-045be1369b0f unmounted
```
> csi: UnpublishNode

- csi/node.go
- csi/node_test.go
This adds support for NodeProbe and NodeGetCapabilities.
Closes #239
Closes #240
> csi: Support for two NodeXXX functions

- pkg/mount/mount.go
- pkg/options/options.go
Bind mount of fuse mounts show up with fuse name  as device rather than device path being bind mounted. Added mechanism to pass in device name for fuse mounts. 
To elaborate, Mount function is passed with a device parameter and a path to mount the device with. In case of bind mount, both device and mount path are simply paths. After the bind mount, both of them will show with filesystem/device  that is on source path.  So mounter needs to track the mounts with this filesystem "string" passed in the options for bind mounts to reflect the correct mount status.
> Support for bind mount of fuse mounts.

- api/server/cluster_test.go
- cluster/cluster.go
With this change it will now be possible to unit test Cluster manager restful endpoints.  This patter can also be used for testing other singleton object receivers.
Authors of this work:
lpabon, ipochi
> test: Test nodeStatus

- pkg/chattr/chattr.go
- pkg/chattr/chattr_test.go
- pkg/mount/mount.go
We already had chattr utility being used in the mounter package. Moving the logic to its own package so that other components can also use it.
- Adds following three APIs
- Add +i flag on a path (AddImmutable)
- Remove +i flag on a path (RemoveImmutable)
- Checks if +i flag is set on a path (IsImmutable)
- Adds a unit test.
> Add a new utility package for setting/unsetting chattr attributes on a given path.

- api/spec/spec_handler.go
- api/spec/spec_handler_test.go
- Adds io_profile param parsing in common spec_handler. This enables specifying io_profile as inline spec for docker volume creation.
> Add IoProfile to spec handler regex

- cmd/osd/main.go
- csi/controller.go
- csi/controller_test.go
- csi/csisanity_test.go
- vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/README.md
- vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/controller.go
- vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/identity.go
- vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/node.go
- vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/sanity.go
- vendor/github.com/kubernetes-csi/csi-test/utils/grpcutil.go
- vendor/vendor.json
With the new csi-sanity tool and pkg we can now test the CSI APIs act as expected. This PR fixes issues found by csi-sanity and also adds it to the CI system to be used on every `docker-test` run.
* Added support to run CSI drivers from `cmd/osd/main.go`
* Added new `csi/csisanity_test.go` which may not be perfectly setting up NFS as the server. Please make sure I did the right thing.
> CSI Sanity tests and fixes

- pkg/storageops/aws/aws.go
- pkg/storageops/gce/gce.go
- pkg/storageops/storageops.go
By exposing Describe, the caller can get additional information
on the instance.
> storageops: Expose Describe

- pkg/storageops/aws/aws.go
- pkg/storageops/aws/aws_test.go
Uses the root drive to determine if it should use `/dev/sd` or `/dev/xvd` as the prefix.
Closes #305
> aws: Fix attached path

- pkg/options/options.go
In case of kubernetes secrets, we need namespace, the secret name
and the key that is used to encrypt volumes.
These extra keys are needed especially for kubernetes secrets, but can be used 
by other secrets stores if they have namespaces
> Additional keys for extra info needed to get the secrets

- api/api.pb.go
- api/api.proto
- api/status.go
We didn't have a good way to tell a user that their cluster is out of quorum because there is no storage available for the cluster.
This status allows us to handle that.
> New Status.

- api/server/cluster.go
- osdconfig/struct.go
Enables boilerplate CLI code generation
Boilerplate CLI code generation can be automated with these struct tags. Please also use this PR to comment on usage and description text that should go in CLI. By adding struct tags we don't mandate code generation and CLI can always be tweaked as needed. While boilerplate code generation will use reflection to read these struct tags, the generated code does not depend on reflection package.
> custom struct tags for CLI boilerplate code autogeneration

- api/client/cluster/client.go
- cluster/cluster.go
- cluster/manager.go
- cluster/mock/cluster.mock.go
- cmd/osd/main.go
- csi/csisanity_test.go
Signed-off-by: Paul Theunis <paul@portworx.com>
Right now gossip is pinned on 9002. This causes issues for some people if that port is already taken.
If using the library it's now configurable. if using straight OSD we use 9002 still.
> Make gossip port configurable

- cluster/manager.go
Signed-off-by: ganesh@portworx.com
Fixes a bug. Since the value is modified by gossip, make a copy under lock.
If not enumerate returns the original and can cause concurrent read-write error.
Closes #
> Make a copy of node object

- pkg/storageops/aws/aws.go
Debugging code was being printed to stdout and it is not necessary from a library
> aws: Remove debugging code

- volume/drivers/nfs/nfs.go
Signed-off-by: bouviti <timothy.bouvier@verizon.com>
nfs volume driver doesn't check for empty volume names or spaces in volume name during create. nfs volume driver doesn't use uuid for volume id. This PR fixes those things
Closes #321 
> nfs - validate volume names

- pkg/dbg/profile_dump.go
This will increase the go profile trace limit from 1M to 5M so that large trace files are not truncated.
> Increase the goprofile trace limit to 5M.

- api/client/cluster/client.go
- api/server/cluster.go
- cluster/manager.go
- cluster/mock/cluster.mock.go
- osdconfig/api.go
- osdconfig/api_test.go
- osdconfig/interface.go
- pkg/dbg/profile_dump.go
Added node delete method in osdconfig interface. It is required for cleanup of data that in etcd
> Node delete added in osdconfig

- pkg/storageops/gce/gce.go
The create, delete and list methods were assuming that the disk was in the same zone as instance.
> Enable disk list, create and delete outside of the instance zone for GCE

- osdconfig/api.go
an external errors pkg got imported by mistake, fixing it here
> remove external errors pkg in osdconfig

- cluster/manager.go
When node is decommissioned, it needs to be removed from osdconfig as well. This PR adds that logic
> osdconfig during node decommission

- pkg/mount/deleted_mount.go
- pkg/mount/deleted_mount_test.go
- pkg/mount/device.go
- pkg/mount/mount.go
Signed-off-by: Vinod <jvinod@portworx.com>
Support "(deleted)" mount entries in mount table and ability to purge them
replaces https://github.com/libopenstorage/openstorage/pull/373
> Add implementation to support deleted paths in mount table

- cluster/manager.go
this pr bumps up the init of osdconfig in cluster manager boot sequence to avoid panics during maintenance mode
this is in response to failures seen during initialization of cluster manager during maintenance mode
> osdconfig bug fix during init in maintenance mode

- api/api.go
- api/client/volume/client.go
- api/server/backup.go
- api/server/backup_test.go
- api/server/volume.go
- volume/drivers/mock/driver.mock.go
- volume/volume.go
- volume/volume_not_supported.go
The previous Delete has been renamed to DeleteAll to delete all backups for a
given volume
> Add Cloudbackup Delete API to delete backups

- api/spec/spec_handler.go
- api/spec/spec_handler_test.go
Signed-off-by: Paul Theunis <paul@portworx.com>
Use Semicolons to delimit nodes for replicaset, comma's cause issues and single quotes get parsed out by docker.
When specifying multiple nodes on command line for docker volume create use "item1;item2"
> Fix nodelist by utilizing semicolons

- Makefile
Fixes the config path used when launching a container.
Closes None
> Makefile: fix config path used in launch target

- pkg/mount/mount.go
- pkg/mount/nfs.go
Relax fstype checks to prefix checks. Allows nfs and nfs4 mounts
> Relax fstype checks to prefix checks

- pkg/mount/mount.go
- Log when we return error in Unmount for ErrEnoEnt.
- Log when we return nil and do not perform a Mount when mountpoint exists.
Adds logs for better debugging.
> Add logs in mounter for error conditions.

- api/client/volume/client.go
- api/client/volume/volume.go
- cli/volumes.go
- pkg/sanity/backup_restore.go
- pkg/sanity/cluster.go
- pkg/sanity/creds.go
- pkg/sanity/osd_test_util.go
- pkg/sanity/snapshot.go
- pkg/sanity/volume.go
- volume/drivers/pwx/pwx.go
- volume/drivers/test/driver.go
- volume/volume.go
Reverts libopenstorage/openstorage#399
While moving this forward to Px, it looks like the "internal" functions are not used. Looks like it would be easier to just clean up VolumeDriver from the functions we do not use.
> Revert "Cleanup Volume Client REST Golang Interface"

- csi/csi.go
- csi/csi_test.go
- pkg/grpcserver/grpcserver.go
- pkg/grpcserver/grpcserver_test.go
- pkg/grpcserver/server.go
This changes provides management of gRPC servers which will be
shared between CSI and SDK.
Part of #407
> sdk: Create new library for gRPC servers

- .travis.yml
make lint does not did not provide any benefits since it was not run
against any package, but if it failed to download, it would fail travis.
Closes #398
> Remove lint from travis

- pkg/mount/bind_mount.go
- pkg/mount/device.go
- pkg/mount/mount.go
- pkg/mount/mount_test.go
- Implement a new Load and Reload functions for bind mounts.
- To detect the source path of a bind mount use PeerGroup and Root field of a mountpoint.
It adds a new mounter which could be used for bind mounts.
> Add a new mounter implementation for bind mounts.

- api/swagger/swagger.json
- osdconfig/struct.go
Adding an additional param to Vault Config. This let's the clients give their own, secrets backend in vault. Currently we store everything under the default 'secrets/' backend.
Closes #
> Add a secrets backend path param to VaultConfig

- api/api.go
- pkg/sanity/backup_restore.go
- vendor/github.com/cenkalti/backoff/LICENSE
- vendor/github.com/cenkalti/backoff/README.md
- vendor/github.com/cenkalti/backoff/backoff.go
- vendor/github.com/cenkalti/backoff/context.go
- vendor/github.com/cenkalti/backoff/exponential.go
- vendor/github.com/cenkalti/backoff/retry.go
- vendor/github.com/cenkalti/backoff/ticker.go
- vendor/vendor.json
- volume/cloudbackup.go
Cloudbackup is being used in multiple plugins which can use
this API to wait for operations to complete
> Add helper API to wait for completion of cloudbackup operations

- api/api.pb.go
- api/api.pb.gw.go
- api/api.proto
- api/client/sdk/js/api_grpc_pb.js
- api/client/sdk/js/api_pb.js
- api/client/sdk/python/api_pb2.py
- api/client/sdk/python/api_pb2_grpc.py
- api/client/sdk/ruby/api_pb.rb
- api/client/sdk/ruby/api_services_pb.rb
- api/server/sdk/api/api.swagger.json
- api/server/sdk/cluster.go
- api/server/sdk/cluster_test.go
- api/server/sdk/credentials.go
- api/server/sdk/credentials_test.go
- api/server/sdk/volume_node_ops.go
- api/server/sdk/volume_node_ops_test.go
- api/server/sdk/volume_ops.go
- api/server/sdk/volume_ops_test.go
- api/server/sdk/volume_snapshot.go
- api/server/sdk/volume_snapshot_test.go
- hack/git-add-proto-generated.sh
To avoid collisions with other objects part of the REST and Golang interfaces, we need to prefix the request and response SDK objects. This also unifies the messages as some started with the object name and others started with "OpenStorage" to avoid collisions.
Part of #407 
Portworx builds passed with this change.
> sdk: Prefix all Sdk Request and response messages with Sdk

- api/server/sdk/credentials.go
- api/server/sdk/credentials_test.go
- volume/drivers/fake/fake.go
- volume/drivers/fake/fake_test.go
To make the fake driver return valueable data to the SDK, the SDK
implementation (not the API) had to be updated to solve #461
from the SDK side.
Issue #461 next needs the Golang interface to change to return
map[string]map[string]string instead of map[string]interface{}
Part of #407 
Part of #461
> sdk: Support for credentials in Fake driver

- volume/drivers/fake/fake.go
- volume/drivers/fake/fake_test.go
Adds support for CloudBackup and CloudBackupSchedule functions in the fake driver
Closes #470
> fake driver support for CloudBackup and Schedules

- docs/dev-sdk.md
Shows developers how to deal with conflicts on generated files when rebasing.
> Update docs to show how to deal with generated file conflicts

- api/server/cluster.go
- api/server/server.go
- api/server/testutils_test.go
- cluster/cluster.go
- cluster/manager.go
- schedpolicy/fake.go
- schedpolicy/fake_test.go
- schedpolicy/sched_policy.go
The issue is that even though it compiled, the current cluster.Cluster
instance in osd did not have an implementation of the schedulerpolicy.
This would cause panics when the SDK would try to use the functions.
Instead it was in the REST server.
Closes #487
* Move the configuration struct to cluster/ from api/server
* Add an in-memory implementation of the SchedulePolicy implementation
* Change the interface name from SchedulePolicy to
SchedulePolicyProvider so that it does not conflict with the struct in
schedpolicy/ of the same name.
> Add in-memory schedule policy to cluster

- api/client/cluster/client.go
- cluster/cluster.go
- cluster/manager.go
- cluster/mock/cluster.mock.go
- cmd/osd/main.go
- schedpolicy/fake.go
- schedpolicy/fake_test.go
- schedpolicy/sched_policy.go
PR #489 fixed the issue where any Golang function request to the
cluster object would be handled by an in-memory implementation instead
of having the system panic due to having no implementation available.
This could introduce another issue in that it could have a 'silent'
handler which could be unexpected. Instead, this fix makes it so
that the cluster object has a handler which always returns error
on default, removing the silent handler.
> Remove silent handler from cluster object

- api/client/cluster/client.go
- api/server/schedpolicy_test.go
Signed-off-by: Ram Suradkar <ram.suradkar@portworx.com>
This PR chane URI path for schedule Name from resource to instance. If we keep policy name as part of Resource() url request, it will be converted to lowercase by restclient. We need to add URI path as Instance() so that restclient will treat it as it is
Closes #
> Add policy name as part of Instance() to keep it case-sensitive

- Dockerfile.proto
- Makefile
- docs/dev-sdk.md
* No need for developers to install the tools. 
* Now all output of the generated files are generated using the same versions of the tools.
Developers just need to type: `make docker-proto`
Closes #510 
This docker file forces certain versions of the tools due to the following issues:
* https://github.com/golang/protobuf/issues/625
* https://github.com/grpc-ecosystem/grpc-gateway/issues/688
> sdk: Docker proto builder

- etc/config/config-fake.yaml
Rename the mock-sdk-server cluster from an ugly name like `deadbeeeef` to a simple name like `mock`
> sdk: Set mock container cluster name

- pkg/dbg/profile_dump.go
Remove spaces from the profile dump file names. 
Closes # PWX-5813
> PWX-5813: Remove whitespace from .stack & .heap filenames.

- volume/drivers/fake/fake.go
- volume/drivers/fake/fake_test.go
To behave more like the px driver, the fake driver should not allow creation requests with ha level of 0
Closes #538
> Fake driver does not accept ha level of 0

- Makefile
This will enable all the generated code to always be the same
since it was generated with the same tools
> Force usage of docker-proto

- Makefile
The rule `sdk-launch` in the Makefile needs to use `docker-proto`
> sdk: Fix launch-sdk

- pkg/dbg/profile_dump.go
Use a const for the time format.
> PWX-5813: Use const for time format.

- api/api.go
- api/spec/spec_handler.go
add a flag that goes along with zones, nodes, racks which says
that these inputs are only optional.
Signed-off-by: sangleganesh <ganesh@portworx.com>
Closes #
you can suggest some other name too.
> Add spec option requested_nodes_options

- .travis.yml
- Makefile
Provides tests for the SDK api as expected by [sdk-test](https://github.com/libopenstorage/sdk-test). Since sdk-test has been compiled with a previous version of the `api.proto`, it ensures that any changes to the current API does not break previous clients.
> travis: Add SDK tests to travis

- pkg/storageops/aws/aws.go
- pkg/storageops/gce/gce.go
- pkg/storageops/gce/gce_test.go
- pkg/storageops/storageops.go
- pkg/storageops/test/storageops.go
- pkg/storageops/vsphere/vsphere.go
- pkg/storageops/vsphere/vsphere_util.go
1. User doesn't need to give vsphere vmuuid from environment. It's optional.
2. Add DeleteFrom and DetachFrom API's to detach and delete if invoked from a different node
> Fix vmware vm uuid parsing and add DeleteFrom and DetachFrom

- api/server/volume.go
Remove extra error messages it's causing issues when calling multiple times and aggregating the error message.
> Remove extra string and just return the error

- .travis.yml
sdk-test had to be removed to allow for a SDK braking change.
Now that the sdk-test repo has been update, we can add it back to
Travis.
> travis: Add sdk-test back

- pkg/storageops/aws/README.md
- pkg/storageops/aws/aws.go
- pkg/storageops/aws/aws_test.go
- pkg/storageops/utils.go
- volume/drivers/aws/aws.go
- For some instance types like (C5, C5d, i3.metal, M5, M5d, R5, R5d, and z1d)
AWS provisions EBS volumes and exposes them as NVMe drives.
- To an Attach call, AWS takes in the usual /dev/xvd path.
- The device names that is specified in the block device mapping are renamed using NVMe device names (/dev/nvme[0-26]n1).
> AWS StorageOps: Add support for provisioning nvme drives.

- pkg/exec/bin.go
- pkg/storageops/aws/aws.go
- vendor/github.com/codegangsta/inject/LICENSE
- vendor/github.com/codegangsta/inject/README.md
- vendor/github.com/codegangsta/inject/inject.go
- vendor/github.com/codegangsta/inject/update_readme.sh
- vendor/github.com/codeskyblue/go-sh/LICENSE
- vendor/github.com/codeskyblue/go-sh/OLD_README.md
- vendor/github.com/codeskyblue/go-sh/README.md
- vendor/github.com/codeskyblue/go-sh/pipe.go
- vendor/github.com/codeskyblue/go-sh/sh.go
- vendor/github.com/codeskyblue/go-sh/test.go
- vendor/github.com/codeskyblue/go-sh/wercker.yml
- vendor/vendor.json
Use `nvme list` command to fetch the nvme drives.
- The current way of determining the nvme drive name is not reliable as
the drive names might change due to different AMI types. Also the current logic
breaks if an existing drive on the instance has a non-standard names such as /dev/xvdcn
- Instead use `nvme list` command to reliably get the mapping between EBS volumeID and a nvme drive.
Here is a sample output of `nvme list` command.
```
root@ip-172-20-52-215:/# nvme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- -------- …
```
> AWS: Add a reliable way to determine nvme drive names

- api/client/client_test.go
- api/client/request.go
Currently, the client always exits upon receiving service unavailable.
This code change will retry until success and wait for 1 second or amount of seconds suggested in the Retry-After header
This way we can limit the number of connections on the server and ask the client to retry if the queue is full.
> Add retry loop to Request if Service Unavailable. Default wait is 1 second

- .travis.yml
- Makefile
- api/server/sdk/api/api.swagger.json
- api/server/sdk/credentials.go
- api/server/sdk/credentials_test.go
- volume/drivers/fake/fake.go
- volume/drivers/fake/fake_test.go
SDK was incorrectly using map[string]string when it should be using map[string]interface{}
Closes #583
api.swagger.json needed to be rebuilt to make sure it is at the latest. I also added a test for this in travis to check this from now on.
> sdk: Credentials now use map[string]interface{}

- api/server/sdk/credentials.go
- api/server/sdk/credentials_test.go
Missing disableSSL in the Inspect call.
Part of #582
> sdk: Missing disablessl in inspect

- pkg/storageops/gce/gce.go
- pkg/storageops/storageops.go
Need to handle NotFound error explicitly,
so that client know that the drive is not present.
Closes #
> Return VolNotFound if disk in not present in gcloud

- cluster/cluster.go
- cluster/cluster_not_supported.go
- objectstore/objectstore.go
- osdconfig/interface_not_supported.go
- schedpolicy/sched_policy.go
- secrets/secrets.go
The cluster pkg has two primary interfaces
- Cluster
- ClusterListener
The ClusterManger in openstorage implements the Cluster interface. It also invokes the APIs
from the ClusterListener interface. Whoever implements the ClusterListener interface will get
events from the ClusterManager. By adding a NULL implementation we would be able to write tests
for the implementors for ClusterListener interface.
> Add a new NULL implementation for Cluster interface.

- pkg/storageops/vsphere/README.md
- pkg/storageops/vsphere/vsphere.go
- pkg/storageops/vsphere/vsphere_util.go
**What this PR does / why we need it**: This PR adds support for creating vmdks on vSphere datastore clusters (https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.resmgmt.doc/GUID-A2294106-A2B5-4AE4-8F45-9D22B20B5146.html)
References followed: 
- https://github.com/vmware/govmomi/issues/740#issuecomment-416443117
- https://github.com/vmware/govmomi/blob/master/govc/vm/create.go#L331
> Add storage pod/datastore cluster support

- volume/drivers/fake/fake.go
Should not check if the id is currently available for cloud backup list. The volume could have been deleted and we still need its backup to be listed.
> fake: Remove volume id check

- api/server/sdk/credentials.go
If the code did hot have `bucket` set in the map, the SDK would fail. It should allow for `bucket` not be set in credentials.
Closes #611
> sdk:Allow bucket not to be set in credentials

- .travis.yml
Need to add test-sdk back once sdk-test (the repo) has been updated to the latest braking changes
> Reenable test-sdk in travis

- api/api.go
- api/spec/spec_handler.go
- api/spec/spec_handler_test.go
This change is needed to allow the value to be set from
a StorageClass in K8S. Forcing the unsupported fs type
will allow callers to ask the driver to use an unsupported
fs type if possible. For example, using the Portworx driver,
the administrator can force XFS as the file system of the
volume if this setting is set to true.
Closes #633
> Add support for forcing fs to spec_handler.go

- api/spec/spec_handler.go
- api/spec/spec_handler_test.go
PR #634 added support to the spec was missed adding to the spec handler from a string. This PR adds that missing functionality
Closes #633
> Add force fs support to options from a string

- pkg/mount/mount.go
**What this PR does / why we need it**: When scheduling removal of trash dir softlink and their targets, the caller was passing references to the file objects to the sched package. Hence go routines would end up using file objects from the caller and 2 go routines (sched pkg tasks) would try to `removeSoftlinkAndTarget` the same file and skip subsequent ones.
Closes #
> Fix mount trash dir cleanup

- api/server/sdk/server.go
This PR fixes bug, where  zero integer value fields were omitted in REST responses.  Added JsonPb's EmitDefault flag so that fields such as `hour:0` treated as it is.
Closes #
zero integer value fields are omitted in REST responses
> Add EmitDefualt flag while starting grpc server.

- api/server/sdk/server.go
Backport #644 to SDK 0.9.x branch
> Backport of 644

- pkg/mount/device_test.go
Skips failing test only in Travis. This test is making all other PRs fail, so while we figure it out, we will be skipping this test.
> Skip failing tests in travis

- csi/csisanity_test.go
By some luck this test ran successfully until finally some timing
issue showed this error in the test. The test should have
waited until the system was ready before starting the CSI Sanity test
> csi: Fix csisanity tests

- alerts/mock/alerts.mock.go
- api/client/cluster/client.go
- api/server/cluster.go
- api/server/cluster_test.go
- api/server/routes.go
- api/swagger/swagger.json
- cluster/cluster.go
- cluster/cluster_not_supported.go
- cluster/manager/pair.go
- cluster/mock/cluster.mock.go
This can be used to update information about the remote cluster when a driver
thinks that there might be a change in the cluster state (eg nodes added or
removed)
> Add API to refresh cluster pair info

- api/client/request.go
- cluster/manager/pair.go
There is StatusCode() if callers want that. This causes HTTP errors to be
propagated up to the APIs and printed for users which isn't relavent. Also for
an API making other API calls which failed this would print multiple HTTP error
codes.
Closes #
> Don't print HTTP status in error message

- cluster/cluster.go
- cluster/manager/pair.go
Don't need node information. Request for ProcessPair is helpful to pass in.
Also fix source cluster UUID in RefreshRequest
> Update ListnerAPIs for ClusterPair

- .travis.yml
- Dockerfile.osd-dev
- Dockerfile.osd-dev-base
- Dockerfile.proto
- Makefile
- csi/csisanity_test.go
It seems the PR travis tests are taking too long. To try to accelerate them, we are checking if it makes a difference to prebuild the images.
Also removed flaky test csi-sanity until we figure out why it times out in travis.
> Prebuild docker images

- .travis.yml
- Makefile
This will help automatically tag latest and released versions of the mock-sdk-server container. Depending on the branch, if it is on master, it will use the tag `latest` but if it is not, it will use the version of the SDK as the tag.
> Tag mock-sdk-server container automatically

- .travis.yml
- Dockerfile.osd-dev
- Dockerfile.osd-dev-base
- Dockerfile.proto
- Makefile
- csi/csisanity_test.go
- volume/drivers/fake/fake.go
Cherry pick makefile and travis updates to automatically generate and tag a mock-sdk-server for releases.
> Cherry pick Makefile and travis updates

- .travis.yml
- Makefile
- tools/sdkver/sdkver.go
With this patch, we can ensure that only one value changes in the SDK
version. On master, we can ensure only the Minor number changes. In
release branches we can ensure only Patch number changes.
> tools: Verify SDK version in Travis

- Makefile
Travis in master is supposed to build with the `latest` tag.
The issue is that Travis checks out master then checks out a hash
at master. This makes the makefile detect that it is not in master
and therefore does not use the `latest` tag for the container.
> Fix travis mock-sdk-server builds

- api/api.go
- volume/drivers/fake/fake.go
SdkCloudStatusResponse did not have SrcVolumeId populated.
> Fix SrcVolumeId not in SdkCloudStatus

- api/api.go
- api/server/sdk/cloud_backup_test.go
Cloud backup status returned by volume driver was missing these fields, which are already in sdk.
Closes #
> Add Eta fields  to cloudbackup status structure.

- osdconfig/new.go
The osdconfig.NewManager API in openstorage is currently starting a kvdb watch on two sub trees.
However in porx, the NewManager API is called by multiple components which causes unnecessary watches to be started on etcd. Currently there are 12 osdconfig watches instead of 2 started when PX comes up.
A watch on etcd is an expensive op and should be started only once for osdconfig.
Ideally the NewManager API and the watch logic should be separated.
Closes #
> added config caller

- api/api.pb.go
- api/api.proto
- api/server/sdk/api/api.swagger.json
**What this PR does / why we need it**: Making `EnforcementType` and `AffinityRuleType` lower  camelCase as that's how we want users to use it in the Kubernetes spec. Having lower camelCase automatically generates the lookup maps e.g `VolumePlacementRule_EnforcementType_value ` which can key off the lower camelCase from the Kubernetes spec without doing any string manipulation.
Closes #
> update affinity and anti-affinity keys to be lower camelCase

- api/client/request.go
Request URL resource is being changed to lowercase and is breaking PX requests. Don't lowercase the resource.
The request resource is being converted to lowercase.   URL() should not change the request resource in anyway.
> PWX-6987: Request URL resource is being changed to lowercase

- api/client/cluster/client.go
- cluster/cluster.go
- cluster/cluster_not_supported.go
- cluster/manager/manager.go
- cluster/manager/manager_test.go
- cluster/mock/cluster.mock.go
We need a way to update the scheduler node name in cluster database at any point in time instead of just startup. This PR has a proposed method of having separate method to update specifically the scheduler node name, similar to `UpdateLabels()` and `UpdateData()`.
Another solution was to add a new method - `UpdateNode(node api.StorageNode)`, and update all the parameters that have changed in the StorageNode object. We could probably replace the `UpdateLabels` method with this because `StorageNode` object already has the labels.
Let me know what you guys think.
Closes #
> Add method to update scheduler node name of current node

- .travis.yml
Reduce e-mails sent out by travis
> Only send e-mail notifications from Travis when the build fails, or transitions from failure to success.

- api/api.go
- api/server/docker.go
- api/server/server.go
- api/spec/spec_handler.go
- api/testing/testing_test.go
- cmd/osd/main.go
- hack/docker-integration-test.sh
* Switched the following commands to use the sdk server instead of the go interfaces
* create
* remove
* get
* list
* path
* Also made the above commands parse out a token from the docker request and added to sdk request metadata.
* Added hack/docker-integration-test.sh
* starts osd as a background process
* tests docker volume create, inspect, rm
*Which issue(s) this PR fixes** (optional)
Closes #786 
Closes #785 
* includes some code copied from @lpabon's sdk-auth-4-ownership branch which hasn't been merged yet
> Use sdk for docker commands and add docker volume integration test

- api/client/volume/client.go
- api/server/backup.go
- api/server/backup_test.go
- api/server/sdk/volume_node_ops.go
- api/server/testutils_test.go
- api/server/volume.go
- api/server/volume_test.go
This is required to allow authentication/authorization to work on the current API server.
Closes #799 
> Original REST server to redirect requests to the SDK for auth support

- api/ownership.go
- api/ownership_test.go
- api/spec/spec_handler.go
* Fix group admin in ownership. A user with an admin group should be able to access any ACLS.
* Also make sure not to save token in labels
Closes #
> Fix group admin in ownership

- api/server/sdk/volume_ops.go
There is no need to also match the owner's ownership. This would mean
that an admin would only see their own volumes. Instead, let the
permission code determine if they can see the volume
> Fix ownership in enumerate

- api/ownership.go
- api/ownership_test.go
- api/server/sdk/volume_ops.go
The function should return that the caller has no access to update ownership
> Fix ownership update

- api/server/sdk/volume_snapshot.go
- api/server/sdk/volume_snapshot_test.go
The Golang SnapshotEnumerate call does not require a volume id. If non passed, then it returns all snapshots.
* Also added ownership support that was missing
Closes #840
> sdk: SnapshotEnumerate does not require volume id

- api/server/docker.go
- api/server/testutils_test.go
- api/server/volume.go
- volume/drivers/fake/fake.go
Docker get/path are sent without token, so to unblock docker, these functions now do not check auth. Stats and usedsize have issues with Portworx driver, and we will investigate and add them back with auth once we figure out the issue.
Closes #841
Closes #842
> Docker get/path and REST stats/usesize to have no auth

- api/server/sdk/volume_ops.go
If a volumename already existed and was created by the admin/owner, we would return the id to a non authorized user. this checks if the user has access to this volume or not and returns an error if they do not.
Closes #849
> Do not return a volume id if the volume name if not owner

- api/client/request.go
It fixes an issue where we would be spinning up goroutines that stayed open until the first request got closed. Also added Exponential back-off to limit the requests hitting the server.
> Fix goroutine creation bug and add exponential back-off logic

- Makefile
When creating a new release branch, the SDK version major and minor numbers must be frozen.
> Freeze SDK v0.33.x in Release-5.0

- api/server/volume.go
Fixes the nil panic we get when doing a volume update.
We were not checking if Locator was nil and we were not creating a new Spec object.
Closes #852
> Fix panic on volume update

- api/ownership.go
- api/ownership_test.go
Updating the ownership could only be done by the owner or cluster admin, even though a collaborator may have admin access type rights. This PR adds support for collaborators or groups with admin access type rights to also update the ownership. These users cannot change the owner, so the owner still has more rights, in that they can remove access to these collaborator/groups.
Also fixes #863 were the ownership was being changed even though it returned an error.
Closes #862
Closes #863
> Let users with admin access type change ownership

- pkg/auth/token.go
- pkg/auth/token_test.go
- Introduces `TokenClaims()` API similar to `TokenIssuer()`
- `TokenIssuer()` calls `TokenClaims()` in order to get the issuer.
Closes #877 
- Needed to get token claims from a raw token
> add pkg/auth API for token claims

- pkg/grpcserver/grpcutil.go
This makes connections to grpc servers more reliable
> grpc: Add backoff in grpc dial

- api/server/volume.go
Moved volume update code into spec and locator nil check.
We were updating the volume without actually having a spec or locator 
This was breaking attach/mount calls
```
{
"cmd": "HostDetach",
"status": "Ok",
"desc": "Volume successfully detached",
"uuid": [
"test2"
]
}
```
> Only update volume if we truly receive a spec and locator

- api/server/sdk/volume_node_ops.go
- api/server/sdk/volume_node_ops_test.go
Instead they should be done by the driver. For example, if an attach request
is sent, the driver can attach the volume to node A. If another attach
request is sent, the driver can say it is already attached if and only
if node A is still up. If not, then it will attach to another node
if possible.
> Remove idempotency from Volume Node calls

- api/server/volume.go
This is part of #892 and with this change, the REST server can add options to the mount/attach calls.
> API server attach code can now pass options to SDK

- api/server/volume.go
Settings needed to be cleaned up and the one for nodelayBeforeDeletingMountPath fixed
> Fix rest server to sdk mountattach settings

- api/server/sdk/volume_node_ops.go
- api/server/sdk/volume_node_ops_test.go
Remove old docker automatic detach from the SDK
> Remove unnecessary detach from unmount

- pkg/auth/tokengenerator.go
- pkg/auth/tokengenerator_test.go
* The original implementation for `noauth.GetToken()` used to be to `return "", nil`. I changed it to return `errAuthDisabled` to make it match `noauth.GetAuthenticator()`.
* The existing implementation depended on noauth.GetToken returning no error for when auth is not enabled.
Closes #904
> pkg/auth noauth.GetToken should not return an error

- api/server/sdk/cloud_backup_test.go
- api/server/sdk/schedule_policy.go
- api/server/sdk/utils.go
Retain value for Cloud backup schedule is separate field out of schedule format.
Closes #
> SDK to ignore the retain value for cloud-backup schedules.

- Dockerfile.sdk
- cmd/osd/main.go
This allows the mock-sdk-server to access cloud OIDCs
> Add certs to mock-sdk-server

- api/server/middleware_auth.go
- pkg/auth/secrets/secrets.go
- Do not rely on the secretName and secretNamespace passed as VolumeLabels in API request
- Always fetch the latest PVC annotations and use them to get the secretName and secretNamespace
> Middleware Auth: Always fetch PVC annotations for kubernetes auth middleware

- api/server/sdk/cloud_backup.go
- api/server/sdk/credentials.go
- api/server/sdk/identity.go
- api/server/sdk/sdk_test.go
- api/server/sdk/server.go
- api/server/sdk/volume.go
- api/server/sdk/volume_migrate.go
- api/server/sdk/volume_node_ops.go
- api/server/sdk/volume_ops.go
- api/server/sdk/volume_ops_test.go
- api/server/sdk/volume_snapshot.go
- api/server/testutils_test.go
- api/server/volume.go
- pkg/grpcserver/grpcserver_test.go
- pkg/grpcserver/grpcutil.go
- Changed the UseVolumeDrivers API to take in a map of name to VolumeDrivers mapping
- Modified the SDK server, to inspect the context's metadata and select the correct
VolumeDriver to use for the API.
- Modified the REST server, to parse the UserAgent in the incoming request and
set it as a metadata key-value pair in the SDK grpc call's context.
> SDK: Allow registering multiple VolumeDrivers with a single SDK server.

- cluster/manager/manager.go
Modifying the "cluster at maximum capacity" error messages:
* sending ErrNewNodeOverMaxCapacity when NEW node is over cluster capacity
* sending ErrOldNodeOverMaxCapacity when old/pre-existing node is now over cluster capacity
Signed-off-by: Zoran Rajic <zox@portworx.com>
Closes #918
Re-fixing the solution for https://portworx.atlassian.net/browse/PWX-7989 / https://github.com/libopenstorage/openstorage/pull/916  (e.g. the "proper fix")
> Sending different errors when "cluster max capacity" (closes #918)

- cluster/manager/manager.go
The Node status was being set to OK ("operational") before the REST services were started via the listeners. This can cause an issue with automation because automation would immediately issue requests to the node as soon as it becomes OK ("operational") and would receive errors cause the REST services were not avail yet. So don't set the node status to OK until the listeners have started.
Closes #
PWX-7978
> PWX-7978: Set the node status after the listeners have started.

- cluster/manager/manager.go
Cherry pick from #931.
PWX-7978
> PWX-7978: Set the node status after the listeners have started. (#931)

- api/server/sdk/credentials.go
- api/server/sdk/credentials_test.go
Fixes an issue in the SDK credentials where it incorrectly tries to get the ownership from an empty string
Closes #941
> Fix getting ownership from cred params

- api/server/migrate.go
- api/server/migrate_test.go
- volume/drivers/fake/fake.go
Closes #930
When I added ownership checks on the SDK for migration I forgot to add the passthrough on the REST side.
> Add authentication to REST Calls for Migration.

- api/server/sdk/server.go
…driver.
Clients just using the API request do not specify which driver is to be used.   Need a default.   So if the driver name is not found in the map just use the default.  
Closes #
PWX-8054
> If the input driver name is not in the map use the default driver

- api/server/sdk/server.go
Return default only if requested driver does
not exist in the map. Always returns the driver
requested.
Merge in from master :  fd7e0995
Closes #
PWX-8054
> Correct check for drivers existence in the map. (#940)

- api/api.go
- api/server/docker.go
- api/server/server.go
- api/spec/spec_handler.go
- api/spec/spec_handler_test.go
- cmd/osd/main.go
* Add supports to pass token through token_secret in dc/os
Closes #928
> Add support to pass security token through token_secret in DC/OS

- volume/drivers/aws/aws.go
Fixes this go 1.11 vet error:
volume/drivers/aws/aws.go:465:16: Warnf call has arguments but no formatting directives
> Fix go 1.11 vet error

- api/api.go
- api/server/backup.go
- api/server/sdk/cloud_backup.go
Also fix bug in the default creds path for enumerate.
Status conversion to string while enumerating cloud backups.
Closes #
> CloudBackup enumerate status conversion.

- api/server/middleware_auth.go
* Check for empty secret/context on create/delete 
* Return respective error messages.
Closes #953
> in-tree: Add check for empty secret/context on create/delete 

- api/server/migrate.go
- api/server/migrate_test.go
I broke the tracking of migrations by removing it.
Also added back the osterrors check for idempotency.
Closes #930 
> Add TaskId back to MigrationStart

- api/server/migrate.go
- api/server/migrate_test.go
I broke the tracking of migrations by removing it.
Also added back the osterrors check for idempotency.
Cherry-pick from master.
> Add TaskId back to MigrationStart (#964)

- api/server/migrate.go
- api/server/sdk/volume_migrate.go
Handle the error coming back from the driver and retain the old logic of idempotency.
> Fix Idempotency for migration starts

- api/server/sdk/volume_migrate.go
The migration calls were not checking if the cluster and driver were available before making the call.
This PR addresses that.
Need Cherry-pick in 6.0 aswell.
> Add driver check to Migration calls

- api/server/server.go
* If authProviderType is none, we should not attempt to initialize SecretsStore.
Closes #975
> Add check for authProviderType before initializing secretsStore

- api/ownership.go
- api/ownership_test.go
Other services need to determine if the user context is from a storage admin, meaning, one that can access any resource.
> Add API to determie if user is system admin

- csi/controller.go
* Adds csiRequestsSharedVolume back into CreateVolume, which correctly sets whether a volume is shared or not.
> Add csiRequestsSharedVolume back into CreateVolume

- api/server/sdk/volume_ops.go
Fixes: Debug call has possible formatting directive %v
Signed-off-by: Craig Rodrigues <craig@portworx.com>
> Fix 'go vet' on go 1.11 in api/server/sdk/volume_ops.go

- api/server/volume.go
We don't have locks on the inspect we do in our enumerate call.
So skip errors and keep enumerating.
> Do not return errors during enumerate.

- api/server/volume.go
* Do not return errors during enumerate.
We don't have locks on the inspect we do in our enumerate call.
So skip errors and keep enumerating.
Cherry-pick from master.
> Do not return errors during enumerate. (#1019)

- cluster/manager/pair.go
When running 'pxctl cloudmigrate' on a cluster not configured for cloud migration.
Should return proper messages to indicate its unconfigured.
Closes #  PWX-8204
> Return proper error msg for pxctl cloudmigrate.

- cluster/manager/pair.go
* Return proper error msg for pxctl cloudmigrate.
When running 'pxctl cloudmigrate' on a cluster not configured for cloud migration.
Should return proper messages to indicate its unconfigured.
* Change the return err msg.
Closes #
> Return proper error msg for pxctl cloudmigrate. (#1017)

- cluster/cluster.go
- cluster/manager/manager.go
- MarkNodeForRemoval is invoked to notify all the cluster listeners that
the node is going to be marked for decommission and will be removed from
the cluster, before actually removing from the cluster.
- It is invoked in the ClusterManager Remove() API, after the listener.CanNodeRemove()
succeeds for all listeners. The CanNodeRemove API does not indicate the listeners if
the node is really going to be decommissioned, as one listener does not know about
the other listener's status.
> Add MarkNodeForRemoval API to the ClusterListener interface.

- pkg/auth/claims.go
- pkg/auth/claims_test.go
- pkg/auth/oidc.go
- pkg/auth/selfsigned.go
- pkg/auth/token_test.go
* We were getting permission denied because of an empty username before. This makes it more clear that the username cannot be empty, depending on which username type they have setup.
> Add check for empty username during authentication

- api/server/docker.go
- api/spec/spec_handler.go
- api/spec/spec_handler_test.go
* Regex was not general enough - missed case of no context and multiple levels of slashes. 
* Changed to use only secretName for entire secretPath, instead of secretName + secretContext.
> Fix DCOS token secret regex to be more flexible for full dcos secret path

- api/server/docker.go
- api/server/sdk/volume_node_ops.go
- api/server/sdk/volume_node_ops_test.go
- csi/node_test.go
During development of the rerouting of the Docker server, we moved some code into the SDK. This code was being executed for other type of interfaces not just Docker, and was causing issues. Instead, we moved the code back and adjusted it to use the SDK as needed.
> Move docker specific code out of the SDK

- api/server/volume.go
We shouldn't return an error if inspect fails during a snapEnumerate
We can delete volumes while an enumerate is happening. and that results into a not found error.
> Continue on an error during Snap Enumerate

- api/server/volume.go
PR #1045 need a simple adjustment.  The if statement should notify the caller if `ok` is not returned as true.
Closes #
> Adjust the error analysis in SnapEnum

- api/server/sdk/errors.go
- api/server/volume.go
Need to return errors found during inspect in the enumerate handler of the old REST server
> Do not hide errors in enumerate

- pkg/auth/token.go
- pkg/auth/token_test.go
* Adds an option to provide a time duration offset for IAT
> Add option for token creation to subtact a duration from IAT

- api/server/sdk/volume_node_ops.go
Unmount uses a different helper function `checkAccessForVolumeId` that handles inspect/NotFound better
> Change mount permissions check to match attach

- api/server/middleware_auth.go
* Before, we were returning empty secret name and namespace if we did not find the secret in the PVC annotations. 
* With this PR, if we end up with an empty secret name or namespace, we'll attempt to retrieve them from the volume labels.
> in-tree: Get k8s secret from labels if not in PVC annotations

- alerts/alerts.go
- When using the resourceIDFilter, a single alert is returned after filtering all the alerts.
- For a single alert, the correct kvdb API, to use is Delete() instead of DeleteTree()
Closes #
> Delete Alert: When using resourceIDFilter use Delete instead of DeleteTree

- api/server/sdk/rest_gateway.go
- api/server/sdk/server.go
* Makes the gRPC SDK Rest Gateway server extendable. 
Closes #1100
> Add support for REST server extensions

- api/client/cluster/client.go
- api/server/sdk/sdk_test.go
- cluster/cluster.go
- cluster/cluster_not_supported.go
- cluster/manager/manager.go
- cluster/manager/manager_test.go
- cluster/mock/cluster.mock.go
- cmd/osd/main.go
- csi/csisanity_test.go
- Let the Storage Listeners decide the maximum no. of nodes that can be
added to the cluster.
- Add a new StorageListener API CanNodeJoin that gets invoked before joining a node
to a cluster.
> Release 6.1 - Remove the cluster max size check from openstorage

- api/client/cluster/client.go
- api/server/sdk/sdk_test.go
- cluster/cluster.go
- cluster/cluster_not_supported.go
- cluster/manager/manager.go
- cluster/manager/manager_test.go
- cluster/mock/cluster.mock.go
- cmd/osd/main.go
- csi/csisanity_test.go
- Let the Storage Listeners decide the maximum no. of nodes that can be
added to the cluster.
- Add a new StorageListener API CanNodeJoin that gets invoked before joining a node
to a cluster.
> Release 6.0 Remove the cluster max size check from openstorage

- api/client/cluster/client.go
- api/server/sdk/sdk_test.go
- cluster/cluster.go
- cluster/cluster_not_supported.go
- cluster/manager/manager.go
- cluster/manager/manager_test.go
- cluster/mock/cluster.mock.go
- cmd/osd/main.go
- csi/csisanity_test.go
- Let the Storage Listeners decide the maximum no. of nodes that can be
added to the cluster.
- Add a new StorageListener API CanNodeJoin that gets invoked before joining a node
to a cluster.
> Release-4.0 Remove the cluster max size check from openstorage

- csi/csi_test.go
- csi/identity.go
- csi/identity_test.go
- csi/v0.3/csi_test.go
- csi/v0.3/identity.go
- csi/v0.3/identity_test.go
According to the CSI spec it needs to follow
https://tools.ietf.org/html/rfc1035#section-2.3.1 so, or current name of
"com.openstorage.pxd" should instead be "pxd.openstorage.org" (com to
org changed also because we own openstorage.org not openstorage.com)
> CSI Name conformance

- csi/csi_test.go
- csi/identity.go
- csi/identity_test.go
- csi/v0.3/csi_test.go
- csi/v0.3/identity.go
- csi/v0.3/identity_test.go
According to the CSI spec it needs to follow
https://tools.ietf.org/html/rfc1035#section-2.3.1 so, or current name of
"com.openstorage.pxd" should instead be "pxd.openstorage.org" (com to
org changed also because we own openstorage.org not openstorage.com)
> Cherry-pick of #1109

- pkg/grpcserver/grpcutil.go
- If the Connect API, is called for an incorrect grpc endpoint
then the connection never changes to Ready state and the function
returns a timeout error. However the conn object is never cleaned up.
> Fix a memory leak in pkg/grpcserver.Connect API.

- api/server/sdk/volume_migrate.go
- api/server/sdk/volume_migrate_test.go
* This enables ownership for cancel and status.
Closes #1098
* This PR introduces a lot of Volume Inspects on behalf of the user, to check for access. 
* Open to suggestions on optimizing this to reduce the stress on the system.
> Check for ownership on migrate cancel and status

- csi/csi.go
- csi/csi_test.go
- csi/identity.go
- csi/identity_test.go
- csi/v0.3/csi.go
- csi/v0.3/csi_test.go
- csi/v0.3/identity.go
- csi/v0.3/identity_test.go
It may be necessary for the driver caller to use a different
name other than `<driver name>.openstorage.org`
For example, in Portworx we could use something like:
`csi.portworx.com`
> Allow caller to override the CSI driver name

- pkg/role/sdkserviceapi.go
- For some reason, kv.Keys only returns "1st-level" keys. This
does not include superstrings. i.e. if we made a role test.view,
test.view1, and test.view2, then only test.view would appear.
- Once test.view was deleted, test.view1 and test.view2 appear
as one is not a substring of the other.
- kv.Enumerate differs from kv.Keys, as it will return all keys and values.
> Fix role enumerate to return superstrings

- cluster/cluster.go
- cluster/manager/manager.go
Node inspect call should go to a listener to update the node
status object if needed. This will allow the cluster listener
to update the node status with pool and disk information.
> Provide pool and disk information in Node Inspect

- cluster/manager/manager.go
- Currently we create an empty Node object and only update the ID and status in it.
- Due to this the cluster listeners do not get other essential Node info such as IP etc
from the cluster listener updates.
- This change will pre-populate a Node object from gossip if available or resort to creating
an empty object as before.
> In updateClusterStatus prepopulate the cache Node object from gossip info

- csi/controller.go
- csi/controller_test.go
The code to support volume cloning is in the CSI driver, but
it did not advertise that it supported it. This patch informs
the caller that the driver supports volume cloning.
Cloning support:
https://github.com/libopenstorage/openstorage/blob/8c189664c0d92099b83e6d97809074f522669fa1/csi/controller.go#L280-L288
> Support CSI Cloning

- api/client/client_test.go
- api/client/request.go
Moving the creation of the request inside of the for-loop.
After doing some research on the web regarding
` http: ContentLength=xxx  with Body length 0`
It seems that all these issues happen when the request's body buffer has been read.
So we're now creating a new request for every retry and filling it with the body buffer from the original call. (this one has not been read)
> Fix api client request body length 0

- csi/controller.go
- csi/controller_test.go
* Allows PVC labels/annotations to be added to the locator.VolumeLabels
> Get PVC name, namespace, and labels/annotations on Provision

- csi/controller.go
- csi/controller_test.go
cherry-pick of 0191ae9085aeeed90b49dfb6ab131e047b4d479c
> Get PVC name, namespace, and labels/annotations on Provision (#1163)

- api/server/sdk/cloud_backup.go
Failed restores may delete the destination volume, there by ownership checks
filter them out to all(including owner). This commit removes the check for
failed restores, so that they are visible to all including caller.
Closes #
> Skip ownership checks for failed cloud restores.

- api/server/sdk/cloud_backup.go
Failed restores may delete the destination volume, there by ownership checks
filter them out to all(including owner). This commit removes the check for
failed restores, so that they are visible to all including caller.
Closes #
> Skip ownership checks for failed cloud restores. (#1174)

- volume/drivers/common/default_store_enumerator.go
- volume/drivers/common/default_store_enumerator_test.go
The default enumerator has a bug where it only checked the keys not the values.
> Fix label match in enumerate

- api/server/sdk/cloud_backup.go
- api/server/sdk/cloud_backup_test.go
**What this PR does / why we need
Closes #
> Cloud Restores to avoid InternalErr for ErrExists

- api/server/sdk/cloud_backup.go
- api/server/sdk/cloud_backup_test.go
> Cloud Restores to avoid InternalErr for ErrExists (#1192)

- api/api.go
- api/server/docker.go
- api/server/middleware_auth.go
- api/server/server.go
- api/spec/spec_handler.go
- api/spec/spec_handler_test.go
- pkg/auth/secrets/secrets.go
- pkg/auth/secrets/secrets_test.go
* We need auth token support for the remaining secrets providers
Closes #1195
* I reworked `pkg/auth/secrets` to only use a single `Auth` struct, as the implementation for each cloud provider seemed very similar. For providers that have edge cases (DCOS/K8s), we handle those in `Auth.GetToken()`
* SecretPublicData and SecretCustomData are for supporting the various cloud secrets providers. I.e. these fields are required for GCloud and AWS to name a few.
* I changed `api/spec/spec_handler.go` to allow for these fields to be passed in and parsed. 
* There's potentially quite a bit of integration testing involved before …
> Add remaining secrets providers for auth token_secret support

- api/server/volume.go
When attaching an encrypted volume the volume info SecureDevicePath was not being set.  A
deep inspect ensures this gets set.
> Deep inspect for volume set

- csi/controller.go
* Adds PVC Metadata to VolumeLabels
Closes #1207
> Fix to add PVC Metadata to VolumeLabels

- cluster/manager/manager.go
When calling Inspect() or GetData() on ClusterConfig the NodeMap returned from the
Nodeentries in the KV store did not have HWType. This was causing the HWType for all the
nodes to be Unknown thus messing up the identification of the nodes underlying HW.
Signed-off-by: Tapas Sharma <tapas@portworx.com>
Closes #
Tested in test env and prod that the machine HWType returned by Inspect() and GetData() returns proper HWType.
> Add clusterConfig.HWType to selfNode when calling getCurrentNode

- cluster/manager/manager.go
When calling Inspect() or GetData() on ClusterConfig the NodeMap returned from the
Nodeentries in the KV store did not have HWType. This was causing the HWType for all the
nodes to be Unknown thus messing up the identification of the nodes underlying HW.
Signed-off-by: Tapas Sharma <tapas@portworx.com>
Closes #
> [Cherry-pick] Add clusterConfig.HWType to selfNode when calling getCurrentNode

- api/server/sdk/sdk_test.go
- api/server/sdk/volume_ops.go
- api/server/sdk/volume_ops_test.go
- api/server/testutils_test.go
- csi/controller_test.go
- csi/csi_test.go
- pkg/util/wait.go
With this fix, any call creating a volume and noticing it already
exists now checks to make sure that the volume is UP and ready
before returning.
Closes #1180
* Updated the test port randomizer 
* Added a new wait call to `pkg/util` called `WaitForWithContext` which will automatically use the passed default value or the Deadline (WithTimeout) value passed in the context by the caller.
> SDK will now return a volume only if it is ready

- api/server/sdk/volume_ops.go
This patch will add more error information during timeout errors
received during the creation of a volume.
Cherry-pick of #1218
> Add more information to timeout errors

- pkg/util/wait.go
- pkg/util/wait_test.go
The waitfor incorrectly was checking the passed in context
timeout value.
> Fix wait deadline checker

- csi/controller.go
- csi/controller_test.go
- csi/csi.go
- csi/csi_test.go
- csi/node.go
* For CSI secrets compatibility, this adds all req.Secrets to locator.VolumeLabels.
Closes #
> CSI: Add req.Secrets encryption info to locator.VolumeLabels

- csi/controller.go
- csi/controller_test.go
- csi/csi.go
- csi/csi_test.go
- csi/node.go
cherry-pick of 63ac38a0dae3c3574c8c239a7cab5c5700acda04
> CSI: Add req.Secrets to SDK calls for volume encryption (#1226)

- api/api.go
- api/server/sdk/node_test.go
The SDK Node.Inspect call was returning the same disk information
for all disks since the address of the value variable was not
changing.
See https://play.golang.org/p/23YLKwmNPJ6
> Fix disk information in Node.Inspect

- pkg/sanity/volume.go
Signed-off-by: Craig Rodrigues <craig@portworx.com>
This patch removes an unused variable error with go vet 1.11+.
This is needed to run the unit tests on go 1.11+
> Remove unused variable to eliminate go vet 1.11 error

- api/server/sdk/volume_migrate.go
- api/server/sdk/volume_migrate_test.go
Volume migration is taking a while, stuck `filterStatusResponseForPermissions`.
This change makes volume migration use Enumerate over inspect, which should be more efficient.
Closes #
> Change volume migration to use Enumerate instead of Inspect

- SDK_CHANGELOG.md
- api/api.go
- api/api.pb.go
- api/api.proto
- api/server/sdk/api/api.swagger.json
SDK developers where using the ID instead of the uuid of the storage pool. Also fixed the copying of the pools into the SDK object.
> Fix Storage Pools and deprecate id

- SDK_CHANGELOG.md
- api/api.go
- api/api.pb.go
- api/api.proto
- api/server/sdk/api/api.swagger.json
Cherry pick of #1259 on release-7.0.
#1259: Fix Storage Pools and deprecate id
> Automated cherry pick of #1259: Fix Storage Pools and deprecate id

- csi/controller.go
Cherry pick of #1280 on release-7.0.
#1280: Add support for ReadOnlyMany volume creation
> Automated cherry pick of #1280: Add support for ReadOnlyMany volume creation

- cluster/manager/manager.go
cleanup init should be called only at node init.
join is called when node is already part of cluster, so no cleanup init is required.
Closes #
> no cleanup in joinCluster

- cluster/manager/manager.go
cleanup init is called only at node init.
join is called when node is already part of cluster.
Closes #
> no cleanup in joinCluster (#1293)

- csi/node.go
- csi/node_test.go
Before, we were erroring out if unmount could not find the volume ID. 
Closes #
> CSI: Unmount to not fail when volume is not found or deleted

- csi/node.go
- csi/node_test.go
Cherry pick of #1299 on release-7.0.
#1299: CSI: Unmount to not fail when volume is not found or deleted
> Automated cherry pick of #1299: CSI: Unmount to not fail when volume is not found or deleted

- alert/alert_kvdb_test.go
- api/server/sdk/sdk_test.go
- api/server/sdk/volume_ops_test.go
- api/server/testutils_test.go
- cluster/manager/manager_test.go
- cmd/osd/main.go
- csi/csi_test.go
- csi/csisanity_test.go
- csi/v0.3/csi_test.go
- objectstore/fake.go
- pkg/dbg/log.go
- pkg/role/sdkserviceapi_test.go
- pkg/storagepolicy/sdkstorage_policy_ownership_test.go
- pkg/storagepolicy/sdkstoragepolicy_test.go
- schedpolicy/fake.go
- vendor/github.com/portworx/kvdb/Dockerfile.kvdb
- vendor/github.com/portworx/kvdb/common/common.go
- vendor/github.com/portworx/kvdb/consul/client.go
- vendor/github.com/portworx/kvdb/consul/kv_consul.go
- vendor/github.com/portworx/kvdb/etcd/common/common.go
- vendor/github.com/portworx/kvdb/etcd/v2/kv_etcd.go
- vendor/github.com/portworx/kvdb/etcd/v3/kv_etcd.go
- vendor/github.com/portworx/kvdb/kvdb.go
- vendor/vendor.json
- volume/drivers/common/default_store_enumerator_test.go
- volume/drivers/fake/fake.go
- volume/drivers/fake/fake_test.go
- volume/drivers/test/driver.go
update kvdb package and fix the fatalCB - use the one provided in kvdb package (equivalent to logrus.Panicf). 
Closes #
> update kvdb package.

- api/server/sdk/cloud_backup_test.go
- api/server/sdk/utils.go
- api/server/sdk/volume_migrate_test.go
The old behavior was to use driver.Inspect, which is very costly
as it does a deep=true. This ignores the cache layer.
In addition, I've refactored checkAccessForVolumesIds to call
checkAccessForVolumeLocator, where we check for auth enabled and
only call Enumerate.
> SDK: Switch all access checks to use Enumerate when auth is enabled

- api/server/sdk/cloud_backup_test.go
- api/server/sdk/utils.go
- api/server/sdk/volume_migrate_test.go
Cherry pick of #1318 on release-7.0.
#1318: Switch all access checks to use Enumerate when auth is
> Automated cherry pick of #1318: Switch all access checks to use Enumerate when auth is

- cluster/manager/database.go
- cluster/manager/manager.go
- cluster/manager/pair.go
Two changes:
1. Remove Put kvdb operation and use CompareAndSet instead
CompareAndSet is more strict and works even if the lock is released. Added a method to retry the update operation using CAS if the version got changed (due to lock release).
2. Watch changes
- Instead of querying db when there is a watch update, unmarshal data in watch update to get the db state.
- Instead of exiting on watch errors, try to resubscribe.
There needs to be one more change to exit watch if required version is compacted, will do that separately since it requires kvdb package update.
Closes #
> Use compare and set and resubscribe watch

- csi/node.go
Fixes nil pointer panic in csi/node.go
Fixes #1330 
> CSI: Fix panic in NodeUnpublishVolume when err is nil

- csi/node.go
Cherry pick of #1331 on release-7.0.
#1331: CSI: Fix panic in NodeUnpublishVolume when err is nil
> Automated cherry pick of #1331: CSI: Fix panic in NodeUnpublishVolume when err is nil

- api/errors/errors.go
error ErrStoragePoolResizeInProgress would print a golang map in its Error method.
- Convert the Params map to a string of k=v pairs.
Closes #
> Pretty print the error ErrStoragePoolResizeInProgress.

- api/api.go
Panic occurs under certain circumstances when l.VolumeLabels is nil.
Closes #
> Fix panic in MergeVolumeSpecLabels

- api/api.go
Cherry pick of #1353 on release-6.1.
#1353: Fix panic in MergeVolumeSpecLabels
> Automated cherry pick of #1353: Fix panic in MergeVolumeSpecLabels

- pkg/mount/mount.go
- Trying to debug a bug where mounter is reporting a device is not mounted
but the device and mountpoint actually exist.
Closes #
> Add debug logs to mounter.Unmount for ErrNoEnt case.

- cluster/cluster.go
- cluster/manager/manager.go
- Invoke the PreJoin API on all the listeners before joining a node into a cluster.
- Update the node's NonQuorumMember property after invoking the Join API.
Closes #
> Add a PreJoin API to ClusterListener interface.

- cluster/manager/manager.go
if we get entry from kvdb, watch index should be 0 to start
watching new updates.
Closes #
> start watch from index 0.

- SDK_CHANGELOG.md
- api/api.pb.go
- api/api.proto
- api/server/sdk/api/api.swagger.json
- pkg/role/sdkserviceapi.go
- pkg/role/sdkserviceapi_test.go
With this patch the role manager will now have the support
for rules which can deny access. By prefixing an RBAC with '!'
the role manager can deny access to a service or an api.
Closes #
> auth: Support for denial in RBAC

- api/server/sdk/server.go
- api/server/sdk/server_interceptors.go
- api/server/sdk/server_interceptors_test.go
- api/server/testutils_test.go
- cmd/osd/main.go
- pkg/role/sdkserviceapi.go
- pkg/role/sdkserviceapi_test.go
- vendor/github.com/hashicorp/go-multierror/go.mod
Cherry pick of #1382 on release-8.0.
#1382: Update public user to use RBAC negation for volume creation
> Automated cherry pick of #1382: Update public user to use RBAC negation for volume creation

- csi/node.go
This check was originally in place due to https://github.com/container-storage-interface/spec/issues/285, which appears to be fixed.
We also use the file info to check for if a path is a block path or not. We may need to perform a different check when we implement CSI Raw block.
> Remove CSI NodeUnpublish lstat and attachment check

- csi/node.go
- csi/node_test.go
Cherry pick of #1379 on release-8.0.
#1379: Remove CSI NodeUnpublish lstat
> Automated cherry pick of #1379: Remove CSI NodeUnpublish lstat

- api/server/sdk/cluster_test.go
- api/server/sdk/sdk_test.go
- api/server/testutils_test.go
- csi/csi_test.go
- csi/csisanity_test.go
- csi/identity_test.go
Cherry pick of #1198 on release-6.3.
#1198: Fix test port conflicts
> Automated cherry pick of #1198: Fix test port conflicts

- pkg/sched/intervals.go
- pkg/sched/sched_test.go
Returns number of intervals per day for given schedule items.
Adds new api to sched package that returns the number intervals per day.
Useful  for estimating number of times the schedule would be exercised per day.
Closes #
> Add api to sched package

- pkg/sched/intervals.go
- pkg/sched/sched_test.go
* Add new api to sched package
Returns number of intervals per day for given schedule items.
* Address Review comments
Closes #
> Add api to sched package (#1395)

- SDK_CHANGELOG.md
- api/api.pb.go
- api/api.proto
- api/server/sdk/api/api.swagger.json
- pkg/role/sdkserviceapi.go
- pkg/role/sdkserviceapi_test.go
Cherry pick of #1373 on release-7.0.
#1373: auth: Support for denial in RBAC
> Automated cherry pick of #1373: auth: Support for denial in RBAC

- cmd/osd/main.go
- hack/osd-csi.yaml
- hack/setup-kind-csi-cluster.sh
Cherry pick of #1416 on release-7.0.
#1416: Change setup CSI OSD cluster to use DaemonSet instead of
> Automated cherry pick of #1416: Change setup CSI OSD cluster to use DaemonSet instead of

- hack/osd-csi.yaml
Cherry pick of #1417 on release-8.0.
#1417: Revert removal of csi-driver-path volume mount
> Automated cherry pick of #1417: Revert removal of csi-driver-path volume mount

- api/client/request.go
Currently it's possible for the Do() call to receive a 503 status
without a retry-after header.
This results in calls looping every second for 5 minutes.
Fixed this with a check for the header and a boolean check.
> Fix the retry logic of our api client.

- cluster/manager/manager.go
- Use the port configured in cluster database for peer nodes
instead of the port used by this node.
Closes #
> Handle gossip port updates.

- csi/node.go
- csi/node_test.go
- hack/osd-csi.yaml
Cherry pick of #1402 on release-7.0.
#1402: Add support for CSI ephemeral volume creation
> Automated cherry pick of #1402: Add support for CSI ephemeral volume creation

- csi/controller.go
We were leaving csi.openstorage.org parameters around in locator.VolumeLabels. This is not needed,  as we copy these fields directly. These fields are only needed for transporting these values from the our external-provisioner fork to our CSI Driver.
See this example of the existing behavior. Each pvc.Label occurs twice. Once in the `csi.openstorage.org/pvc-labels` field, and once as it's own field.
```
csi.openstorage.org/pvc-labels={"app":"minio"
"chart":"minio-3.0.1",
"heritage":"Helm",
"release":"minio-reliability",
},
csi.openstorage.org/pvc-name=minio-reliability,
csi.openstorage.org/pvc-namespace=minio,
csi.openstorage.org/pvc-annotations={"volume.beta.kubernetes.io/storage-provisioner":"pxd. …
```
> Cleanup csi.openstorage.org parameters after adding to VolumeLabels

- csi/controller.go
Cherry pick of #1440 on release-7.0.
#1440: Cleanup csi.openstorage.org parameters after adding to
> Automated cherry pick of #1440: Cleanup csi.openstorage.org parameters after adding to

- cluster/cluster.go
- cluster/manager/manager.go
- Invoke the PreJoin API on all the listeners before joining a node into a cluster.
- Update the node's NonQuorumMember property after invoking the Join API.
Closes #
> Add a PreJoin API to ClusterListener interface. (#1372)

- api/server/middleware_auth.go
- api/server/volume.go
Failing enumerate requests from k8s in tree driver are in this format:
> 
> 298869c4599 HTTP/1.1 1 1 map[Content-Type:[application/json] Date:[2020-03-06 03:57:28.262818093 +0000 UTC m=+1940.733020398] Accept-Encoding:[gzip] User-Agent:[pxd-sched/v1]] {} <nil> 0 [] false 10.98.204.209:9001 map[] map[] <nil> map[] 192.168.30.80:54159 /v1/**osd-volumes?VolumeID=pvc-8d61ac20-2956-4193-ad6d-1298869c4599** <nil> <nil> <nil> 0xc422434420}
> 
While the k8s in-tree volume client calls "inspect", the server is treating this as an "enumerate" request. See the following:
client call - GET /osd-volumes?VolumeID=<id>
https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/libopenstorage/openstorag …
> Add auth middleware enumerateWithAuth

- api/api.go
Allows users to create incremental backups across multiple credentials with
access to same endpoint.
Closes #
> Cloudbackup label option for ignoring credentials

- api/api.go
Allows users to create incremental backups across multiple credentials with
access to same endpoint.
Closes #
> Cloudbackup label option for ignoring credentials (#1454)

- cluster/cluster.go
- cluster/manager/manager.go
- Whenever a node's status changes to NotInQuorum, Update all the listeners.
Closes #
> Update NotInQuorum self node state to listeners.

- cluster/cluster.go
- cluster/manager/manager.go
- Whenever a node's status changes to NotInQuorum, Update all the listeners.
Closes #
> Update listeners when the node is NotInQUorum

- api/server/sdk/server_interceptors.go
- api/server/sdk/server_interceptors_test.go
Cherry pick of #1489 on release-7.0.
#1489: Remove confusing error message for unauthenticated API calls
> Automated cherry pick of #1489: Remove confusing error message for unauthenticated API calls

- alert/alert_kvdb.go
when kvdb becomes unavailable, a new wrapper is added to it.
query kvdb instance instead of saving it.
Closes #
> do not store kvdb instance

- csi/controller.go
- csi/controller_test.go
- csi/node.go
The CSI Spec has a concept of VolumeCapabilities. One of them that we have been ignoring is the FsType field. Here is where the provisioner adds the capability:
https://github.com/kubernetes-csi/external-provisioner/blob/3d6bea496c305929b2d9b816ed8cfdfad7e4f5ce/pkg/controller/controller.go#L493-L501
We are also allowing a dynamic PV binding to PVC, aka raw block, even though we don't support it. Added a check to disable this.
Closes #
> [CSI] Add support for CSI FsType and deny CSI raw block requests

- csi/controller.go
- csi/controller_test.go
Cherry pick of #1513 on release-8.0.
#1513: Fix FsType resolution to use PX FsType by default
> Automated cherry pick of #1513: Fix FsType resolution to use PX FsType by default

- api/server/docker.go
- hack/docker-integration-test.sh
Cherry pick of #1514 on release-7.0.
#1514: Add support for mount via docker volume ID
> Automated cherry pick of #1514: Add support for mount via docker volume ID

- api/server/middleware_auth.go
- api/server/middleware_auth_test.go
When a request with a token and a user agent was sent to the
old REST server, the auth middleware assumed that it was from
Kubernetes and tried to get the token for the request, ignoring
the token provided.
This fix makes sure that the token provided is used instead.
> Fix token in middleware server

- api/server/docker.go
- In docker/DCOS you can use scaled volumes by running the following docker command
docker run --volume-driver pxd -v secret_key=foo,secure=true,name=scaled_volume,size=10,scale=3:/data -it busybox sh
- The above command will create a volume with provided spec as well as attach it in the busybox container.
- If the same command is now run on another node, the docker volume driver in openstorage will create a new volume as a part
of this scale set and attach it inside the container.
**Problem**: The secret_key provided as a part of the docker run command was not getting propagated to the create call
for volumes done as part of the scale set. So the 2nd volume will not get created in the scale set.
**Solution**: Pass the secret_key got as a part of …
> Handle secure volumes with secret keys for scaled volumes.

- api/server/volume.go
Signed-off-by: adikulkarni0 <adi.kulkarni@portworx.com>
Return error when the call to Inspect fails in volumeSet when called to handle ha-update operation
This caused an issue on the customer side where due to typo it was thought the HA update operation was done and a node failure caused a data loss.
Closes # PWX-10619
> PWX-10619: Fail ha-update when volume is not found

- pkg/mount/bind_mount.go
- pkg/mount/consistent_read.go
- pkg/mount/device.go
- pkg/mount/mount.go
- pkg/mount/nfs.go
Cherry pick of #1592 on release-7.0.
#1592: Add fix for consistent mount table read
> Automated cherry pick of #1592: Add fix for consistent mount table read

- api/api.go
- api/server/sdk/server.go
- api/server/sdk/server_interceptors.go
- api/server/sdk/volume.go
- api/server/sdk/volume_node_ops.go
- api/server/sdk/volume_ops.go
- pkg/grpcserver/grpcutil.go
- pkg/role/sdkserviceapi.go
This patch adds support for the following audits:
* Log when unathenticated
* Log volume id for attach, detach, mount, unmount, created,
delete, and update
Cherry pick of #1613
> More audit log support

- pkg/mount/nfs.go
Cherry pick of #1621 on release-8.0.
#1621: Remove LogDevices in pkg/mount
> Automated cherry pick of #1621: Remove LogDevices in pkg/mount

- api/server/sdk/server_interceptors.go
Error was being returned as:
```
Failed to get volumes: signature is invalid%!(EXTRA []interface {}=[])
```
> Fix error missing optional arg list

- pkg/role/sdkserviceapi.go
- pkg/role/sdkserviceapi_test.go
Users will want to gain access to node information as they do with `kubernetes get nodes`
Closes #
> Allow cloud and node information on default rbac

- cluster/cluster.go
- cluster/manager/manager.go
The Enumerate interface API in cluster listener is not taking in a pointer. This results in all downstream updates to be lost
Simplified golang playground demonstrating the issue
https://play.golang.org/p/nTATQKfd_kD
Closes #
> Fix missing updates in cluster listener enumerate

- api/api.go
- api/server/cluster_test.go
- api/server/sdk/node_test.go
- cluster/manager/manager.go
Apparently, golang cannot use pass by reference. Instead of hacking each usage, updating the api struct itself
https://dave.cheney.net/2017/04/29/there-is-no-pass-by-reference-in-go
Closes #
> use pointer to node in cluster api struct

- api/api.go
- api/server/cluster_test.go
- api/server/sdk/node_test.go
- cluster/cluster.go
- cluster/manager/manager.go
* Fix missing updates in cluster listener enumerate
The Enumerate interface API in cluster listener is not taking in a pointer. This results in all downstream updates to be lost
* fix compile
Closes #
> [cherry-pick]  Fix missing updates in cluster listener enumerate (#1660)

- api/api.go
- api/server/cluster_test.go
- api/server/sdk/node_test.go
- cluster/cluster.go
- cluster/manager/manager.go
* Fix missing updates in cluster listener enumerate
The Enumerate interface API in cluster listener is not taking in a pointer. This results in all downstream updates to be lost
* fix compile
Closes #
> [cherry-pick] Fix missing updates in cluster listener enumerate (#1660)

- pkg/grpcserver/grpcutil.go
The Connect utility method has a hard-coded timeout of 1 min. The client (operator) tries to establish a connection to the grpc server and gets stuck for 1 min when SDK is initializing. To avoid the long blocking call, adding another utility method with a custom timeout.
Closes #
> Grpc connect util with a timeout

- alerts/alerts.go
- alerts/alerts_test.go
- alerts/api.go
- api/server/sdk/sdk_test.go
- Return an error in alerts.NewManager if kvdb instance is not set.
Closes #
> Use the global kvdb instance in alerts package.

- pkg/auth/duration.go
- pkg/auth/duration_test.go
This regex will still parse `1habc` as `1h`.
This adds a check in the regex for end of string.
Closes #
> [pkg/auth] Make duration parse RegEx check end and beginning of string

- api/server/middleware_auth.go
- pkg/auth/secrets/secrets.go
Need to check for nil when accessing the secrets instance
> Check for nil when accessing secret instance

- api/server/middleware_k8s.go
- api/server/middleware_k8s_test.go
- api/server/volume.go
- Reset certain fields in the Set request.
- If the request is coming from a container orchestrator like kubernetes
we only allow setting the volume size in the Set request. All other fields
should be reset to the original values. This needs to be done since kubernetes
in-tree driver has older vendor'ed openstorage code, so any new boolean flags
added to the VolumeSpec will always be set to false overwriting the exising value.
Closes #
> Handle Set requests from CO in auth middleware.

- Makefile
- api/server/middleware_auth.go
- api/server/middleware_auth_test.go
- api/server/testutils_test.go
- api/server/volume_test.go
- cluster/mock/cluster.mock.go
The middleware was designed for release-6.x releases and it did not have the Guest role in the design. This update enabled the middleware to pass requests which have no tokens to the SDK and let it figure out what to do.
**Special Notes**:
The Makefile change and the mock file were needed to make the unit tests pass.
> Need to update middleware to work with Guest Roles

- api/client/client.go
Cherry pick of #1784 on release-9.0.
#1784: Add Patch method to the REST client
> Automated cherry pick of #1784: Add Patch method to the REST client

- csi/node.go
- csi/node_test.go
Due to a change in k8s 1.20:
```
ACTION REQUIRED: For CSI drivers, kubelet no longer creates the target_path for NodePublishVolume in accordance with the CSI spec. Kubelet also no longer checks if staging and target paths are mounts or corrupted. CSI drivers need to be idempotent and do any necessary mount verification.
```
Closes #
> [CSI] Create mountpath if it does not exist

- csi/node.go
- csi/node_test.go
Cherry pick of #1789 on release-9.0.
#1789: Create mountpath if it does not exist
> Automated cherry pick of #1789: Create mountpath if it does not exist

- cluster/manager/manager.go
- cluster/manager/manager_test.go
Signed-off-by: Serhii Aheienko <serhii.aheienko@gmail.com>
Dump output goroutines to a file instead of OS default logger.
Closes #
> cluster/manager: replace logrus.Printf with dbg.LogErrorAndPanicf

- csi/node.go
- csi/node_test.go
Cherry pick of #1795 on release-7.0.
#1795: Add delete and check for mount path in
> Automated cherry pick of #1795: Add delete and check for mount path in

- csi/controller.go
Adds SC parameters to locator.VolumeLabels on CSI volume create.
Closes #
> [CSI] Add SC parameters to locator volume labels

- csi/controller.go
Cherry pick of #1807 on release-9.0.
#1807: Add SC parameters to locator volume labels
> Automated cherry pick of #1807: Add SC parameters to locator volume labels

- volume/drivers/pwx/connection.go
When security is enabled, token is used for authenticating to the APIs. This commit adds constants so that a custom token issuer can be used.
Closes #
> add defaults for the token issuer and its env variable

- volume/drivers/pwx/connection.go
- volume/drivers/pwx/connection_test.go
Env variables for SDK and API port where mixed up.
Fixes an issue found by code inspection.
Closes #
> swap incorrect env variable names

- api/client/cluster/cluster.go
- cluster/manager/pair.go
- This ensures that two clusters can pair over an https endpoint
with TLS config set to skip verify if the clusters are not TLS enabled.
> [cherrypick] Add support for cluster pairing over https endpoints.

- volume/volume.go
This error is better to have in openstorage as many upstream dependencies can depend on it
Closes #
> Move ErrNoVolumeUpdate to volume pkg from Portworx

- api/server/middleware_auth.go
- api/server/testutils_test.go
- api/server/volume_test.go
- cluster/manager/manager.go
* Also fixed an error in auth middleware Enumerate function where
it returns the incorrect object in an error.
Signed-off-by: Luis Pabón <lpabon@purestorage.com>
Auth middleware has the following errors:
- Deletions of volumes that do not exist where returning error. If a volume does not exist, return success according to idempotency rules
- the client.Inspect() call was receiving the incorrect object from the auth middleware. The auth middleware encountered an error condition it returned the error object instead of an empty list as expected by the client.
Closes #
- Unit tests were updated to completely reset the KV stores used by the `fake` driver and the `cluster` …
> Auth-middleware delete is not idempotent

- Dockerfile.osd
- hack/docker-integration-test.sh
Logging into docker via Travis is not straightforward when working with forks. Instead of dealing with that, we can move a problematic base image to use a gcr.io base image instead.
This will lower the amount of rate limiting we hit
Closes #
> Remove golang base image to avoid rate limited docker pull

- csi/controller.go
- csi/node.go
Cherry pick of #1841 on release-9.0.
#1841: Don't log entire request and cleanup logs
> Automated cherry pick of #1841: Don't log entire request and cleanup logs

- api/client/client.go
- api/client/cluster/cluster.go
- cluster/manager/pair.go
- This ensures that two clusters can pair over an https endpoint
with TLS config set to skip verify if the clusters are not TLS enabled.
Closes #
> Add support for cluster pairing over https endpoints.

- cluster/manager/manager.go
Inspect IP and add square brackets around the IPv6 address to be used for the tcp:// & udp:// connect calls.
> Add IPv6 addr handling by adding '[]' around IPv6 connect addresses.

- api/spec/spec_handler.go
- api/spec/spec_handler_test.go
Signed-off-by: Harsh Desai <hadesai@purestorage.com>
pxctl volume create defaults to cow on demand: https://github.com/portworx/porx/blob/master/px/pxctl/spec/volume.yaml#L444
Closes #
> PWX-19496 Default to cow_on_demand for new volumes

- csi/csi.go
- csi/node.go
- csi/node_test.go
* Adds feature flag for enabling inline volume support.
* Inline volume has a security flag in that it allows for creation of volumes without respect to any quotas or k8s RBAC. Customers will need to opt-in to this feature as a result.
* Generic ephemeral volumes should be used instead:
https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes
Closes #
> [CSI] Add feature flag for enabling inline volumes

- Dockerfile.osd-dev
- Dockerfile.osd-dev-base
- Makefile
- api/client/request.go
- api/server/backup.go
- api/server/migrate.go
- api/server/sdk/sdk_test.go
- api/server/volume.go
- api/server/volume_test.go
- csi/controller.go
- csi/node.go
- pkg/auth/oidc.go
- pkg/defaultcontext/default.go
- pkg/defaultcontext/default_test.go
- pkg/grpcserver/grpcutil.go
- pkg/grpcutil/context.go
- pkg/grpcutil/context_test.go
Need timeouts on all RPC calls
* This fix also cleans up the gRPC client connect to use
`grpc.WithBlock()` and `grpc.DialWithContext()` since the APIs we used
to use where experimental.
* Needed to bump the docker-test golang version from 1.10 to something more than 1.13 since we require `http.NewRequestWithContext()`. FYI, when I used 1.15 or 1.16 golang versions, the unit test SDK server did not allow connections. OSD built with 1.15 did allow. Something to investigate later.
> Add timeouts to all RPCs

- api/api.go
- csi/controller.go
- csi/controller_test.go
**What this PR does / why we need it**: Portworx volume spec parameters including `shared`, `sharedv4` and `secure` doesn't apply to pure volume, and shouldn't be set when parsing from storage classes
Closes # [PWX-19922](https://portworx.atlassian.net/browse/PWX-19922)
> [PWX-19922] Don't pass shared, sharedv4, secure parameters to Pure volume specs

- .gitignore
- csi/controller.go
- csi/controller_test.go
- csi/node.go
- csi/node_test.go
- hack/csi-sanity-test.sh
- pkg/mount/mount.go
- pkg/mount/mount_test.go
- pkg/mount/raw_mount.go
- volume/drivers/fake/fake.go
Cherry pick of #1854 on release-9.1.
#1854: Raw Block support
> Automated cherry pick of #1854: Raw Block support

- csi/controller.go
- csi/controller_test.go
Rounds up volume size to nearest GiB to match in-tree behavior:
https://github.com/kubernetes/kubernetes/blob/442a69c3bdf6fe8e525b05887e57d89db1e2f3a5/pkg/volume/portworx/portworx_util.go#L63
Closes #
> [CSI] Round volume size up to nearest GiB

- csi/controller.go
- csi/controller_test.go
Rounds CSI Driver ControllerExpand to nearest GiB 
Matches in-tree resize
https://github.com/kubernetes/kubernetes/blob/830055379b811f69f6f4cd8622bdcf8a08307c9a/pkg/volume/portworx/portworx_util.go#L217
Closes #
> [CSI] Round ControllerExpand up to nearest GiB

- csi/controller.go
- csi/controller_test.go
Cherry pick of #1874 on release-9.1.
#1874: Round ControllerExpand up to nearest GiB
> Automated cherry pick of #1874: Round ControllerExpand up to nearest GiB

- csi/controller.go
Fixes the volume snapshot restore size to be non-zero
> [CSI] Fix Volume Snapshot restore size

- csi/controller.go
Accidental merge w/o approval.
Reverts libopenstorage/openstorage#1881
> Revert "[CSI] Fix Volume Snapshot restore size"

- csi/controller.go
Cherry pick of #1881 on release-9.1.
#1881: Fix Volume Snapshot restore size
> Automated cherry pick of #1881: Fix Volume Snapshot restore size

- csi/controller.go
Cherry pick of #1884 on release-9.0.
#1884: Fix Volume Snapshot restore size
> Automated cherry pick of #1884: Fix Volume Snapshot restore size

- cluster/manager/manager.go
updateClusterStatus() function had dual purpose. It would update the node cache with the new info
received from gossip and it would also notify the listeners of any changes in the node status. If
one of the listeners took long time to process the change notification, node cache updates stopped.
This patch refactors node-cache updates and listener notifications into separate goroutines
so that one does not block the other.
PWX-15391
Carry forward from WIP PR https://github.com/libopenstorage/openstorage/pull/1887
> PWX-15391: separate out node cache update

- cluster/manager/manager.go
- config/config.go
- Added two new options to ClusterConfig
- QuorumTimeoutInSeconds configures time after which an out of quorum node
will restart
- SnapLockTryDurationInMinutes is the time for which
the cluster manager will try acquiring a lock for cluster snapshot
Closes #
> Add Cluster Manager options to set quorum timeout and lock try duration.

- api/server/volume.go
If sharedv4 service spec is specified, we need to send it to the volume update API.
Closes #
PWX-20657
> PWX-20657: allow updating the sharedv4 service spec

- csi/controller.go
- csi/node.go
Cherry pick of #1906 on release-9.1.
#1906: Change CSI driver logs from Debugf to Infof
> Automated cherry pick of #1906: Change CSI driver logs from Debugf to Infof

- csi/node.go
This log is very chatty in Nomad CSI deployments. Lowering it to debug for now.
Closes #
> [CSI] Move a few CSI logs back to Debugf

- csi/node.go
Cherry pick of #1910 on release-9.1.
#1910: Move NodeGetCapabilities and VolumeStats log to Debugf
> Automated cherry pick of #1910: Move NodeGetCapabilities and VolumeStats log to Debugf

- pkg/auth/oidc.go
```
pb-1857: Reverting the defaultTimeout base context in NewOIDC api.
Reverting the defaultTimeout base context as some of the coreos oidc
api takes this context for subsequent call and end up using expired
context.
Signed-off-by: sivakumar subramani <ssubramani@purestorage.com>
```
Closes # PB-1857
> pb-1857: Reverting the defaultTimeout base context in NewOIDC api.

- csi/csi_test.go
- pkg/auth/auth.go
- pkg/correlation/README.md
- pkg/correlation/context.go
- pkg/correlation/correlation_test.go
- pkg/correlation/hook.go
- pkg/correlation/interceptor.go
Cherry pick of #1917 on release-9.2.
#1917: Correlation context pkg feedback
> Automated cherry pick of #1917: Correlation context pkg feedback

- alerts/mock/alerts.mock.go
- api/client/volume/client.go
- api/flexvolume/flexvolume.go
- api/server/docker.go
- api/server/middleware_auth.go
- api/server/sdk/volume_node_ops.go
- api/server/sdk/volume_node_ops_test.go
- api/server/volume_test.go
- cli/volumes.go
- csi/node.go
- csi/node_test.go
- csi/v0.3/node.go
- csi/v0.3/node_test.go
- graph/drivers/layer0/layer0.go
- pkg/correlation/context.go
- pkg/correlation/correlation_test.go
- pkg/correlation/hook.go
- pkg/correlation/interceptor.go
- pkg/sanity/volume.go
- volume/drivers/btrfs/btrfs.go
- volume/drivers/buse/buse.go
- volume/drivers/fake/fake.go
- volume/drivers/fuse/volume_driver.go
- volume/drivers/mock/driver.mock.go
- volume/drivers/nfs/nfs.go
- volume/drivers/test/driver.go
- volume/drivers/vfs/vfs.go
- volume/volume.go
Cherry pick of #1918 on release-9.2.
#1918: Add context to mount/unmount APIs
> Automated cherry pick of #1918: Add context to mount/unmount APIs

- api/client/volume/client.go
- api/flexvolume/flexvolume.go
- api/server/docker.go
- api/server/middleware_auth.go
- api/server/sdk/volume_node_ops.go
- api/server/sdk/volume_node_ops_test.go
- api/server/volume_test.go
- cli/volumes.go
- csi/controller.go
- csi/csi.go
- csi/node.go
- csi/node_test.go
- csi/v0.3/node.go
- csi/v0.3/node_test.go
- graph/drivers/layer0/layer0.go
- pkg/correlation/context.go
- pkg/correlation/correlation_test.go
- pkg/correlation/hook.go
- pkg/correlation/interceptor.go
- pkg/sanity/backup_restore.go
- pkg/sanity/volume.go
- volume/drivers/buse/buse.go
- volume/drivers/fake/fake.go
- volume/drivers/fuse/volume_driver.go
- volume/drivers/mock/driver.mock.go
- volume/drivers/nfs/nfs.go
- volume/drivers/test/driver.go
- volume/drivers/vfs/vfs.go
- volume/volume.go
- volume/volume_not_supported.go
Cherry pick of #1930 on release-9.2.
#1930: Add correlation context to Attach/Detach/MountedAt
> Automated cherry pick of #1930: Add correlation context to Attach/Detach/MountedAt

- pkg/correlation/hook.go
Cherry pick of #1933 on release-9.2.
#1933: Remove error when we can't get correlation context
> Automated cherry pick of #1933: Remove error when we can't get correlation context

- api/client/cluster/client.go
- cluster/cluster.go
- cluster/cluster_not_supported.go
- cluster/manager/manager.go
- cluster/mock/cluster.mock.go
Added a return parameter to be able to indicate a failure
in NodeRemoveDone function.
PWX-21840
> PWX-21840: add an error return to NodeRemoveDone()

- api/server/sdk/volume_ops.go
250 ms of retry interval is too frequent for k8s api calls. This is
resulting in us hitting the k8s rate limiting and a bunch of
issues following that. This patch decreases the frequency and also
the timeout.
250 ms of retry interval is too frequent for k8s api calls. This is
resulting in us hitting the k8s rate limiting and a bunch of
issues following that. This patch decreases the frequency and also
the timeout.
Closes # PWX-21966
> PWX-21966: Increase retry interval and timeout

- pkg/correlation/correlation_test.go
- pkg/correlation/hook.go
Fixes correlation log hook to fire for all log levels
Closes #
> correlation: fix log level for correlation log hook

- pkg/correlation/correlation_test.go
- pkg/correlation/hook.go
Cherry pick of #1966 on release-9.2.
#1966: correlation: fix log level correlation log hook
> Automated cherry pick of #1966: correlation: fix log level correlation log hook

- api/api.go
- cluster/manager/pair.go
Add option to pass remote cluster credential details for RefreshPair api
Closes #
> pass remote cred uuid while calling refresh cluster pair

- api/spec/spec_handler.go
- api/spec/spec_handler_test.go
When explicitly not specified, autofstrim to inherit its value from
nodiscard filed on volume spec.
Closes #
> Autofstrim's default value in volume spec

- api/server/volume.go
Cherry pick of #1998 on release-9.3.
#1998: Only update size for k8s set requests
> Automated cherry pick of #1998: Only update size for k8s set requests

- csi/controller.go
- csi/controller_test.go
Cherry pick of #2000 on release-9.3.
#2000: Add extra idempotency check for resizing
> Automated cherry pick of #2000: Add extra idempotency check for resizing

- api/client/cluster/client.go
- cluster/cluster.go
- cluster/cluster_not_supported.go
- cluster/manager/manager.go
- cluster/mock/cluster.mock.go
- go.mod
- go.sum
- vendor/github.com/libopenstorage/gossip/.travis.yml
- vendor/github.com/libopenstorage/gossip/proto/gossip.go
- vendor/github.com/libopenstorage/gossip/types/types.go
- vendor/modules.txt
Added a method to allow consumers to retrieve the configured values
of the gossip settings.
PWX-23088
will remove the replace directive once the gossip PR is merged
> PWX-23088: expose gossip intervals

- api/client/volume/client.go
- api/server/backup_test.go
- api/server/migrate_test.go
- api/server/sdk/server_interceptors_test.go
- api/server/sdk/volume_ops.go
- api/server/sdk/volume_ops_test.go
- api/server/volume_test.go
- cli/volumes.go
- csi/controller_test.go
- csi/node_test.go
- csi/v0.3/controller.go
- csi/v0.3/controller_test.go
- pkg/sanity/backup_restore.go
- pkg/sanity/cluster.go
- pkg/sanity/snapshot.go
- pkg/sanity/volume.go
- volume/drivers/btrfs/btrfs.go
- volume/drivers/buse/buse.go
- volume/drivers/fake/fake.go
- volume/drivers/fake/fake_test.go
- volume/drivers/fuse/volume_driver.go
- volume/drivers/mock/driver.mock.go
- volume/drivers/nfs/nfs.go
- volume/drivers/test/driver.go
- volume/drivers/vfs/vfs.go
- volume/volume.go
Adds context.Context to openstorage volume driver create/delete
> [correlation] Update volume Create/Delete to use context.Context

- Makefile
Signed-off-by: dahuang <dahuang@purestorage.com>
We were previously building the osd-proto image on the fly. This might create inconsistency between different builds. The new image is push to quay.io and this PR removes the building step.
Closes # none
Built locally to test the changes.
> Use pushed quay.io image in docker-proto

- .github/workflows/on-pr.yml
We don't need this message, sometimes vendor or protobuf update PRs are large.
> Update on-pr action to remove warning about XL size

- api/server/sdk/cloud_backup.go
Enforce auth checks when retoreVolumeID is non-empty.
Closes #
> Allow cloudbackup restore sts with empty volID

- pkg/mount/mount.go
Returns the Mount error directly instead of masking it as a new error.
Callers may depend on this specific error type.
Closes #
> Fix error mask in pkg/mount Mount call

- csi/controller.go
Signed-off-by: Adam Krpan <akrpan@purestorage.com>
Currently we cannot create Pure FA RWX volumes (which should be supported) due to this check. This will check if the proxy spec is a pure type: if it is, it will go through a different set of checks for which volumes are or are not allowed.
PWX-23028 & PWX-23107
This has now been tested with all the various permutations of RWO/RWX, PX or Pure DA volumes, and block/file access modes. All performed as expected (e.g. PX raw RWX is blocked, FA filesystem RWX is blocked, everything else is allowed)
> PWX-23028 & PWX-23107: Changes Pure DA checks for RWX block

- api/client/volume/client.go
- api/server/backup_test.go
- api/server/migrate_test.go
- api/server/sdk/server_interceptors_test.go
- api/server/sdk/volume_ops.go
- api/server/sdk/volume_ops_test.go
- api/server/volume_test.go
- cli/volumes.go
- csi/controller_test.go
- csi/node_test.go
- csi/v0.3/controller.go
- csi/v0.3/controller_test.go
- pkg/sanity/backup_restore.go
- pkg/sanity/cluster.go
- pkg/sanity/snapshot.go
- pkg/sanity/volume.go
- volume/drivers/btrfs/btrfs.go
- volume/drivers/buse/buse.go
- volume/drivers/fake/fake.go
- volume/drivers/fake/fake_test.go
- volume/drivers/fuse/volume_driver.go
- volume/drivers/mock/driver.mock.go
- volume/drivers/nfs/nfs.go
- volume/drivers/test/driver.go
- volume/drivers/vfs/vfs.go
- volume/volume.go
Cherry pick of #2003 on release-9.4.
#2003: Update Create/Delete to use context.Context
> Automated cherry pick of #2003: Update Create/Delete to use context.Context

- api/server/sdk/server_interceptors.go
Cherry pick of #2026 on release-9.4.
#2026: Remove failed token and role from audit logs
> Automated cherry pick of #2026: Remove failed token and role from audit logs

- api/server/sdk/node.go
- cluster/manager/pair.go
- volume/drivers/pwx/connection.go
Use ipv6 friendly px/sdk endpoint building so ipv6 are in in brackets when combining with port
Closes #PWX-23394
NOT TESTED YET
> PWX-23394 Use ipv6 friendly px/sdk endpoint building

- csi/csi.go
Need to also rename server to CSI 1.6
Closes #
> Update server name to CSI 1.6 to match vendor version

- csi/controller.go
Temporarily blocks Pure shared raw block volumes.
> PWX-23530: Disables Pure shared RWX volumes temporarily

- pkg/mount/mount.go
We were swallowing the "path not mounted" error in Unmount(). This
prevented the callers from executing the cleanup such as removing
the path. This patch exposes that error.
PWX-23689
> PWX-23689: surface error from Unmount when path is not mounted

- api/status.go
Signed-off-by: Lakshmi Narasimhan Sundararajan <lns@portworx.com>
Pool maintenance status is incorrectly reported as operational.
This is because the severity flag of the status is not set.
Closes #https://portworx.atlassian.net/browse/PWX-23690
Logs are attached to the below PR
https://github.com/portworx/porx/pull/9315
> PWX-23690: missed pool maintenance severity

- api/server/sdk/rest_gateway.go
- cmd/osd/main.go
Signed-off-by: Priyanshu Pandey <ppandey@purestorage.com>
Bucker handler wasn't set at SDK server and bucket server was not updated at rest gateway server. This was causing Rest and gRPC calls to fail. This change fixes the issue. 
Closes #
tester.server.UseBucketDrivers(tester.b) was setting the driver on the grpc server and hence the unit tests were passing. When executing the Rest API or the grpc,  call was failing because the driver handler was not set. For now. I have updated fake driver handler on the sdk server.
> Register bucket server on rest gateway and update handler on sdk server.

- api/api.go
- api/spec/spec_handler.go
It looks like this change was brought in to vendor manually but somehow didn't actually make it into openstorage? This PR catches it up with all that should be there. Genuinely not sure how this built before...
> PWX-23408: Added missing Pure backend volume name parsing

- cmd/osd/main.go
- csi/controller.go
- csi/controller_test.go
- csi/csi.go
- csi/csi_test.go
Cherry pick of #2048 on release-9.4.
#2048: Add CSI VolumeCreate node round-robin
> Automated cherry pick of #2048: Add CSI VolumeCreate node round-robin

- volume/volume.go
New error message makes it more obvious that the attach failure is because
the volume is not shared.
PWX-24862
> PWX-24862: add more helpful error message for non-shared vol attach

- api/flexvolume/flexvolume.go
- pkg/mount/bind_mount.go
- pkg/mount/custom_mount.go
- pkg/mount/deleted_mount.go
- pkg/mount/device.go
- pkg/mount/device_test.go
- pkg/mount/mount.go
- pkg/mount/mount_test.go
- pkg/mount/nfs.go
- pkg/mount/raw_mount.go
- volume/drivers/nfs/nfs.go
Signed-Off-By: Adam Krpan <akrpan@purestorage.com>
As part of enabling NVMe FlashArray drives, we now have to handle a different format of path as well which is not just a prefix. We specifically need to search for the pattern `/dev/mapper/*24a937` (note the asterisk in the middle). The easiest way I could think of doing this is to change from a string prefix to just passing in regexes instead. That way we can still specify prefixes by using the regex "start" character, but also get more complex cases.
Closes #
Tests to run:
> PWX-24720: Changed mounter to use regex instead of prefix

- api/server/sdk/bucket_ops.go
- api/server/sdk/bucket_ops_test.go
Signed-off-by: Priyanshu Pandey <ppandey@purestorage.com>
Closes #PWX-26155
Pure FB doesn't require setting a region. We are using S3 compatible APIs which expect a region to be passed so passing a default region in create and delete bucket api calls to satisfy the region check.
> PWX-26155: Setting default region for purefb in case of missing region.

- csi/node.go
- csi/node_test.go
* replacing "deep volume inspect" with cheaper equivalent "volume enumerate" call
Signed-off-by: Zoran Rajic <zrajic@purestorage.com>
The `NodeUnpublishVolume()` was using the "expensive" volume-inspect call, just to determine if the volume already existed, so that a different error can be displayed.
As a fix, we're using a "close equivalent" volume-enumerate call, which returns the volume-data from the cache, and avoids "deep volume inspect".  The returned data-structures are identical, also the lower-level function that gets called, is the same between the "volume-inspect" and "volume-enumerate" (except with "deep=true/false" parameter difference).
Closes # PWX-26406
> PWX-26406-pt1: Optimizing NodeUnpublishVolume

- pkg/mount/mount.go
We delay the removal of mountPath by 30 seconds. CSI NodeUnpublishVolume()
call fails if the mountPath still exists and kubelet retries the same call
call in quick succession (before the back-off slows it down). This
causes us to add duplicate tasks for removing the same mountPath.
This patch detects that we already scheduled the mountPath reomoval and
skips adding a task again.
PWX-26615
Tested by adding a temporary debug log line.
> PWX-26615: avoid scheduling duplicate mountpath removal tasks

- pkg/sched/sched.go
- pkg/sched/sched_test.go
In the scheduleTasks function, we iterate over all the tasks to find the ready tasks and
feed them to the workers. When we encounter a runOnce task, we feed it to the workers and
then remove it from the task list. But the removal resets the current element's next pointer
to nil. This terminates the iteration prematurely causing other ready tasks to not get added
to the work queue.
Now, we remove the runOnce tasks outside of the iteration.
Also, added dynamic creation of new worker goroutines.
- start a new batch (10) of worker goroutines if the number of enqueued tasks
is high enough
- excess workers exit after being idle for 30 seconds
- total number of workers is capped at 100
Also,
- fixed staticcheck warnings
- added some basic stats collection …
> PWX-26578: fix the slow task scheduling when runOnce tasks are present

- api/api.go
@pureneelesh noticed this when updating openstorage vendor and this method wasn't in release-9.5 (or master it turns out). Commit where it slipped into Porx is https://github.com/portworx/porx/commit/b8e78101443467105baf1f0414d33e8c7780b825#diff-e295365d6e35f64e39d4b464c205784290d3cc8346f9bfa447f98e6402203f08
> Adds a missing method that slipped into Porx directly

- pkg/sched/sched_test.go
Need to sleep a bit longer to ensure that that tasks get chance to run.
This was the failure in travis build:
--- FAIL: TestMulti (3.00s)
Error Trace:	sched_test.go:106
Error:		Should be true
Messages:	count was 0 for task 0
FAIL
PWX-26709
> PWX-26709: fix the intermittent failure in the unit test

- pkg/mount/mount.go
- pkg/mount/mount_test.go
We hit a race condition in unmount with concurrent iteration and write. This was due to unlocking too early before reading ends. This commit adds the fix and UT to verify.
JIRA: PWX-26792
- Testing: UT passed
- UT error without the fix when run:
`go test  github.com/libopenstorage/openstorage/pkg/mount/... `
```
fatal error: concurrent map iteration and map write
goroutine 153 [running]:
runtime.throw(0xb74a14, 0x26)
/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0001e7c78 sp=0xc0001e7c48 pc=0x4366f2
runtime.mapiternext(0xc0001e7e50)
/usr/local/go/src/runtime/map.go:853 +0x552 fp=0xc0001e7cf8 sp=0xc0001e7c78 pc=0x411492 …
```
> PWX-26792 Fix Race condition in unmount

- csi/controller.go
- csi/controller_test.go
- csi/csi.go
- csi/node.go
- csi/node_test.go
* The kubelet retry logic changes based on the NodePublishVolume / NodeUnpublishVolume status codes returned:
https://github.com/kubernetes/kubernetes/blob/64ed9145452d2d1d324d2437566f1ea1ce76f226/pkg/volume/csi/csi_client.go#L718-L724
* Same with provisioner: https://github.com/kubernetes-csi/external-provisioner/blob/b3d0a89b38dede277ea1a5c200f3da6a328bc3e7/pkg/controller/controller.go#L1803
Closes #
> [CSI] Return non-final NodePublishVolume codes and cleanup

- csi/controller.go
- csi/controller_test.go
- csi/csi.go
- csi/node.go
- csi/node_test.go
Cherry pick of #2114 on release-9.5.
#2114: Return non-final NodePublishVolume codes and
> Automated cherry pick of #2114: Return non-final NodePublishVolume codes and

- pkg/mount/mount.go
- pkg/mount/mount_test.go
We hit a race condition in unmount with concurrent iteration and write. This was due to unlocking too early before reading ends. This commits adds the fix and UT to verify.
JIRA: PWX-26782
Testing: UT passed
Signed-off-by: dahuang <dahuang@purestorage.com>
> PWX-26782 Fix Race condition in unmount (#2116)

- cluster/manager/manager.go
Signed-off-by: Zoran Rajic <zrajic@purestorage.com>
Attempt the forced node-removal, even when node was not found in the ClusterDB
Closes # PWX-26437  (part 1)
> PWX-26437-pt1: Fixing ClusterManager.Remove() with force-flag

- Makefile
The container has all the tools to create proto files. No need for the developer to install any of those tools.
> No need for proto tools

- csi/node.go
This error causes a lot of alarms when performing RCAs. Best to hide it and focus on the actual unmount/detach errors.
Closes #
> [CSI] Change log level for UnpublishVolume mount delete fail

- pkg/mount/mount.go
- pkg/mount/nfs.go
Signed-off-by: dahuang <dahuang@purestorage.com>
Previously, mount path was never removed because scheduled task was cancelled when PX is down. And NFS mount does not pass on the trashlocation for symlink removal. This commit adds the parameter and more logging for when removal happens.
PWX-27439
There will be a second part of related to the ticket on the porx side, to pass the trashlocation down from the mounter.New()
> PWX-27439-pt1 Pass trashlocation in NFS mount

- .travis.yml
Fixes the case where we were getting double travis jobs for every PR. There was a PR travis job and branch travis job.
The branch travis job will only run on master and release-x.y now.
Closes #
> Only run "branch" job on master and release-x.y

- volume/drivers/pwx/connection.go
- volume/drivers/pwx/connection_test.go
Signed-off-by: Priyanshu Pandey <ppandey@purestorage.com>
With TLS disabled,  9023 is being reported as REST port and all the communications to this endpoint are failing.
Closes #PWX-27736
* finalRestPort was set to restPortSecured
* This should happen only when TLS is enabled
> PWX-27736: Use 9001 as the default rest port when TLS is not enabled

- pkg/mount/mount.go
- pkg/mount/nfs.go
Previously, mount path was never removed because scheduled task was cancelled when PX is down. And NFS mount does not pass on the trashlocation for symlink removal. This commit adds the parameter and more logging for when removal happens.
Testing: local testing
JIRA: PWX-27439
Signed-off-by: dahuang <dahuang@purestorage.com>
Closes #
> PWX-27439 release 9.5

- volume/drivers/pwx/connection.go
- volume/drivers/pwx/connection_test.go
* expand to "full" service names when using Kuberenetes DNS for service discovery
* adding Kuberenetes CA for gRPC dial-opts when SSL enabled
Signed-off-by: Zoran Rajic <zrajic@purestorage.com>
These changes are a part of the "auromatic SSL/TLS setup" effort
* change to "full" service names when using Kuberenetes DNS for discovery
- required since the SSL certs are registered to FULL K8s dns-name `portworx-service.kube-system.svc.cluster.local`
- using short `portworx-service.kube-system` dns-alias will result in SSL-validation errors
* adding Kuberenetes CA for gRPC dial-opts when SSL enabled
- required since PX certs will be signed by K8s CA
Closes #  PWX-26915 (part 1)
**Special notes for your …
> PWX-26915-pt1: Auto-TLS support

- csi/csi.go
Dependabot already updated this, but we need to bump the text
Bumps the CSI spec text to 1.7 for PX 2.13.0
Dependabot already updated the dependency. This handles the server text.
Closes #
> Bump CSI version to 1.7

- csi/controller.go
- csi/csi.go
- csi/sched/filter.go
- csi/sched/interceptor.go
- csi/sched/k8s/k8s.go
Closes #
manual test w/ non-forked sidecar:
```
[root@ggriffiths-k8s1-node2 /]# /opt/pwx/bin/pxctl v i pvc-91fb9df7-d398-4a28-ab4b-ea88f8c3cef6
Volume          	 :  338813348211823216
Name            	 :  pvc-91fb9df7-d398-4a28-ab4b-ea88f8c3cef6
Size            	 :  1.0 GiB
Format          	 :  ext4
HA              	 :  2
IO Priority     	 :  LOW
Creation time   	 :  Dec 8 01:04:25 UTC 2022
Shared          	 :  no
Status          	 :  up
State           	 :  detached
Last Attached   	 :  Dec 8 01:04:26 UTC 2022
Labels          	 :  gg-ann-1=hi-ann,gg-sc-param-1=hi,namespace=default,repl=2,gg-lab-1=hi-lab,pvc=mys …
```
> CSI: Add sched filter to avoid forking sidecars

- csi/controller.go
- csi/csi.go
- csi/sched/filter.go
- csi/sched/interceptor.go
- csi/sched/k8s/k8s.go
Cherry pick of #2039 on release-9.6.
#2039: Add CSI standard pvc name/namespace
> release-9.6: Add CSI standard pvc name/namespace and csi filter

- api/server/sdk/volume_ops.go
- csi/controller.go
- csi/controller_test.go
We were seeing some cases where snapshotting retries do not happen. 
This happens when an error is non-final:
https://github.com/kubernetes-csi/external-snapshotter/blob/v6.0.1/pkg/sidecar-controller/snapshot_controller.go#L656-L678
In addition, we were checking the SDK Server response to be `kvdb.ErrNotFound`, but the SDK server only returns grpc status errors. We need to check for codes.NotFound instead.
Closes #
> [CSI] Adjust error codes for snapshotting to be non-final

- csi/node.go
Cherry pick of #2125 on release-9.7.
#2125: Change log level for UnpublishVolume mount delete fail
> Automated cherry pick of #2125: Change log level for UnpublishVolume mount delete fail

- csi/controller.go
- csi/controller_test.go
Cleanup failed snapshot and re-create on next retry
Reproduced the issue, and received the below alert for a failed snapshot create.
```
VOLUME	SnapshotCreateFailure		985152750896393125			ALARM		1	Feb 17 07:08:39 UTC 2023	Feb 17 07:08:39 UTC 2023	Volume (Id: 985152750896393125 Name: snapshot-9a69ca8d-fc5c-4591-80e2-b2ce3bd48d8f Source: 1027903614514639842) snapshot failed with error: All nodes which store the volume data are not online or data is not yet fully replicated on all replicas. Snapshot will automatically complete when volume is ready.	
```
However, the CSI driver cleaned up this failed snapshot and re-create it. The test then passed.
```
Ran 4 of 7227 Specs in 133.751 seconds
SUCCESS! -- 4 Passed | 0 …
```
> CSI: Cleanup failed snapshot and re-create on next retry

- cluster/manager/manager.go
Caught this log line in a torpedo test but wasn't able to figure out what it was calling. This will make it more obvious what is happening for debugging.
> Updates a log line in ClusterManager to help clarify tests

- api/server/sdk/volume_ops.go
- api/server/sdk/volume_ops_test.go
- api/server/sdk/volume_snapshot_test.go
- csi/controller.go
- csi/controller_test.go
- volume/drivers/fake/fake.go
Redo https://github.com/libopenstorage/openstorage/pull/2022 to fix the unit tests additionally.
When volume spec updates are requested, there is a spec reconciliation based on the current state of the volume.
This is done to validate policy settings.
For some volume update operations the spec gets updated only upon action from px-storage and may take time to complete action. Ex. HA Update on a volume needs action from px-storage before the HA level change gets reflected in spec.
So, if there is a subsequent volume update, it is possible for the reconciliation action part of update to pick stale config,
and the final action may be inconsistent after.
To avoid this, whenever volume update is applied, only pass the relevant section of the spec that …
> PWX-23290: handle spec updates with stale config

- alerts/alerts.go
- alerts/alerts_test.go
- alerts/api.go
- alerts/opt.go
PWX-30083: In openstorage either use an option to use ttl to purge alerts or let the alert publisher purge the alerts. Default to the publisher purging the alerts.
> PWX-30083: Optional way to purge alerts

- api/server/sdk/cloud_backup.go
Nearsync migrate does not need credentials and so the cred check is also not needed.
> Remove cred check for nearsync

- api/server/sdk/cloud_backup_test.go
Adds unittest to test no cred requirement for nearsync
> Add unittest for cloudbackupcreate for nearsync

- api/server/sdk/cloud_backup.go
- api/server/sdk/cloud_backup_test.go
Nearsync migrate does not need credentials and so the cred check is also not needed.
> Remove cred check from release-9.7

- api/server/sdk/sdk_test.go
- api/server/sdk/server.go
- api/server/sdk/server_interceptors.go
- api/server/sdk/volume.go
- api/server/sdk/volume_migrate.go
- api/server/testutils_test.go
- cmd/osd/main.go
- csi/csi.go
- csi/csi_test.go
- pkg/correlation/context.go
- pkg/loadbalancer/balancer.go
- pkg/loadbalancer/roundrobin.go
- Move the current round-robin logic used by the CSI driver into a separate package.
- Currently only the VolumeMigrate's Start() API uses the round-robin load balancing functionality.
- Modify the CSI code to use the new round robin package.
The round robin package provides a GetRemoteNodeConnection() API
- The API returns:
- a gRPC client connection object.
- a boolean value indicating whether the connection is to a remote node. It is set to false if the round robin node chosen is the current node itself.
- an error which is returned when the API fails to create a gRPC connection.
Closes #
Eventually we could bake the round-robin balancer into the gRPC interceptor …
> Allow round-robin load balancing of requests for SDK APIs.

- pkg/keylock/keylock.go
Implement trylock - don't keep waiting for the per-volume keyLock forever
Signed-off-by: Dolly Talreja [dtalreja@purestorage.com](mailto:dtalreja@purestorage.com)
Implementation of TryLock.
PWX-21105
> Cherrypick - Pwx 21105 implement Trylock to acquire the per-volume keylock (#2275)

- api/api.go
Add a few consts to the api.
This consts make help proxy client to pass in uniform mount arguments.
> Add some consts to be used for proxy mounts

- csi/controller.go
Cherry pick of #2262 on release-9.7.
#2262: Move ControllerGetVolume log to be Tracef
> Automated cherry pick of #2262: Move ControllerGetVolume log to be Tracef

- csi/csi.go
- csi/csi_test.go
- pkg/grpcserver/grpcserver.go
Add CSI socket auto-recover when deleted.
Closes #
* I first investigated using `fsnotify`, but it added a lot of complexity and seemed overkill. It was also unreliable compared to checking periodically.
* This only takes care of the CSI Driver socket at `/var/lib/kubelet/plugins/pxd.portworx.com/csi.sock`. There is another UDS created by the kubelet registration system for registering the CSI node. That is at `/var/lib/kubelet/plugins_registry/pxd.portworx.com-reg.sock`. A PX Pod restart is required to get that to re-register. Looking into how that can be automated too. This PR only fixes the issue of having to restart portworx to get the CSI Driver socket re-created. …
> PWX-32881: [CSI] Add CSI socket auto-recover when deleted

- csi/csi.go
We were taking two redundant locks: One inside of pkg/loadbalancer and once inside of the CSI function that called into pkg/loadbalancer. This removes the CSI lock.
Closes #
> PWX-33631: Remove global lock on getRemoteConn

- cmd/osd/main.go
- csi/csi.go
- csi/csi_test.go
- pkg/correlation/context.go
- pkg/loadbalancer/balancer.go
- pkg/loadbalancer/roundrobin.go
Cherry-pick pkg/loadbalancer from libopenstorage#2267 
PWX-33631: Hold round-robin lock only when needed (libopenstorage#2335) 
PWX-33631: Remove global lock on getRemoteConn (libopenstorage#2339) 
Closes #
> PWX-33631: Hold round-robin lock only when needed/remove global lock

- pkg/chattr/chattr.go
chattr exits with status 1 for files that are not permitted without force flag
[PWX-32298](https://portworx.atlassian.net/browse/PWX-32298)
It was obsereved that the package was throwing error despite of setting the immutability flags properly.
```sh
Operation not supported while reading flags on /var/lib/kubelet/plugins_registry/pxd.portworx.com-reg.sock
```
Use the package to set immutability flags on node registration socket, 
use the `ForceAddImmutable` method to set the immutability flags 
it can be compared to `AddImmutable` that `ForceAddImmutable` does set the flags successfully
[PWX-32298]: https://portworx.atlassian.net/browse/PWX-32298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …
> fix: chattr exits with status 1 for files that are not permitted without force flag

- pkg/mount/consistent_read.go
… can parse mountinfo file using this function
There are multiple use cases, especially for testing, where we want to parseMountInfo() from a input buffer.
PWX-33647
> PWX-33647: Export parseInfoFile 

- csi/identity.go
Nomad shows this version in the CLI output, so we need to have the correct version exposed here via GetPluginInfo
PWX-34326
Not needed
n/a
> PWX-34326: CSI - fix GetPluginInfo version for CSI

- pkg/mount/consistent_read.go
This PR exposes ParseInfoFile as external function.
This can be used for users wanting to use private files for parsing mountinfo (useful for test cases).
PWX-33647
Manually tested ParseInfoFile() functionality using in memory buffers as file.
> PWX-33647: Export parseInfoFile, For external users. (#2357)

- api/server/docker.go
The volume ID that we get from the http request to mount, is added to the mountpath to make it unique so that volume does not unmount from other pods to which it is attached.
Closes #
or
PWX-33076
> Add volume id, gotten from mount request, to the mountpath

- api/api.go
For some tasks we need to distinguish between block volumes and file volumes.
PWX-34315
> PWX-34315: Add IsPureBlockVolume() interface

- api/errors/errors.go
Update Error message, remove labels
PWX-34442
Testing Done:- 
Before
```
PX drive configuration:
Pool ID: 0
Type:  PX-StoreV2
UUID:  d948cae8-7077-4848-8530-5679e834ba07
IO Priority:  HIGH
Labels:  topology.portworx.io/node=422dcdcd-8b61-0a89-117d-867c72edefbe,kubernetes.io/hostname=rkinhalkar-59-2,topology.portworx.io/datacenter=CNBU,medium=STORAGE_MEDIUM_SSD,kubernetes.io/arch=amd64,kubernetes.io/os=linux,topology.portworx.io/hypervisor=HostSystem-host-35113,beta.kubernetes.io/os=linux,iopriority=HIGH,beta.kubernetes.io/arch=amd64
Size: 186 GiB
Status: In Maintenance
Error Description: Pool or Node is in Maintenance mode
Has metadata:  No
Drives:
0: /dev/sdf, Total size 200 GiB, Online
1: /dev/sdh, Total size 200 GiB, Online
LastOperation  OPERATION_RESIZE
Status:  OPERATION_IN_PROGRESS …
```
> [PWX-34442] Update Error message, remove labels

- csi/controller.go
- csi/controller_test.go
Don't default to sharedv4/shared for RWX Volumes if proxy spec is set
[PWX-33008](https://portworx.atlassian.net/browse/PWX-33008)
Add a proxy spec
RWX or a similar multi-node access mode the volume shouldn't default to sharedv4 if the proxy spec is defined
[PWX-33008]: https://portworx.atlassian.net/browse/PWX-33008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [cherry-pick] Don't default to sharedv4/shared for RWX Volumes if proxy spec is set

- api/server/sdk/volume_migrate.go
Need to explicitly copy the auth token to the outgoing gRPC metadata when forwarding the request to another node.
PWX-35277
Thanks @diptiranjanpx for validating the fix on his cluster that was exhibiting the problem.
> PWX-35277: copy auth token to the outgoing gRPC metadata

- api/server/sdk/volume_migrate.go
Need to explicitly copy the auth token to the outgoing gRPC metadata when forwarding the request to another node.
PWX-35277
> [cherry-pick] PWX-35277: copy auth token to the outgoing gRPC metadata

- api/client/client.go
When creating the http client we cache the client against the host without any expiration
```
c = newHTTPClient(u, nil, 10*time.Second, 5*time.Minute)
httpCache[host] = c
```
In this scenario the node when rebooted was still picking the client from cache for any further request
The cached client had resolved the IP that was assigned to the node prior to reboot hence restarting resolved the issue
A fix for this would be to add a custom round tripper in the transport layer which can invalidate the cache and build a new http client in case of a timeout, this way the it will attempt to resolve the new IP for that host
[PWX-35254](https://portworx.atlassian.net/browse/PWX-35254)
restart …
> fix: rebuild connection cache on timeout

- api/server/sdk/volume_ops.go
In case the underlying storage driver fails to create the volume and puts it in down state and keep it pending forever due to kvdb miss, it could also be that it is unable to rollback too since the kvdb is down.
the check added helps us break out of that loop.
[PWX-35130](https://portworx.atlassian.net/browse/PWX-35130)
While creating a volume if the kvdb is unavailable and the volume enters a down state
CSI should throw an error
[PWX-35130]: https://portworx.atlassian.net/browse/PWX-35130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: throw error if volume is down state and with pending status, it might not recover

- api/api.go
* adding `VolumeSpec.IsNFSProxyVolume()`
Adding a convenient method to query if a volume is a NFS-proxy volume.
PWX-35451 - part2
Tested together w/ https://github.com/portworx/porx/pull/12814 PR
-
> PWX-35451-pt2: NFS-proxy volumes fix

- pkg/loadbalancer/roundrobin.go
- pkg/loadbalancer/roundrobin_test.go
This PR adds a few check before accessing the filteredNodes:
1. If the length is zero, we return empty string and false (isRemote)
2. Before accessing the array, we take a reminder of the currentIndex with the length of the array.
PWX-35601
Added simple UT to check the function
> PWX-35601 Add length check before accessing in round robin

- pkg/loadbalancer/roundrobin.go
- pkg/loadbalancer/roundrobin_test.go
* Add length check before accessing in round robin
This PR adds a few check before accessing the filteredNodes:
1. If the length is zero, we return empty string and false (isRemote)
2. Before accessing the array, we take a reminder of the currentIndex with the length of the array.
JIRA: PWX-35601
Closes #
or
PWX-
> PWX-35601 Add length check before accessing in round robin (#2399)

- pkg/mount/mount.go
NFS Unmount call gets routed to RemoveMountPath, which can get stuck in “stats“ system call in case of an offline NFS server. To rectify this, changes has been made where stat command is run remotely along with a timeout of 60 seconds. This helps the system not to hang and retry the command every one minute.
PWX-33580
I tested the change with an Infof with my name to check if the code is running as expected. The change is working and the retry happens after the specified timeout.
> PWX-33580 Run stat command with timeout during NFS Unmount

- csi/node.go
- csi/node_test.go
Adds check for shared v4 volumes that have a different attach path than the assumed CSI volume path. 
PWX-35351
With the fix, we are able to see Used Space on OCP:
> add check for shared volumes in getVolumeStats

- pkg/mount/mount.go
There are instances where the mount cache table is going out of sync with the disk status and this is causing issues when mount/unmount calls are made. Log all place where we add / delete entry into the mount table.
PWX-36522.
> Add Additional logging in Mount/Unmount/Load/Reload

- api/server/sdk/errors.go
- csi/controller.go
- csi/controller_test.go
- csi/csi.go
- csi/csi_test.go
feat: add delete cloud backup 
fix: create cloud backup ready status update
[PWX-30540](https://portworx.atlassian.net/browse/PWX-30540)
[PWX-30539](https://portworx.atlassian.net/browse/PWX-30539)
[PWX-30540]: https://portworx.atlassian.net/browse/PWX-30540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PWX-30539]: https://portworx.atlassian.net/browse/PWX-30539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add delete cloud backup

- api/spec/spec_handler.go
- api/spec/spec_handler_test.go
Pure NFS Endpoint for FBDA volumes can be either an IP or FQDN. Hence, removing IP format validation as part of this PR.
PWX-36750
> [PWX-36750] Removed IP format validation for Pure NFS endpoint for FBDA

- pkg/mount/mount.go
PWX-36850
Reduce log message level from Into to Debug to avoid log flooding.
> PWX-36850: reduce verbosity of frequent ops by making those Debug

- csi/controller.go
- csi/controller_test.go
This PR introduces the ability to restore cloud snapshots in the OSD CSI driver. It also includes unit tests for this new feature.
- **Feature**: Restore cloud snapshot. This feature allows users to restore cloud snapshots.
- **Tests**: Unit tests for the restore cloud snapshot feature to ensure it works as expected.
**Which issue(s) this PR fixes**
[PWX-36217](https://purestorage.atlassian.net/browse/PWX-36217)
[Testing results](https://purestorage.atlassian.net/browse/PWX-37389)
stc: 
```yaml
apiVersion: core.libopenstorage.org/v1
kind: StorageCluster
metadata:
annotations:
portworx.io/install-source: https://install.portworx.com/?operator=true&mc=false&kbver=1.25.0&ns=portworx&b=true&iop=6&r=17001&c=px-cluster-670d0151-90c8-4 …
```
> [PWX-36217] feat: cloudbackup restore

- api/api.go
- api/server/sdk/volume_ops.go
- csi/controller.go
- csi/controller_test.go
When we make a clone of a volume, or restore from a snapshot, we only get the name info of the volume. We do not get parameters like the pod name, which are required to determine where to place the volume. This adds the pod name as a label in the locator.
PWX-37650
Confirmed volume clones are placed correctly inside of pods as expected.
> PWX-37650: Supports adding the pod name as a locator label for clone/snap restore

- cluster/manager/manager.go
Don’t fail if node osdconfig doesn’t exist
Closes # PWX-38030
```
root@vpatidar-99-3:~# pxctl status 
Status: PX is operational
Telemetry: Disabled or Unhealthy
Metering: Disabled or Unhealthy
License: Trial (expires in 31 days)
Node ID: 3c602ac3-b966-43d3-9669-98a749e8f0d4
IP: 10.13.9.254 
Local Storage Pool: 1 pool
POOL	IO_PRIORITY	RAID_LEVEL	USABLE	USED	STATUS	ZONE	REGION
0	HIGH		raid0		111 GiB	34 MiB	Online	default	default
Local Storage Devices: 1 device
Device	Path		Media Type		Size		Last-Scan
0:0	/dev/sdd	STORAGE_MEDIUM_SSD	128 GiB		11 Jul 24 12:17 UTC
total			-			128 GiB
Cache Devices:
* No cache devices
Metadata Device: 
1	/dev/sdc	STORAGE_MEDIUM_SSD	64 GiB
Cluster Summary …
```
> PWX-38030: Don’t fail if node osdconfig doesn’t exist

- api/server/docker.go
- api/server/sdk/volume_ops.go
- csi/controller.go
- csi/controller_test.go
We are currently setting the pod name in two separate labels in a clone, which aside from a bad UX just makes things more complicated. This collapses it down to one variable.
It also passes all labels in one case instead of just the pod name label.
PWX-38585
**Testing Notes** 
Manually tested pxctl clone and PVC-based clone and confirmed that labels are piped through properly.
Letting UTs run and fail here so I can fix them.
> PWX-38585: Removes extra pod name label

- pkg/mount/mount.go
- pkg/options/options.go
Portworx will try to mount the FBDA volumes using the NFS IP. However if there exists an NFS mountpoint for the same volume which used FQDN then the mountpoint created by Portworx will end up using FQDN as well instead of IP. (This is default NFS behavior)
Now consider we get a Mount request from Kubernetes, we mount it using IP, but shows up as FQDN mount due to 1. We return a success to k8s, but k8s has given up by then, so it sends another request for the same mount. As part of the repeated request we check for an existing mountpoint and there PX detects an FQDN mountpoint instead of IP and errors out the incoming repeated mount request.
PWX-38721
* Created /etc/hosts entries …
> PWX-38721: Fix for ip/host mismatch during FBDA mount.

- cluster/manager/manager.go
With recent update from portworx to pure-px, we were seeing errors during porx upgrade in decoding of gossip message.
_"gossip: Error in unmarshalling peer's local data. Error : gob: name not registered for interface: \"github.com/portworx/porx/vendor/github.com/libopenstorage/openstorage/api.Node\"_
Since the latest porx was not able to decipher the old path, we have changes gob.Register() to gob.RegisterName() to explicitly inform the complete path.
Closes #
PWX-38452 and PWX-38611
Tested the below scenarios - 
1. Upgrade a 3 node cluster from 3.1.4 to 3.2.0 using operator 24.1.1
2. Upgrade a 3 node cluster from 3.1.4 to 3.2.0 using operator 24.2.0-dev
3. Sequentially Upgrade a 10 …
> PWX-38611 : Replacing gob.Register with gob.RegisterName

- api/client/cluster/client.go
- cluster/cluster.go
- cluster/cluster_not_supported.go
- cluster/manager/manager.go
- cluster/manager/manager_test.go
- cluster/mock/cluster.mock.go
- cmd/osd/main.go
With recent update from portworx to pure-px, we were seeing errors during porx upgrade in decoding of gossip message.
"gossip: Error in unmarshalling peer's local data. Error : gob: name not registered for interface: "github.com/portworx/porx/vendor/github.com/libopenstorage/openstorage/api.Node"
Since the latest porx was not able to decipher the old path, we have changes gob.Register() to gob.RegisterName() to explicitly inform the complete path.
Closes #
PWX-38452 and PWX-38611
Testing Notes
Tested the below scenarios -
Upgrade a 3 node cluster from 3.1.4 to 3.2.0 using operator 24.1.1
Upgrade a 3 node cluster from 3.1.4 to 3.2.0 using operator 24.2.0-dev
Sequentially Upgrade a 10 node cluster from 3.1.4 to …
> PWX-38611 : Replacing gob.Register with gob.RegisterName while passing the actual path from PX 

- pkg/mount/mount.go
- pkg/mount/mount_test.go
- This change introduces a SafeEmptyTrashDir function. The safe implementation will only remove symbolic links if the 
prefix of the target matches with the provided path, to ensure we don't remove any other unrelated symbolic links.
- The SafeEmptyTrashDir will take in an arbitrary trash location
and a prefix which needs cleanup.
- The symbolic links and the target paths will only be cleaned up if the target
path has the provided prefix.
Closes #
or
PWX-38618
Added a UT
> PWX-38618: Add SafeEmptyTrashDir function to Mounter.

- pkg/mount/mount.go
- pkg/mount/mount_test.go
1. During DNS resolution, FQDN should match with any IPs.
2. Adding UTs.
Adding UTs
> PWX-38721: Fixing multiple IP and only path mismatch case.

- pkg/mount/mount.go
- pkg/mount/mount_test.go
- pkg/options/options.go
Portworx will try to mount the FBDA volumes using the NFS IP. However if there exists an NFS mountpoint for the same volume which used FQDN then the mountpoint created by Portworx will end up using FQDN as well instead of IP. (This is default NFS behavior)
Now consider we get a Mount request from Kubernetes, we mount it using IP, but shows up as FQDN mount due to 1. We return a success to k8s, but k8s has given up by then, so it sends another request for the same mount. As part of the repeated request we check for an existing mountpoint and there PX detects an FQDN mountpoint instead of IP and errors out the incoming repeated mount request.
PWX-38721
* Created /etc/hosts entries …
> PWX-38721: Fix for ip/host mismatch during FBDA mount. (#2467)

- api/flexvolume/flexvolume.go
- pkg/mount/device_test.go
- pkg/mount/mount.go
- pkg/mount/mount_test.go
- pkg/mount/nfs.go
- volume/drivers/nfs/nfs.go
- While reloading for a specific source, we used to check if the in-memory mount table has an entry for that source.
- Since source can be an IP or DNS, we need to check if any of the existing sources which are DNS entries resolve to the input source. If found use that mount table entry.
Closes #
or
PWX-38760
UTs:
- For now running the existing UTs with setting the handleDNSResolution to true. 
Manual Tests
- Issued a repeated mount request for an NFS share using IP:/exportPath whereas on the host the mountpoint shows up as DNS:/exportPath
- Repeated mount requests for the same targetPath passed
Before
```
[root@pwx-ocp-208-143-qbkb2-worker-0-kzw58 mount]# /opt/pwx/bin/pxctl host …
```
> PWX-38760: Handle NFS Mounter's Reload when both DNS and IPs are configured

- api/api.pb.go
- api/api.proto
- api/client/cluster/client.go
- api/server/sdk/api/api.swagger.json
- cluster/cluster.go
- cluster/cluster_not_supported.go
- cluster/manager/manager.go
- cluster/manager/manager_test.go
- cluster/mock/cluster.mock.go
- cmd/osd/main.go
- pkg/mount/mount_test.go
With recent update from portworx to pure-px, we were seeing errors during porx upgrade in decoding of gossip message.
"gossip: Error in unmarshalling peer's local data. Error : gob: name not registered for interface: "github.com/portworx/porx/vendor/github.com/libopenstorage/openstorage/api.Node"
Since the latest porx was not able to decipher the old path, we have changes gob.Register() to gob.RegisterName() to explicitly inform the complete path.
Closes #
PWX-38452 and PWX-38611
Testing Notes
Tested the below scenarios -
Upgrade a 3 node cluster from 3.1.4 to 3.2.0 using operator 24.1.1
Upgrade a 3 node cluster from 3.1.4 to 3.2.0 using operator 24.2.0-dev
Sequentially Upgrade a 10 node cluster from 3.1.4 to …
> PWX-38611 : [Cherry-pick]Replacing gob.Register with gob.RegisterName while passing the actual path from PX

- api/flexvolume/flexvolume.go
- pkg/mount/device_test.go
- pkg/mount/mount.go
- pkg/mount/mount_test.go
- pkg/mount/nfs.go
- volume/drivers/nfs/nfs.go
* PWX-38760: Handle NFS Mounter's Reload when both DNS and IPs are configured.
- While reloading for a specific source, we used to check if the in-memory mount table has an entry for that source.
- Since source can be an IP or DNS, we need to check if any of the existing sources which are DNS entries resolve to the input source. If found use that mount table entry.
Closes #
or
PWX-38760
> PWX-38760: Handle NFS Mounter's Reload when both DNS and IPs are configured (#2477)

- api/server/sdk/volume_node_ops.go
- api/server/volume.go
While debugging issues related to hung mount while using in tree driver, we noticed that there is no clear signal using logs to check when the Open Storage API call was completed. This PR adds logs to help with this scenario
PWX-38876 (Not actual fix)
```
@sradhakrishnan-6-1 portworx[470138]: time="2024-09-05T08:01:04Z" level=info msg="Attachment completed for volume" file="volume.go:440" Driver=pxd ID=1100666696692950591 Request=volumeSet component=openstorage/api/server
@sradhakrishnan-6-1 portworx[470138]: time="2024-09-05T08:01:04Z" level=info msg="Mount completed for volume on path /var/lib/osd/pxns/1100666696692950591" file="volume.go:460" …
```
> Improve logging for better debugging of attach/mount and unmount

- api/server/volume.go
Volume clone requests can have additional labels, which were not being plumbed through.
PWX-38585
> PWX-38585: Adds additional labels to clone requests

- cluster/cluster.go
- cluster/manager/manager.go
- cluster/mock/cluster_listener.mock.go
Allowing forceRemove during CanNodeRemove
PWX-39064:
In the Porx PR : https://github.com/pure-px/porx/pull/14042
> PWX-39064: Allow force option to be passed to CanNodeRemove

- cluster/manager/manager.go
- cluster/manager/manager_test.go
This reverts commit 24e88ce1ee8f298a62c41cead5aee13d7ae27cfb.
Reverting the changes as we need more analysis on the issue.
Closes #
or
PWX-
1. make pr-verify o/p
```
make pr-verify
go fmt  | grep -v "api.pb.go" | wc -l | grep "^0";
package github.com/libopenstorage/openstorage: no Go files in /root/go/src/github.com/libopenstorage/openstorage
0
go run tools/sdkver/sdkver.go --check-major=0 --check-minor=101
0.101.54
git-validation -run DCO,short-subject
INFO[0000] using commit range: 2872d00f..a81e7a46
* a81e7a46 …
```
> Revert "PWX-37595: honour force flag over node status (#2479)"

- api/api.go
- csi/controller.go
- csi/controller_test.go
This PR will set the creation time of the snapshot in CSI response object as the local snapshot time. As per CSI spec, the creation time of the snapshot is the time when storage system took the point in time snapshot.
Closes #
or
PWX-39688
Tested creating a snapshot and made sure that the creation time is coming up in the kubectl get volumesnapshot <name> -o yaml output
> PWX-39688 Wai till local snapshot is taken to send create snapshot response in case of cloud snap

- csi/controller.go
- csi/controller_test.go
For Pure File volumes, if an export rule is not set, set it to *(ro) if the pvc mode is ReadOnlyMany. This way customers can choose not to specify an export rule in storage class. Since *(rw) is the default case, we are not setting that explicitly and assume that the NFS server will set the right default.
Closes #
or
PWX-37757
> Set export rules when ROX access mode is used in Pure File Volumes

- api/client/volume/client.go
Stork was sending the volume IDs in the Locator struct data but that was not being added to the query params in the volume enumerate REST API call. This PR fixes that.
[PWX-42338
](https://purestorage.atlassian.net/browse/PWX-42338)
**Testing Notes** 
```
In a 10 node cluster with 750 volumes and 750 snaps, when putting 30 pods in scheduling in parallel, we are seeing following
With released stork:
Filter request handling avg time taken is - 3-5secs
Priortize request handling avg time taken is - 5-7 secs
With the fix:
Filter request handling avg time taken is - 0-1sec
Priortize request handling avg time taken is - 0-1sec
```
> PWX-42338: add volumelocator id in query params for volume enumerate api call

- api/client/volume/client.go
Fixes adding query parameter for multiple volume IDs in REST API call.
> PWX-42924: fix adding multiple volume id as query param in enumerate call
